---
name: Setup
description: Setup .NET and install dependencies.

inputs:
  dotnet_version:
    description: The .NET SDK versions to install.
    required: false
    default: |
      6.0.x
      8.0.x
  install_dependencies:
    description: Install dependencies.
    required: false
    default: 'true'

runs:
  using: composite
  steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ inputs.dotnet_version }}
    - name: Cache NuGet packages
      if: inputs.install_dependencies == 'true'
      uses: actions/cache@v4
      with:
        path: ~/.nuget/packages
        key: nuget-${{ runner.os }}-${{ hashFiles('**/*.csproj', '.config/dotnet-tools.json') }}
        restore-keys: nuget-${{ runner.os }}-
    - name: Restore tools
      if: inputs.install_dependencies == 'true'
      shell: bash
      run: dotnet tool restore
    - name: Restore dependencies
      if: inputs.install_dependencies == 'true'
      shell: bash
      run: dotnet restore ./output/csharp
