// <auto-generated>
//   Generated by codegen/smith.ts from @seamapi/types. Do not edit.
// </auto-generated>
#nullable enable
#pragma warning disable CS0618 // The generated code references its own deprecated members.
using System.Runtime.Serialization;
using System.Text.Json;
using System.Text.Json.Serialization;
using Seam.Http;
using Seam.Models;

namespace Seam.Routes
{
    public sealed class AccessCodesUnmanaged
    {
        private readonly SeamHttpTransport _transport;
        private readonly ActionAttemptWait _waitForActionAttemptDefault;

        internal AccessCodesUnmanaged(
            SeamHttpTransport transport,
            ActionAttemptWait waitForActionAttemptDefault
        )
        {
            _transport = transport;
            _waitForActionAttemptDefault = waitForActionAttemptDefault;
        }

        /// <summary>
        /// Request parameters for Convert an Unmanaged Access Code.
        /// </summary>
        public sealed record ConvertToManagedRequest
        {
            /// <summary>
            /// ID of the unmanaged access code that you want to convert to a managed access code.
            /// </summary>
            [JsonPropertyName("access_code_id")]
            public required string AccessCodeId { get; init; }

            /// <summary>
            /// Indicates whether [external modification](https://docs.seam.co/low-level-apis/smart-locks/access-codes#external-modification) of the access code is allowed.
            /// </summary>
            [JsonPropertyName("allow_external_modification")]
            public bool? AllowExternalModification { get; init; }

            /// <summary>
            /// Indicates whether to force the access code conversion. To switch management of an access code from one Seam workspace to another, set `force` to `true`.
            /// </summary>
            [JsonPropertyName("force")]
            public bool? Force { get; init; }

            /// <summary>
            /// Indicates whether [external modification](https://docs.seam.co/low-level-apis/smart-locks/access-codes#external-modification) of the access code is allowed.
            /// </summary>
            [JsonPropertyName("is_external_modification_allowed")]
            public bool? IsExternalModificationAllowed { get; init; }
        }

        /// <summary>
        /// Converts an [unmanaged access code](https://docs.seam.co/low-level-apis/smart-locks/access-codes/migrating-existing-access-codes) to an [access code managed through Seam](https://docs.seam.co/low-level-apis/smart-locks/access-codes).
        ///
        /// An unmanaged access code has a limited set of operations that you can perform on it. Once you convert an unmanaged access code to a managed access code, the full set of access code operations and lifecycle events becomes available for it.
        ///
        /// Note that not all device providers support converting an unmanaged access code to a managed access code.
        /// </summary>
        public async Task ConvertToManagedAsync(
            ConvertToManagedRequest request,
            CancellationToken cancellationToken = default
        )
        {
            await _transport
                .SendAsync(
                    HttpMethod.Patch,
                    "/access_codes/unmanaged/convert_to_managed",
                    request,
                    cancellationToken
                )
                .ConfigureAwait(false);
        }

        /// <summary>
        /// Request parameters for Delete an Unmanaged Access Code.
        /// </summary>
        public sealed record DeleteRequest
        {
            /// <summary>
            /// ID of the unmanaged access code that you want to delete.
            /// </summary>
            [JsonPropertyName("access_code_id")]
            public required string AccessCodeId { get; init; }
        }

        /// <summary>
        /// Deletes an [unmanaged access code](https://docs.seam.co/low-level-apis/smart-locks/access-codes/migrating-existing-access-codes).
        /// </summary>
        public async Task DeleteAsync(
            DeleteRequest request,
            CancellationToken cancellationToken = default
        )
        {
            await _transport
                .SendAsync(
                    HttpMethod.Delete,
                    "/access_codes/unmanaged/delete",
                    request,
                    cancellationToken
                )
                .ConfigureAwait(false);
        }

        /// <summary>
        /// Request parameters for Get an Unmanaged Access Code.
        /// </summary>
        public sealed record GetRequest
        {
            /// <summary>
            /// ID of the unmanaged access code that you want to get. You must specify either `access_code_id` or both `device_id` and `code`.
            /// </summary>
            [JsonPropertyName("access_code_id")]
            public string? AccessCodeId { get; init; }

            /// <summary>
            /// Code of the unmanaged access code that you want to get. You must specify either `access_code_id` or both `device_id` and `code`.
            /// </summary>
            [JsonPropertyName("code")]
            public string? Code { get; init; }

            /// <summary>
            /// ID of the device containing the unmanaged access code that you want to get. You must specify either `access_code_id` or both `device_id` and `code`.
            /// </summary>
            [JsonPropertyName("device_id")]
            public string? DeviceId { get; init; }

            internal void Validate()
            {
                if (AccessCodeId == null && Code == null && DeviceId == null)
                {
                    throw new ArgumentException(
                        "At least one parameter is required for /access_codes/unmanaged/get"
                    );
                }
            }
        }

        public sealed record GetResponse
        {
            /// <summary>
            /// OK
            /// </summary>
            [JsonPropertyName("access_code")]
            public UnmanagedAccessCode? AccessCode { get; init; }
        }

        /// <summary>
        /// Returns a specified [unmanaged access code](https://docs.seam.co/low-level-apis/smart-locks/access-codes/migrating-existing-access-codes).
        ///
        /// You must specify either `access_code_id` or both `device_id` and `code`.
        /// </summary>
        public async Task<UnmanagedAccessCode> GetAsync(
            GetRequest request,
            CancellationToken cancellationToken = default
        )
        {
            request.Validate();
            var response = await _transport
                .SendAsync<GetResponse>(
                    HttpMethod.Get,
                    "/access_codes/unmanaged/get",
                    request,
                    cancellationToken
                )
                .ConfigureAwait(false);
            return response.AccessCode
                ?? throw new HttpRequestException(
                    "Seam returned no access_code for /access_codes/unmanaged/get"
                );
        }

        /// <summary>
        /// Request parameters for List Unmanaged Access Codes.
        /// </summary>
        public sealed record ListRequest
        {
            /// <summary>
            /// ID of the device for which you want to list unmanaged access codes.
            /// </summary>
            [JsonPropertyName("device_id")]
            public required string DeviceId { get; init; }

            /// <summary>
            /// Numerical limit on the number of unmanaged access codes to return.
            /// </summary>
            [JsonPropertyName("limit")]
            public float? Limit { get; init; }

            /// <summary>
            /// Identifies the specific page of results to return, obtained from the previous page&apos;s `next_page_cursor`.
            /// </summary>
            [JsonPropertyName("page_cursor")]
            public Optional<string> PageCursor { get; init; }

            /// <summary>
            /// String for which to search. Filters returned access codes to include all records that satisfy a partial match using `name`, `code` or `access_code_id`.
            /// </summary>
            [JsonPropertyName("search")]
            public string? Search { get; init; }

            /// <summary>
            /// Your user ID for the user by which to filter unmanaged access codes.
            /// </summary>
            [JsonPropertyName("user_identifier_key")]
            public string? UserIdentifierKey { get; init; }
        }

        public sealed record ListResponse
        {
            /// <summary>
            /// OK
            /// </summary>
            [JsonPropertyName("access_codes")]
            public List<UnmanagedAccessCode>? AccessCodes { get; init; }

            /// <summary>
            /// The pagination metadata for the page of results.
            /// </summary>
            [JsonPropertyName("pagination")]
            public Pagination? Pagination { get; init; }
        }

        /// <summary>
        /// Returns a list of all [unmanaged access codes](https://docs.seam.co/low-level-apis/smart-locks/access-codes/migrating-existing-access-codes).
        /// </summary>
        public async Task<List<UnmanagedAccessCode>> ListAsync(
            ListRequest request,
            CancellationToken cancellationToken = default
        )
        {
            var response = await _transport
                .SendAsync<ListResponse>(
                    HttpMethod.Get,
                    "/access_codes/unmanaged/list",
                    request,
                    cancellationToken
                )
                .ConfigureAwait(false);
            return response.AccessCodes
                ?? throw new HttpRequestException(
                    "Seam returned no access_codes for /access_codes/unmanaged/list"
                );
        }

        /// <summary>Fetches one page of /access_codes/unmanaged/list with its pagination metadata.</summary>
        public async Task<SeamPage<UnmanagedAccessCode>> ListPageAsync(
            ListRequest request,
            CancellationToken cancellationToken = default
        )
        {
            var response = await _transport
                .SendAsync<ListResponse>(
                    HttpMethod.Get,
                    "/access_codes/unmanaged/list",
                    request,
                    cancellationToken
                )
                .ConfigureAwait(false);
            var items =
                response.AccessCodes
                ?? throw new HttpRequestException(
                    "Seam returned no access_codes for /access_codes/unmanaged/list"
                );
            var pagination =
                response.Pagination
                ?? throw new HttpRequestException(
                    "Seam returned no pagination for /access_codes/unmanaged/list"
                );
            return new SeamPage<UnmanagedAccessCode>(items, pagination);
        }

        /// <summary>Creates a paginator over /access_codes/unmanaged/list.</summary>
        public SeamPaginator<UnmanagedAccessCode> ListPager(ListRequest request)
        {
            return new SeamPaginator<UnmanagedAccessCode>(
                (pageCursor, cancellationToken) =>
                    ListPageAsync(
                        pageCursor == null ? request : request with { PageCursor = pageCursor },
                        cancellationToken
                    )
            );
        }

        /// <summary>
        /// Request parameters for Update an Unmanaged Access Code.
        /// </summary>
        public sealed record UpdateRequest
        {
            /// <summary>
            /// ID of the unmanaged access code that you want to update.
            /// </summary>
            [JsonPropertyName("access_code_id")]
            public required string AccessCodeId { get; init; }

            /// <summary>
            /// Indicates whether [external modification](https://docs.seam.co/low-level-apis/smart-locks/access-codes#external-modification) of the code is allowed.
            /// </summary>
            [JsonPropertyName("allow_external_modification")]
            public bool? AllowExternalModification { get; init; }

            /// <summary>
            /// Indicates whether to force the unmanaged access code update.
            /// </summary>
            [JsonPropertyName("force")]
            public bool? Force { get; init; }

            /// <summary>
            /// Indicates whether [external modification](https://docs.seam.co/low-level-apis/smart-locks/access-codes#external-modification) of the code is allowed.
            /// </summary>
            [JsonPropertyName("is_external_modification_allowed")]
            public bool? IsExternalModificationAllowed { get; init; }

            [JsonPropertyName("is_managed")]
            public required bool IsManaged { get; init; }
        }

        /// <summary>
        /// Updates a specified [unmanaged access code](https://docs.seam.co/low-level-apis/smart-locks/access-codes/migrating-existing-access-codes).
        /// </summary>
        public async Task UpdateAsync(
            UpdateRequest request,
            CancellationToken cancellationToken = default
        )
        {
            await _transport
                .SendAsync(
                    HttpMethod.Patch,
                    "/access_codes/unmanaged/update",
                    request,
                    cancellationToken
                )
                .ConfigureAwait(false);
        }
    }
}
