// <auto-generated>
//   Generated by codegen/smith.ts from @seamapi/types. Do not edit.
// </auto-generated>
#nullable enable
#pragma warning disable CS0618 // The generated code references its own deprecated members.
using System.Runtime.Serialization;
using System.Text.Json;
using System.Text.Json.Serialization;
using Seam.Http;
using Seam.Models;

namespace Seam.Routes
{
    public sealed class AccessGrants
    {
        private readonly SeamHttpTransport _transport;
        private readonly ActionAttemptWait _waitForActionAttemptDefault;

        internal AccessGrants(
            SeamHttpTransport transport,
            ActionAttemptWait waitForActionAttemptDefault
        )
        {
            _transport = transport;
            _waitForActionAttemptDefault = waitForActionAttemptDefault;
            Unmanaged = new AccessGrantsUnmanaged(transport, waitForActionAttemptDefault);
        }

        public AccessGrantsUnmanaged Unmanaged { get; }

        /// <summary>
        /// Request parameters for Create an Access Grant.
        /// </summary>
        public sealed record CreateRequest
        {
            /// <summary>
            /// ID of user identity for whom access is being granted.
            /// </summary>
            [JsonPropertyName("user_identity_id")]
            public string? UserIdentityId { get; init; }

            /// <summary>
            /// When used, creates a new user identity with the given details, and grants them access.
            /// </summary>
            [JsonPropertyName("user_identity")]
            public CreateRequestUserIdentity? UserIdentity { get; init; }

            /// <summary>
            /// Unique key for the access grant within the workspace.
            /// </summary>
            [JsonPropertyName("access_grant_key")]
            public string? AccessGrantKey { get; init; }

            /// <summary>
            /// Set of IDs of the [entrances](https://docs.seam.co/api/acs/systems/list) to which access is being granted.
            /// </summary>
            [JsonPropertyName("acs_entrance_ids")]
            public List<string>? AcsEntranceIds { get; init; }

            /// <summary>
            /// ID of the customization profile to apply to the Access Grant and its access methods.
            /// </summary>
            [JsonPropertyName("customization_profile_id")]
            public string? CustomizationProfileId { get; init; }

            /// <summary>
            /// Set of IDs of the [devices](https://docs.seam.co/api/devices/list) to which access is being granted.
            /// </summary>
            [JsonPropertyName("device_ids")]
            public List<string>? DeviceIds { get; init; }

            /// <summary>
            /// Date and time at which the validity of the new grant ends, in [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html) format. Must be a time in the future and after `starts_at`.
            /// </summary>
            [JsonPropertyName("ends_at")]
            public Optional<string> EndsAt { get; init; }

            [Obsolete("Create a space first, then reference it using `space_ids`.")]
            [JsonPropertyName("location")]
            public CreateRequestLocation? Location { get; init; }

            [Obsolete("Use `space_ids`.")]
            [JsonPropertyName("location_ids")]
            public List<string>? LocationIds { get; init; }

            /// <summary>
            /// Name for the access grant.
            /// </summary>
            [JsonPropertyName("name")]
            public Optional<string> Name { get; init; }

            [JsonPropertyName("requested_access_methods")]
            public required List<CreateRequestRequestedAccessMethods> RequestedAccessMethods { get; init; }

            /// <summary>
            /// Reservation key for the access grant.
            /// </summary>
            [JsonPropertyName("reservation_key")]
            public string? ReservationKey { get; init; }

            /// <summary>
            /// Set of IDs of existing spaces to which access is being granted.
            /// </summary>
            [JsonPropertyName("space_ids")]
            public List<string>? SpaceIds { get; init; }

            /// <summary>
            /// Set of keys of existing spaces to which access is being granted.
            /// </summary>
            [JsonPropertyName("space_keys")]
            public List<string>? SpaceKeys { get; init; }

            /// <summary>
            /// Date and time at which the validity of the new grant starts, in [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html) format.
            /// </summary>
            [JsonPropertyName("starts_at")]
            public string? StartsAt { get; init; }
        }

        public sealed record CreateRequestUserIdentity
        {
            /// <summary>
            /// Unique email address for the user identity.
            /// </summary>
            [JsonPropertyName("email_address")]
            public Optional<string> EmailAddress { get; init; }

            /// <summary>
            /// Full name of the user associated with the user identity.
            /// </summary>
            [JsonPropertyName("full_name")]
            public Optional<string> FullName { get; init; }

            /// <summary>
            /// Unique phone number for the user identity in [E.164 format](https://www.itu.int/rec/T-REC-E.164/en) (for example, +15555550100).
            /// </summary>
            [JsonPropertyName("phone_number")]
            public Optional<string> PhoneNumber { get; init; }

            /// <summary>
            /// Unique key for the user identity.
            /// </summary>
            [JsonPropertyName("user_identity_key")]
            public Optional<string> UserIdentityKey { get; init; }
        }

        public sealed record CreateRequestLocation
        {
            [Obsolete("Use `acs_entrance_ids` at the top level.")]
            [JsonPropertyName("acs_entrance_ids")]
            public List<string>? AcsEntranceIds { get; init; }

            [Obsolete("Use `device_ids` at the top level.")]
            [JsonPropertyName("device_ids")]
            public List<string>? DeviceIds { get; init; }

            /// <summary>
            /// Name of the location.
            /// </summary>
            [JsonPropertyName("name")]
            public string? Name { get; init; }
        }

        public sealed record CreateRequestRequestedAccessMethods
        {
            /// <summary>
            /// Access method mode. Supported values: `code`, `card`, `mobile_key`, `cloud_key`.
            /// </summary>
            [JsonConverter(typeof(SeamStringEnumConverter))]
            public enum ModeEnum
            {
                [EnumMember(Value = "unrecognized")]
                Unrecognized = 0,

                [EnumMember(Value = "code")]
                Code = 1,

                [EnumMember(Value = "card")]
                Card = 2,

                [EnumMember(Value = "mobile_key")]
                MobileKey = 3,

                [EnumMember(Value = "cloud_key")]
                CloudKey = 4,
            }

            /// <summary>
            /// Specific PIN code to use for this access method. Only applicable when mode is &apos;code&apos;.
            /// </summary>
            [JsonPropertyName("code")]
            public string? Code { get; init; }

            /// <summary>
            /// Maximum number of times the instant key can be used. Only applicable when mode is &apos;mobile_key&apos;. Defaults to 1 if not specified.
            /// </summary>
            [JsonPropertyName("instant_key_max_use_count")]
            public int? InstantKeyMaxUseCount { get; init; }

            /// <summary>
            /// Access method mode. Supported values: `code`, `card`, `mobile_key`, `cloud_key`.
            /// </summary>
            [JsonPropertyName("mode")]
            public CreateRequestRequestedAccessMethods.ModeEnum? Mode { get; init; }
        }

        public sealed record CreateResponse
        {
            /// <summary>
            /// OK
            /// </summary>
            [JsonPropertyName("access_grant")]
            public AccessGrant? AccessGrant { get; init; }
        }

        /// <summary>
        /// Creates a new [Access Grant](https://docs.seam.co/use-cases/granting-access/access-grants). Access Grants are the default and recommended way to grant a user access to any physical space, irrespective of the locking hardware. They work with both standalone smart locks (using `device_ids`) and access control systems (using `acs_entrance_ids` or `space_ids`), and can issue PIN codes, key cards, and mobile keys through a single request.
        /// </summary>
        public async Task<AccessGrant> CreateAsync(
            CreateRequest request,
            CancellationToken cancellationToken = default
        )
        {
            var response = await _transport
                .SendAsync<CreateResponse>(
                    HttpMethod.Post,
                    "/access_grants/create",
                    request,
                    cancellationToken
                )
                .ConfigureAwait(false);
            return response.AccessGrant
                ?? throw new HttpRequestException(
                    "Seam returned no access_grant for /access_grants/create"
                );
        }

        /// <summary>
        /// Request parameters for Delete an Access Grant.
        /// </summary>
        public sealed record DeleteRequest
        {
            /// <summary>
            /// ID of Access Grant to delete.
            /// </summary>
            [JsonPropertyName("access_grant_id")]
            public required string AccessGrantId { get; init; }
        }

        /// <summary>
        /// Delete an Access Grant.
        /// </summary>
        public async Task DeleteAsync(
            DeleteRequest request,
            CancellationToken cancellationToken = default
        )
        {
            await _transport
                .SendAsync(HttpMethod.Delete, "/access_grants/delete", request, cancellationToken)
                .ConfigureAwait(false);
        }

        /// <summary>
        /// Request parameters for Get an Access Grant.
        /// </summary>
        public sealed record GetRequest
        {
            /// <summary>
            /// ID of Access Grant to get.
            /// </summary>
            [JsonPropertyName("access_grant_id")]
            public string? AccessGrantId { get; init; }

            /// <summary>
            /// Unique key of Access Grant to get.
            /// </summary>
            [JsonPropertyName("access_grant_key")]
            public string? AccessGrantKey { get; init; }

            internal void Validate()
            {
                if (AccessGrantId == null && AccessGrantKey == null)
                {
                    throw new ArgumentException(
                        "At least one parameter is required for /access_grants/get"
                    );
                }
            }
        }

        public sealed record GetResponse
        {
            /// <summary>
            /// OK
            /// </summary>
            [JsonPropertyName("access_grant")]
            public AccessGrant? AccessGrant { get; init; }
        }

        /// <summary>
        /// Get an Access Grant.
        /// </summary>
        public async Task<AccessGrant> GetAsync(
            GetRequest request,
            CancellationToken cancellationToken = default
        )
        {
            request.Validate();
            var response = await _transport
                .SendAsync<GetResponse>(
                    HttpMethod.Get,
                    "/access_grants/get",
                    request,
                    cancellationToken
                )
                .ConfigureAwait(false);
            return response.AccessGrant
                ?? throw new HttpRequestException(
                    "Seam returned no access_grant for /access_grants/get"
                );
        }

        /// <summary>
        /// Request parameters for Get related Access Grant resources.
        /// </summary>
        public sealed record GetRelatedRequest
        {
            [JsonConverter(typeof(SeamStringEnumConverter))]
            public enum ExcludeEnum
            {
                [EnumMember(Value = "unrecognized")]
                Unrecognized = 0,

                [EnumMember(Value = "spaces")]
                Spaces = 1,

                [EnumMember(Value = "devices")]
                Devices = 2,

                [EnumMember(Value = "acs_entrances")]
                AcsEntrances = 3,

                [EnumMember(Value = "connected_accounts")]
                ConnectedAccounts = 4,

                [EnumMember(Value = "acs_systems")]
                AcsSystems = 5,

                [EnumMember(Value = "user_identities")]
                UserIdentities = 6,

                [EnumMember(Value = "acs_access_groups")]
                AcsAccessGroups = 7,

                [EnumMember(Value = "access_methods")]
                AccessMethods = 8,
            }

            [JsonConverter(typeof(SeamStringEnumConverter))]
            public enum IncludeEnum
            {
                [EnumMember(Value = "unrecognized")]
                Unrecognized = 0,

                [EnumMember(Value = "spaces")]
                Spaces = 1,

                [EnumMember(Value = "devices")]
                Devices = 2,

                [EnumMember(Value = "acs_entrances")]
                AcsEntrances = 3,

                [EnumMember(Value = "connected_accounts")]
                ConnectedAccounts = 4,

                [EnumMember(Value = "acs_systems")]
                AcsSystems = 5,

                [EnumMember(Value = "user_identities")]
                UserIdentities = 6,

                [EnumMember(Value = "acs_access_groups")]
                AcsAccessGroups = 7,

                [EnumMember(Value = "access_methods")]
                AccessMethods = 8,
            }

            /// <summary>
            /// IDs of the access grants that you want to get along with their related resources.
            /// </summary>
            [JsonPropertyName("access_grant_ids")]
            public List<string>? AccessGrantIds { get; init; }

            /// <summary>
            /// Keys of the access grants that you want to get along with their related resources.
            /// </summary>
            [JsonPropertyName("access_grant_keys")]
            public List<string>? AccessGrantKeys { get; init; }

            [JsonPropertyName("exclude")]
            public List<GetRelatedRequest.ExcludeEnum>? Exclude { get; init; }

            [JsonPropertyName("include")]
            public List<GetRelatedRequest.IncludeEnum>? Include { get; init; }

            internal void Validate()
            {
                if (
                    AccessGrantIds == null
                    && AccessGrantKeys == null
                    && Exclude == null
                    && Include == null
                )
                {
                    throw new ArgumentException(
                        "At least one parameter is required for /access_grants/get_related"
                    );
                }
            }
        }

        public sealed record GetRelatedResponse
        {
            /// <summary>
            /// OK
            /// </summary>
            [JsonPropertyName("batch")]
            public Batch? Batch { get; init; }
        }

        /// <summary>
        /// Gets all related resources for one or more Access Grants.
        /// </summary>
        public async Task<Batch> GetRelatedAsync(
            GetRelatedRequest request,
            CancellationToken cancellationToken = default
        )
        {
            request.Validate();
            var response = await _transport
                .SendAsync<GetRelatedResponse>(
                    HttpMethod.Get,
                    "/access_grants/get_related",
                    request,
                    cancellationToken
                )
                .ConfigureAwait(false);
            return response.Batch
                ?? throw new HttpRequestException(
                    "Seam returned no batch for /access_grants/get_related"
                );
        }

        /// <summary>
        /// Request parameters for List Access Grants.
        /// </summary>
        public sealed record ListRequest
        {
            /// <summary>
            /// ID of the access code by which you want to filter the list of Access Grants.
            /// </summary>
            [JsonPropertyName("access_code_id")]
            public string? AccessCodeId { get; init; }

            /// <summary>
            /// IDs of the access grants to retrieve.
            /// </summary>
            [JsonPropertyName("access_grant_ids")]
            public List<string>? AccessGrantIds { get; init; }

            /// <summary>
            /// Filter Access Grants by access_grant_key. Use null to filter for Access Grants without an access_grant_key.
            /// </summary>
            [JsonPropertyName("access_grant_key")]
            public Optional<string> AccessGrantKey { get; init; }

            /// <summary>
            /// ID of the entrance by which you want to filter the list of Access Grants.
            /// </summary>
            [JsonPropertyName("acs_entrance_id")]
            public string? AcsEntranceId { get; init; }

            /// <summary>
            /// ID of the access system by which you want to filter the list of Access Grants.
            /// </summary>
            [JsonPropertyName("acs_system_id")]
            public string? AcsSystemId { get; init; }

            /// <summary>
            /// Customer key for which you want to list access grants.
            /// </summary>
            [JsonPropertyName("customer_key")]
            public string? CustomerKey { get; init; }

            /// <summary>
            /// ID of the device by which you want to filter the list of Access Grants.
            /// </summary>
            [JsonPropertyName("device_id")]
            public string? DeviceId { get; init; }

            /// <summary>
            /// Numerical limit on the number of access grants to return.
            /// </summary>
            [JsonPropertyName("limit")]
            public float? Limit { get; init; }

            [Obsolete("Use `space_id`.")]
            [JsonPropertyName("location_id")]
            public string? LocationId { get; init; }

            /// <summary>
            /// Identifies the specific page of results to return, obtained from the previous page&apos;s `next_page_cursor`.
            /// </summary>
            [JsonPropertyName("page_cursor")]
            public Optional<string> PageCursor { get; init; }

            /// <summary>
            /// Filter Access Grants by reservation_key.
            /// </summary>
            [JsonPropertyName("reservation_key")]
            public string? ReservationKey { get; init; }

            /// <summary>
            /// ID of the space by which you want to filter the list of Access Grants.
            /// </summary>
            [JsonPropertyName("space_id")]
            public string? SpaceId { get; init; }

            /// <summary>
            /// ID of user identity by which you want to filter the list of Access Grants.
            /// </summary>
            [JsonPropertyName("user_identity_id")]
            public string? UserIdentityId { get; init; }
        }

        public sealed record ListResponse
        {
            /// <summary>
            /// OK
            /// </summary>
            [JsonPropertyName("access_grants")]
            public List<AccessGrant>? AccessGrants { get; init; }

            /// <summary>
            /// The pagination metadata for the page of results.
            /// </summary>
            [JsonPropertyName("pagination")]
            public Pagination? Pagination { get; init; }
        }

        /// <summary>
        /// Gets an Access Grant.
        /// </summary>
        public async Task<List<AccessGrant>> ListAsync(
            ListRequest? request = null,
            CancellationToken cancellationToken = default
        )
        {
            var response = await _transport
                .SendAsync<ListResponse>(
                    HttpMethod.Get,
                    "/access_grants/list",
                    request,
                    cancellationToken
                )
                .ConfigureAwait(false);
            return response.AccessGrants
                ?? throw new HttpRequestException(
                    "Seam returned no access_grants for /access_grants/list"
                );
        }

        /// <summary>Fetches one page of /access_grants/list with its pagination metadata.</summary>
        public async Task<SeamPage<AccessGrant>> ListPageAsync(
            ListRequest? request = null,
            CancellationToken cancellationToken = default
        )
        {
            var response = await _transport
                .SendAsync<ListResponse>(
                    HttpMethod.Get,
                    "/access_grants/list",
                    request,
                    cancellationToken
                )
                .ConfigureAwait(false);
            var items =
                response.AccessGrants
                ?? throw new HttpRequestException(
                    "Seam returned no access_grants for /access_grants/list"
                );
            var pagination =
                response.Pagination
                ?? throw new HttpRequestException(
                    "Seam returned no pagination for /access_grants/list"
                );
            return new SeamPage<AccessGrant>(items, pagination);
        }

        /// <summary>Creates a paginator over /access_grants/list.</summary>
        public SeamPaginator<AccessGrant> ListPager(ListRequest? request = null)
        {
            return new SeamPaginator<AccessGrant>(
                (pageCursor, cancellationToken) =>
                    ListPageAsync(
                        pageCursor == null
                            ? request
                            : (request ?? new ListRequest()) with
                            {
                                PageCursor = pageCursor,
                            },
                        cancellationToken
                    )
            );
        }

        /// <summary>
        /// Request parameters for Add Requested Access Methods to Access Grant.
        /// </summary>
        public sealed record RequestAccessMethodsRequest
        {
            /// <summary>
            /// ID of the Access Grant to add access methods to.
            /// </summary>
            [JsonPropertyName("access_grant_id")]
            public required string AccessGrantId { get; init; }

            /// <summary>
            /// Array of requested access methods to add to the access grant.
            /// </summary>
            [JsonPropertyName("requested_access_methods")]
            public required List<RequestAccessMethodsRequestRequestedAccessMethods> RequestedAccessMethods { get; init; }
        }

        public sealed record RequestAccessMethodsRequestRequestedAccessMethods
        {
            /// <summary>
            /// Access method mode. Supported values: `code`, `card`, `mobile_key`, `cloud_key`.
            /// </summary>
            [JsonConverter(typeof(SeamStringEnumConverter))]
            public enum ModeEnum
            {
                [EnumMember(Value = "unrecognized")]
                Unrecognized = 0,

                [EnumMember(Value = "code")]
                Code = 1,

                [EnumMember(Value = "card")]
                Card = 2,

                [EnumMember(Value = "mobile_key")]
                MobileKey = 3,

                [EnumMember(Value = "cloud_key")]
                CloudKey = 4,
            }

            /// <summary>
            /// Specific PIN code to use for this access method. Only applicable when mode is &apos;code&apos;.
            /// </summary>
            [JsonPropertyName("code")]
            public string? Code { get; init; }

            /// <summary>
            /// Maximum number of times the instant key can be used. Only applicable when mode is &apos;mobile_key&apos;. Defaults to 1 if not specified.
            /// </summary>
            [JsonPropertyName("instant_key_max_use_count")]
            public int? InstantKeyMaxUseCount { get; init; }

            /// <summary>
            /// Access method mode. Supported values: `code`, `card`, `mobile_key`, `cloud_key`.
            /// </summary>
            [JsonPropertyName("mode")]
            public RequestAccessMethodsRequestRequestedAccessMethods.ModeEnum? Mode { get; init; }
        }

        public sealed record RequestAccessMethodsResponse
        {
            /// <summary>
            /// OK
            /// </summary>
            [JsonPropertyName("access_grant")]
            public AccessGrant? AccessGrant { get; init; }
        }

        /// <summary>
        /// Adds additional requested access methods to an existing Access Grant.
        /// </summary>
        public async Task<AccessGrant> RequestAccessMethodsAsync(
            RequestAccessMethodsRequest request,
            CancellationToken cancellationToken = default
        )
        {
            var response = await _transport
                .SendAsync<RequestAccessMethodsResponse>(
                    HttpMethod.Post,
                    "/access_grants/request_access_methods",
                    request,
                    cancellationToken
                )
                .ConfigureAwait(false);
            return response.AccessGrant
                ?? throw new HttpRequestException(
                    "Seam returned no access_grant for /access_grants/request_access_methods"
                );
        }

        /// <summary>
        /// Request parameters for Update an Access Grant.
        /// </summary>
        public sealed record UpdateRequest
        {
            /// <summary>
            /// ID of the Access Grant to update. Provide either `access_grant_id` or `access_grant_key`.
            /// </summary>
            [JsonPropertyName("access_grant_id")]
            public string? AccessGrantId { get; init; }

            /// <summary>
            /// Key of the Access Grant to update. Provide either `access_grant_id` or `access_grant_key`.
            /// </summary>
            [JsonPropertyName("access_grant_key")]
            public string? AccessGrantKey { get; init; }

            /// <summary>
            /// Date and time at which the validity of the grant ends, in [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html) format. Must be a time in the future and after `starts_at`.
            /// </summary>
            [JsonPropertyName("ends_at")]
            public Optional<string> EndsAt { get; init; }

            /// <summary>
            /// Display name for the access grant.
            /// </summary>
            [JsonPropertyName("name")]
            public Optional<string> Name { get; init; }

            /// <summary>
            /// Date and time at which the validity of the grant starts, in [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html) format.
            /// </summary>
            [JsonPropertyName("starts_at")]
            public string? StartsAt { get; init; }

            internal void Validate()
            {
                if (
                    AccessGrantId == null
                    && AccessGrantKey == null
                    && !EndsAt.IsSet
                    && !Name.IsSet
                    && StartsAt == null
                )
                {
                    throw new ArgumentException(
                        "At least one parameter is required for /access_grants/update"
                    );
                }
            }
        }

        /// <summary>
        /// Updates an existing Access Grant&apos;s time window.
        /// </summary>
        public async Task UpdateAsync(
            UpdateRequest request,
            CancellationToken cancellationToken = default
        )
        {
            request.Validate();
            await _transport
                .SendAsync(HttpMethod.Patch, "/access_grants/update", request, cancellationToken)
                .ConfigureAwait(false);
        }
    }
}
