// <auto-generated>
//   Generated by codegen/smith.ts from @seamapi/types. Do not edit.
// </auto-generated>
#nullable enable
#pragma warning disable CS0618 // The generated code references its own deprecated members.
using System.Runtime.Serialization;
using System.Text.Json;
using System.Text.Json.Serialization;
using Seam.Http;
using Seam.Models;

namespace Seam.Routes
{
    public sealed class AccessGrantsUnmanaged
    {
        private readonly SeamHttpTransport _transport;
        private readonly ActionAttemptWait _waitForActionAttemptDefault;

        internal AccessGrantsUnmanaged(
            SeamHttpTransport transport,
            ActionAttemptWait waitForActionAttemptDefault
        )
        {
            _transport = transport;
            _waitForActionAttemptDefault = waitForActionAttemptDefault;
        }

        /// <summary>
        /// Request parameters for Get an Unmanaged Access Grant.
        /// </summary>
        public sealed record GetRequest
        {
            /// <summary>
            /// ID of unmanaged Access Grant to get.
            /// </summary>
            [JsonPropertyName("access_grant_id")]
            public required string AccessGrantId { get; init; }
        }

        public sealed record GetResponse
        {
            /// <summary>
            /// OK
            /// </summary>
            [JsonPropertyName("access_grant")]
            public UnmanagedAccessGrant? AccessGrant { get; init; }
        }

        /// <summary>
        /// Get an unmanaged Access Grant (where is_managed = false).
        /// </summary>
        public async Task<UnmanagedAccessGrant> GetAsync(
            GetRequest request,
            CancellationToken cancellationToken = default
        )
        {
            var response = await _transport
                .SendAsync<GetResponse>(
                    HttpMethod.Get,
                    "/access_grants/unmanaged/get",
                    request,
                    cancellationToken
                )
                .ConfigureAwait(false);
            return response.AccessGrant
                ?? throw new HttpRequestException(
                    "Seam returned no access_grant for /access_grants/unmanaged/get"
                );
        }

        /// <summary>
        /// Request parameters for List Unmanaged Access Grants.
        /// </summary>
        public sealed record ListRequest
        {
            /// <summary>
            /// ID of the entrance by which you want to filter the list of unmanaged Access Grants.
            /// </summary>
            [JsonPropertyName("acs_entrance_id")]
            public string? AcsEntranceId { get; init; }

            /// <summary>
            /// ID of the access system by which you want to filter the list of unmanaged Access Grants.
            /// </summary>
            [JsonPropertyName("acs_system_id")]
            public string? AcsSystemId { get; init; }

            /// <summary>
            /// Numerical limit on the number of unmanaged access grants to return.
            /// </summary>
            [JsonPropertyName("limit")]
            public float? Limit { get; init; }

            /// <summary>
            /// Identifies the specific page of results to return, obtained from the previous page&apos;s `next_page_cursor`.
            /// </summary>
            [JsonPropertyName("page_cursor")]
            public Optional<string> PageCursor { get; init; }

            /// <summary>
            /// Filter unmanaged Access Grants by reservation_key.
            /// </summary>
            [JsonPropertyName("reservation_key")]
            public string? ReservationKey { get; init; }

            /// <summary>
            /// ID of user identity by which you want to filter the list of unmanaged Access Grants.
            /// </summary>
            [JsonPropertyName("user_identity_id")]
            public string? UserIdentityId { get; init; }
        }

        public sealed record ListResponse
        {
            /// <summary>
            /// OK
            /// </summary>
            [JsonPropertyName("access_grants")]
            public List<UnmanagedAccessGrant>? AccessGrants { get; init; }

            /// <summary>
            /// The pagination metadata for the page of results.
            /// </summary>
            [JsonPropertyName("pagination")]
            public Pagination? Pagination { get; init; }
        }

        /// <summary>
        /// Gets unmanaged Access Grants (where is_managed = false).
        /// </summary>
        public async Task<List<UnmanagedAccessGrant>> ListAsync(
            ListRequest? request = null,
            CancellationToken cancellationToken = default
        )
        {
            var response = await _transport
                .SendAsync<ListResponse>(
                    HttpMethod.Get,
                    "/access_grants/unmanaged/list",
                    request,
                    cancellationToken
                )
                .ConfigureAwait(false);
            return response.AccessGrants
                ?? throw new HttpRequestException(
                    "Seam returned no access_grants for /access_grants/unmanaged/list"
                );
        }

        /// <summary>Fetches one page of /access_grants/unmanaged/list with its pagination metadata.</summary>
        public async Task<SeamPage<UnmanagedAccessGrant>> ListPageAsync(
            ListRequest? request = null,
            CancellationToken cancellationToken = default
        )
        {
            var response = await _transport
                .SendAsync<ListResponse>(
                    HttpMethod.Get,
                    "/access_grants/unmanaged/list",
                    request,
                    cancellationToken
                )
                .ConfigureAwait(false);
            var items =
                response.AccessGrants
                ?? throw new HttpRequestException(
                    "Seam returned no access_grants for /access_grants/unmanaged/list"
                );
            var pagination =
                response.Pagination
                ?? throw new HttpRequestException(
                    "Seam returned no pagination for /access_grants/unmanaged/list"
                );
            return new SeamPage<UnmanagedAccessGrant>(items, pagination);
        }

        /// <summary>Creates a paginator over /access_grants/unmanaged/list.</summary>
        public SeamPaginator<UnmanagedAccessGrant> ListPager(ListRequest? request = null)
        {
            return new SeamPaginator<UnmanagedAccessGrant>(
                (pageCursor, cancellationToken) =>
                    ListPageAsync(
                        pageCursor == null
                            ? request
                            : (request ?? new ListRequest()) with
                            {
                                PageCursor = pageCursor,
                            },
                        cancellationToken
                    )
            );
        }

        /// <summary>
        /// Request parameters for Update an Unmanaged Access Grant.
        /// </summary>
        public sealed record UpdateRequest
        {
            /// <summary>
            /// ID of the unmanaged Access Grant to update.
            /// </summary>
            [JsonPropertyName("access_grant_id")]
            public required string AccessGrantId { get; init; }

            /// <summary>
            /// Unique key for the access grant. If not provided, the existing key will be preserved.
            /// </summary>
            [JsonPropertyName("access_grant_key")]
            public string? AccessGrantKey { get; init; }

            /// <summary>
            /// Must be set to true to convert the unmanaged access grant to managed.
            /// </summary>
            [JsonPropertyName("is_managed")]
            public required bool IsManaged { get; init; }
        }

        /// <summary>
        /// Updates an unmanaged Access Grant to make it managed.
        ///
        /// This endpoint can only be used to convert unmanaged access grants to managed ones by setting `is_managed` to `true`. It cannot be used to convert managed access grants back to unmanaged.
        ///
        /// When converting an unmanaged access grant to managed, all associated access methods will also be converted to managed.
        /// </summary>
        public async Task UpdateAsync(
            UpdateRequest request,
            CancellationToken cancellationToken = default
        )
        {
            await _transport
                .SendAsync(
                    HttpMethod.Patch,
                    "/access_grants/unmanaged/update",
                    request,
                    cancellationToken
                )
                .ConfigureAwait(false);
        }
    }
}
