// <auto-generated>
//   Generated by codegen/smith.ts from @seamapi/types. Do not edit.
// </auto-generated>
#nullable enable
#pragma warning disable CS0618 // The generated code references its own deprecated members.
using System.Runtime.Serialization;
using System.Text.Json;
using System.Text.Json.Serialization;
using Seam.Http;
using Seam.Models;

namespace Seam.Routes
{
    public sealed class AccessCodesSimulate
    {
        private readonly SeamHttpTransport _transport;
        private readonly ActionAttemptWait _waitForActionAttemptDefault;

        internal AccessCodesSimulate(
            SeamHttpTransport transport,
            ActionAttemptWait waitForActionAttemptDefault
        )
        {
            _transport = transport;
            _waitForActionAttemptDefault = waitForActionAttemptDefault;
        }

        /// <summary>
        /// Request parameters for Simulate Creating an Unmanaged Access Code.
        /// </summary>
        public sealed record CreateUnmanagedAccessCodeRequest
        {
            /// <summary>
            /// Code of the simulated unmanaged access code.
            /// </summary>
            [JsonPropertyName("code")]
            public required string Code { get; init; }

            /// <summary>
            /// ID of the device for which you want to simulate the creation of an unmanaged access code.
            /// </summary>
            [JsonPropertyName("device_id")]
            public required string DeviceId { get; init; }

            /// <summary>
            /// Name of the simulated unmanaged access code.
            /// </summary>
            [JsonPropertyName("name")]
            public required string Name { get; init; }
        }

        public sealed record CreateUnmanagedAccessCodeResponse
        {
            /// <summary>
            /// OK
            /// </summary>
            [JsonPropertyName("access_code")]
            public UnmanagedAccessCode? AccessCode { get; init; }
        }

        /// <summary>
        /// Simulates the creation of an [unmanaged access code](https://docs.seam.co/low-level-apis/smart-locks/access-codes/migrating-existing-access-codes) in a [sandbox workspace](https://docs.seam.co/core-concepts/workspaces#sandbox-workspaces).
        /// </summary>
        public async Task<UnmanagedAccessCode> CreateUnmanagedAccessCodeAsync(
            CreateUnmanagedAccessCodeRequest request,
            CancellationToken cancellationToken = default
        )
        {
            var response = await _transport
                .SendAsync<CreateUnmanagedAccessCodeResponse>(
                    HttpMethod.Post,
                    "/access_codes/simulate/create_unmanaged_access_code",
                    request,
                    cancellationToken
                )
                .ConfigureAwait(false);
            return response.AccessCode
                ?? throw new HttpRequestException(
                    "Seam returned no access_code for /access_codes/simulate/create_unmanaged_access_code"
                );
        }
    }
}
