// <auto-generated>
//   Generated by codegen/smith.ts from @seamapi/types. Do not edit.
// </auto-generated>
#nullable enable
#pragma warning disable CS0618 // The generated code references its own deprecated members.
using System.Runtime.Serialization;
using System.Text.Json;
using System.Text.Json.Serialization;
using Seam.Http;
using Seam.Models;

namespace Seam.Routes
{
    public sealed class AcsEntrances
    {
        private readonly SeamHttpTransport _transport;
        private readonly ActionAttemptWait _waitForActionAttemptDefault;

        internal AcsEntrances(
            SeamHttpTransport transport,
            ActionAttemptWait waitForActionAttemptDefault
        )
        {
            _transport = transport;
            _waitForActionAttemptDefault = waitForActionAttemptDefault;
        }

        /// <summary>
        /// Request parameters for Get an Entrance.
        /// </summary>
        public sealed record GetRequest
        {
            /// <summary>
            /// ID of the entrance that you want to get.
            /// </summary>
            [JsonPropertyName("acs_entrance_id")]
            public required string AcsEntranceId { get; init; }
        }

        public sealed record GetResponse
        {
            /// <summary>
            /// OK
            /// </summary>
            [JsonPropertyName("acs_entrance")]
            public AcsEntrance? AcsEntrance { get; init; }
        }

        /// <summary>
        /// Returns a specified [access system entrance](https://docs.seam.co/low-level-apis/access-systems/retrieving-entrance-details).
        /// </summary>
        public async Task<AcsEntrance> GetAsync(
            GetRequest request,
            CancellationToken cancellationToken = default
        )
        {
            var response = await _transport
                .SendAsync<GetResponse>(
                    HttpMethod.Get,
                    "/acs/entrances/get",
                    request,
                    "acs_entrance",
                    cancellationToken
                )
                .ConfigureAwait(false);
            return response.Read(r => r.AcsEntrance);
        }

        /// <summary>
        /// Request parameters for Grant an ACS User Access to an Entrance.
        /// </summary>
        public sealed record GrantAccessRequest
        {
            /// <summary>
            /// ID of the entrance to which you want to grant an access system user access.
            /// </summary>
            [JsonPropertyName("acs_entrance_id")]
            public required string AcsEntranceId { get; init; }

            /// <summary>
            /// ID of the access system user to whom you want to grant access to an entrance. You can only provide one of acs_user_id or user_identity_id.
            /// </summary>
            [JsonPropertyName("acs_user_id")]
            public string? AcsUserId { get; init; }

            /// <summary>
            /// ID of the user identity to whom you want to grant access to an entrance. You can only provide one of acs_user_id or user_identity_id. If the ACS system contains an ACS user with the same `email_address` or `phone_number` as the user identity that you specify, they are linked, and the access group membership belongs to the ACS user. If the ACS system does not have a corresponding ACS user, one is created.
            /// </summary>
            [JsonPropertyName("user_identity_id")]
            public string? UserIdentityId { get; init; }
        }

        /// <summary>
        /// Grants a specified [access system user](https://docs.seam.co/low-level-apis/access-systems/user-management) access to a specified [access system entrance](https://docs.seam.co/low-level-apis/access-systems/retrieving-entrance-details).
        /// </summary>
        public async Task GrantAccessAsync(
            GrantAccessRequest request,
            CancellationToken cancellationToken = default
        )
        {
            await _transport
                .SendAsync(
                    HttpMethod.Post,
                    "/acs/entrances/grant_access",
                    request,
                    cancellationToken
                )
                .ConfigureAwait(false);
        }

        /// <summary>
        /// Request parameters for List Entrances.
        /// </summary>
        public sealed record ListRequest
        {
            /// <summary>
            /// ID of the access method for which you want to retrieve all entrances to which it grants access.
            /// </summary>
            [JsonPropertyName("access_method_id")]
            public string? AccessMethodId { get; init; }

            /// <summary>
            /// ID of the credential for which you want to retrieve all entrances.
            /// </summary>
            [JsonPropertyName("acs_credential_id")]
            public string? AcsCredentialId { get; init; }

            /// <summary>
            /// IDs of the entrances for which you want to retrieve all entrances.
            /// </summary>
            [JsonPropertyName("acs_entrance_ids")]
            public List<string>? AcsEntranceIds { get; init; }

            /// <summary>
            /// ID of the access system for which you want to retrieve all entrances.
            /// </summary>
            [JsonPropertyName("acs_system_id")]
            public string? AcsSystemId { get; init; }

            /// <summary>
            /// ID of the connected account for which you want to retrieve all entrances.
            /// </summary>
            [JsonPropertyName("connected_account_id")]
            public string? ConnectedAccountId { get; init; }

            /// <summary>
            /// Customer key for which you want to list entrances.
            /// </summary>
            [JsonPropertyName("customer_key")]
            public string? CustomerKey { get; init; }

            /// <summary>
            /// Maximum number of records to return per page.
            /// </summary>
            [JsonPropertyName("limit")]
            public int? Limit { get; init; }

            [Obsolete("Use `space_id`.")]
            [JsonPropertyName("location_id")]
            public Optional<string> LocationId { get; init; }

            /// <summary>
            /// Identifies the specific page of results to return, obtained from the previous page&apos;s `next_page_cursor`.
            /// </summary>
            [JsonPropertyName("page_cursor")]
            public Optional<string> PageCursor { get; init; }

            /// <summary>
            /// String for which to search. Filters returned entrances to include all records that satisfy a partial match using `display_name`.
            /// </summary>
            [JsonPropertyName("search")]
            public string? Search { get; init; }

            /// <summary>
            /// ID of the space for which you want to list entrances.
            /// </summary>
            [JsonPropertyName("space_id")]
            public string? SpaceId { get; init; }
        }

        public sealed record ListResponse
        {
            /// <summary>
            /// OK
            /// </summary>
            [JsonPropertyName("acs_entrances")]
            public List<AcsEntrance>? AcsEntrances { get; init; }

            /// <summary>
            /// The pagination metadata for the page of results.
            /// </summary>
            [JsonPropertyName("pagination")]
            public Pagination? Pagination { get; init; }
        }

        /// <summary>
        /// Returns a list of all [access system entrances](https://docs.seam.co/low-level-apis/access-systems/retrieving-entrance-details).
        /// </summary>
        public async Task<List<AcsEntrance>> ListAsync(
            ListRequest? request = null,
            CancellationToken cancellationToken = default
        )
        {
            var response = await _transport
                .SendAsync<ListResponse>(
                    HttpMethod.Get,
                    "/acs/entrances/list",
                    request,
                    "acs_entrances",
                    cancellationToken
                )
                .ConfigureAwait(false);
            return response.Read(r => r.AcsEntrances);
        }

        /// <summary>Fetches one page of /acs/entrances/list with its pagination metadata.</summary>
        public async Task<SeamPage<AcsEntrance>> ListPageAsync(
            ListRequest? request = null,
            CancellationToken cancellationToken = default
        )
        {
            var response = await _transport
                .SendAsync<ListResponse>(
                    HttpMethod.Get,
                    "/acs/entrances/list",
                    request,
                    "acs_entrances",
                    cancellationToken
                )
                .ConfigureAwait(false);
            return new SeamPage<AcsEntrance>(
                response.Read(r => r.AcsEntrances),
                response.Read("pagination", r => r.Pagination)
            );
        }

        /// <summary>Creates a paginator over /acs/entrances/list.</summary>
        public SeamPaginator<AcsEntrance> ListPager(ListRequest? request = null)
        {
            return new SeamPaginator<AcsEntrance>(
                (pageCursor, cancellationToken) =>
                    ListPageAsync(
                        pageCursor == null
                            ? request
                            : (request ?? new ListRequest()) with
                            {
                                PageCursor = pageCursor,
                            },
                        cancellationToken
                    )
            );
        }

        /// <summary>
        /// Request parameters for List Credentials with Access to an Entrance.
        /// </summary>
        public sealed record ListCredentialsWithAccessRequest
        {
            /// <summary>
            /// Conditions that credentials must meet to be included in the returned list.
            /// </summary>
            [JsonConverter(typeof(SeamStringEnumConverter))]
            public enum IncludeIfEnum
            {
                [EnumMember(Value = "unrecognized")]
                Unrecognized = 0,

                [EnumMember(Value = "visionline_metadata.is_valid")]
                VisionlineMetadataIsValid = 1,
            }

            /// <summary>
            /// ID of the entrance for which you want to list all credentials that grant access.
            /// </summary>
            [JsonPropertyName("acs_entrance_id")]
            public required string AcsEntranceId { get; init; }

            /// <summary>
            /// Conditions that credentials must meet to be included in the returned list.
            /// </summary>
            [JsonPropertyName("include_if")]
            public List<ListCredentialsWithAccessRequest.IncludeIfEnum>? IncludeIf { get; init; }
        }

        public sealed record ListCredentialsWithAccessResponse
        {
            /// <summary>
            /// OK
            /// </summary>
            [JsonPropertyName("acs_credentials")]
            public List<AcsCredential>? AcsCredentials { get; init; }
        }

        /// <summary>
        /// Returns a list of all [credentials](https://docs.seam.co/low-level-apis/access-systems/managing-credentials) with access to a specified [entrance](https://docs.seam.co/low-level-apis/access-systems/retrieving-entrance-details).
        /// </summary>
        public async Task<List<AcsCredential>> ListCredentialsWithAccessAsync(
            ListCredentialsWithAccessRequest request,
            CancellationToken cancellationToken = default
        )
        {
            var response = await _transport
                .SendAsync<ListCredentialsWithAccessResponse>(
                    HttpMethod.Get,
                    "/acs/entrances/list_credentials_with_access",
                    request,
                    "acs_credentials",
                    cancellationToken
                )
                .ConfigureAwait(false);
            return response.Read(r => r.AcsCredentials);
        }

        /// <summary>
        /// Request parameters for Unlock an Entrance.
        /// </summary>
        public sealed record UnlockRequest
        {
            /// <summary>
            /// ID of the cloud_key credential to use for the unlock operation.
            /// </summary>
            [JsonPropertyName("acs_credential_id")]
            public required string AcsCredentialId { get; init; }

            /// <summary>
            /// ID of the entrance to unlock.
            /// </summary>
            [JsonPropertyName("acs_entrance_id")]
            public required string AcsEntranceId { get; init; }
        }

        public sealed record UnlockResponse
        {
            /// <summary>
            /// OK
            /// </summary>
            [JsonPropertyName("action_attempt")]
            public ActionAttempt? ActionAttempt { get; init; }
        }

        /// <summary>
        /// Remotely unlocks a specified [entrance](https://docs.seam.co/low-level-apis/access-systems/retrieving-entrance-details) using a cloud_key credential. Returns an action attempt that tracks the progress of the unlock operation.
        /// </summary>
        public async Task<ActionAttempt> UnlockAsync(
            UnlockRequest request,
            ActionAttemptWait? waitForActionAttempt = null,
            CancellationToken cancellationToken = default
        )
        {
            var response = await _transport
                .SendAsync<UnlockResponse>(
                    HttpMethod.Post,
                    "/acs/entrances/unlock",
                    request,
                    "action_attempt",
                    cancellationToken
                )
                .ConfigureAwait(false);
            var actionAttempt = response.Read(r => r.ActionAttempt);
            return await ActionAttemptResolver
                .ResolveAsync(
                    actionAttempt,
                    _transport,
                    waitForActionAttempt ?? _waitForActionAttemptDefault,
                    cancellationToken
                )
                .ConfigureAwait(false);
        }
    }
}
