// <auto-generated>
//   Generated by codegen/smith.ts from @seamapi/types. Do not edit.
// </auto-generated>
#nullable enable
#pragma warning disable CS0618 // The generated code references its own deprecated members.
using System.Runtime.Serialization;
using System.Text.Json;
using System.Text.Json.Serialization;
using Seam.Http;
using Seam.Models;

namespace Seam.Routes
{
    public sealed class AcsUsers
    {
        private readonly SeamHttpTransport _transport;
        private readonly ActionAttemptWait _waitForActionAttemptDefault;

        internal AcsUsers(
            SeamHttpTransport transport,
            ActionAttemptWait waitForActionAttemptDefault
        )
        {
            _transport = transport;
            _waitForActionAttemptDefault = waitForActionAttemptDefault;
        }

        /// <summary>
        /// Request parameters for Add an ACS User to an Access Group.
        /// </summary>
        public sealed record AddToAccessGroupRequest
        {
            /// <summary>
            /// ID of the access group to which you want to add an access system user.
            /// </summary>
            [JsonPropertyName("acs_access_group_id")]
            public required string AcsAccessGroupId { get; init; }

            /// <summary>
            /// ID of the access system user that you want to add to an access group.
            /// </summary>
            [JsonPropertyName("acs_user_id")]
            public required string AcsUserId { get; init; }
        }

        /// <summary>
        /// Adds a specified [access system user](https://docs.seam.co/low-level-apis/access-systems/user-management) to a specified [access group](https://docs.seam.co/low-level-apis/access-systems/user-management/assigning-users-to-access-groups).
        /// </summary>
        public async Task AddToAccessGroupAsync(
            AddToAccessGroupRequest request,
            CancellationToken cancellationToken = default
        )
        {
            await _transport
                .SendAsync(
                    HttpMethod.Put,
                    "/acs/users/add_to_access_group",
                    request,
                    cancellationToken
                )
                .ConfigureAwait(false);
        }

        /// <summary>
        /// Request parameters for Create an ACS User.
        /// </summary>
        public sealed record CreateRequest
        {
            /// <summary>
            /// `starts_at` and `ends_at` timestamps for the new access system user&apos;s access. If you specify an `access_schedule`, you may include both `starts_at` and `ends_at`. If you omit `starts_at`, it defaults to the current time. `ends_at` is optional and must be a time in the future and after `starts_at`.
            /// </summary>
            [JsonPropertyName("access_schedule")]
            public CreateRequestAccessSchedule? AccessSchedule { get; init; }

            /// <summary>
            /// Array of access group IDs to indicate the access groups to which you want to add the new access system user.
            /// </summary>
            [JsonPropertyName("acs_access_group_ids")]
            public List<string>? AcsAccessGroupIds { get; init; }

            /// <summary>
            /// ID of the access system to which you want to add the new access system user.
            /// </summary>
            [JsonPropertyName("acs_system_id")]
            public required string AcsSystemId { get; init; }

            [Obsolete("use email_address.")]
            [JsonPropertyName("email")]
            public string? Email { get; init; }

            /// <summary>
            /// Email address of the [access system user](https://docs.seam.co/low-level-apis/access-systems/user-management).
            /// </summary>
            [JsonPropertyName("email_address")]
            public string? EmailAddress { get; init; }

            /// <summary>
            /// Full name of the new access system user.
            /// </summary>
            [JsonPropertyName("full_name")]
            public required string FullName { get; init; }

            /// <summary>
            /// Phone number of the [access system user](https://docs.seam.co/low-level-apis/access-systems/user-management) in E.164 format (for example, `+15555550100`).
            /// </summary>
            [JsonPropertyName("phone_number")]
            public string? PhoneNumber { get; init; }

            /// <summary>
            /// ID of the user identity with which you want to associate the new access system user.
            /// </summary>
            [JsonPropertyName("user_identity_id")]
            public string? UserIdentityId { get; init; }
        }

        public sealed record CreateRequestAccessSchedule
        {
            /// <summary>
            /// Ending timestamp for the new access system user&apos;s access.
            /// </summary>
            [JsonPropertyName("ends_at")]
            public Optional<string> EndsAt { get; init; }

            /// <summary>
            /// Starting timestamp for the new access system user&apos;s access.
            /// </summary>
            [JsonPropertyName("starts_at")]
            public string? StartsAt { get; init; }
        }

        public sealed record CreateResponse
        {
            /// <summary>
            /// OK
            /// </summary>
            [JsonPropertyName("acs_user")]
            public AcsUser? AcsUser { get; init; }
        }

        /// <summary>
        /// Creates a new [access system user](https://docs.seam.co/low-level-apis/access-systems/user-management).
        /// </summary>
        public async Task<AcsUser> CreateAsync(
            CreateRequest request,
            CancellationToken cancellationToken = default
        )
        {
            var response = await _transport
                .SendAsync<CreateResponse>(
                    HttpMethod.Post,
                    "/acs/users/create",
                    request,
                    cancellationToken
                )
                .ConfigureAwait(false);
            return response.AcsUser
                ?? throw new HttpRequestException(
                    "Seam returned no acs_user for /acs/users/create"
                );
        }

        /// <summary>
        /// Request parameters for Delete an ACS User.
        /// </summary>
        public sealed record DeleteRequest
        {
            /// <summary>
            /// ID of the access system that you want to delete. You must provide acs_system_id with user_identity_id.
            /// </summary>
            [JsonPropertyName("acs_system_id")]
            public string? AcsSystemId { get; init; }

            /// <summary>
            /// ID of the access system user that you want to delete. You must provide either acs_user_id or user_identity_id
            /// </summary>
            [JsonPropertyName("acs_user_id")]
            public string? AcsUserId { get; init; }

            /// <summary>
            /// ID of the user identity that you want to delete. You must provide either acs_user_id or user_identity_id. If you provide user_identity_id, you must also provide acs_system_id.
            /// </summary>
            [JsonPropertyName("user_identity_id")]
            public string? UserIdentityId { get; init; }

            internal void Validate()
            {
                if (AcsSystemId == null && AcsUserId == null && UserIdentityId == null)
                {
                    throw new ArgumentException(
                        "At least one parameter is required for /acs/users/delete"
                    );
                }
            }
        }

        /// <summary>
        /// Deletes a specified [access system user](https://docs.seam.co/low-level-apis/access-systems/user-management) and invalidates the access system user&apos;s [credentials](https://docs.seam.co/low-level-apis/access-systems/managing-credentials).
        /// </summary>
        public async Task DeleteAsync(
            DeleteRequest request,
            CancellationToken cancellationToken = default
        )
        {
            request.Validate();
            await _transport
                .SendAsync(HttpMethod.Delete, "/acs/users/delete", request, cancellationToken)
                .ConfigureAwait(false);
        }

        /// <summary>
        /// Request parameters for Get an ACS User.
        /// </summary>
        public sealed record GetRequest
        {
            /// <summary>
            /// ID of the access system that you want to get. You can only provide acs_user_id or user_identity_id.
            /// </summary>
            [JsonPropertyName("acs_system_id")]
            public string? AcsSystemId { get; init; }

            /// <summary>
            /// ID of the access system user that you want to get. You can only provide acs_user_id or user_identity_id.
            /// </summary>
            [JsonPropertyName("acs_user_id")]
            public string? AcsUserId { get; init; }

            /// <summary>
            /// ID of the user identity that you want to get. You can only provide acs_user_id or user_identity_id.
            /// </summary>
            [JsonPropertyName("user_identity_id")]
            public string? UserIdentityId { get; init; }

            internal void Validate()
            {
                if (AcsSystemId == null && AcsUserId == null && UserIdentityId == null)
                {
                    throw new ArgumentException(
                        "At least one parameter is required for /acs/users/get"
                    );
                }
            }
        }

        public sealed record GetResponse
        {
            /// <summary>
            /// OK
            /// </summary>
            [JsonPropertyName("acs_user")]
            public AcsUser? AcsUser { get; init; }
        }

        /// <summary>
        /// Returns a specified [access system user](https://docs.seam.co/low-level-apis/access-systems/user-management).
        /// </summary>
        public async Task<AcsUser> GetAsync(
            GetRequest request,
            CancellationToken cancellationToken = default
        )
        {
            request.Validate();
            var response = await _transport
                .SendAsync<GetResponse>(
                    HttpMethod.Get,
                    "/acs/users/get",
                    request,
                    cancellationToken
                )
                .ConfigureAwait(false);
            return response.AcsUser
                ?? throw new HttpRequestException("Seam returned no acs_user for /acs/users/get");
        }

        /// <summary>
        /// Request parameters for List ACS Users.
        /// </summary>
        public sealed record ListRequest
        {
            /// <summary>
            /// ID of the `acs_system` for which you want to retrieve all access system users.
            /// </summary>
            [JsonPropertyName("acs_system_id")]
            public string? AcsSystemId { get; init; }

            /// <summary>
            /// Timestamp by which to limit returned access system users. Returns users created before this timestamp.
            /// </summary>
            [JsonPropertyName("created_before")]
            public string? CreatedBefore { get; init; }

            /// <summary>
            /// Maximum number of records to return per page.
            /// </summary>
            [JsonPropertyName("limit")]
            public int? Limit { get; init; }

            /// <summary>
            /// Identifies the specific page of results to return, obtained from the previous page&apos;s `next_page_cursor`.
            /// </summary>
            [JsonPropertyName("page_cursor")]
            public Optional<string> PageCursor { get; init; }

            /// <summary>
            /// String for which to search. Filters returned access system users to include all records that satisfy a partial match using `full_name`, `phone_number`, `email_address`, `acs_user_id`, `user_identity_id`, `user_identity_full_name` or `user_identity_phone_number`.
            /// </summary>
            [JsonPropertyName("search")]
            public string? Search { get; init; }

            /// <summary>
            /// Email address of the user identity for which you want to retrieve all access system users. Specify `null` to retrieve access system users whose user identity has no email address.
            /// </summary>
            [JsonPropertyName("user_identity_email_address")]
            public Optional<string> UserIdentityEmailAddress { get; init; }

            /// <summary>
            /// ID of the user identity for which you want to retrieve all access system users.
            /// </summary>
            [JsonPropertyName("user_identity_id")]
            public string? UserIdentityId { get; init; }

            /// <summary>
            /// Phone number of the user identity for which you want to retrieve all access system users, in [E.164 format](https://www.itu.int/rec/T-REC-E.164/en) (for example, `+15555550100`). Specify `null` to retrieve access system users whose user identity has no phone number.
            /// </summary>
            [JsonPropertyName("user_identity_phone_number")]
            public Optional<string> UserIdentityPhoneNumber { get; init; }
        }

        public sealed record ListResponse
        {
            /// <summary>
            /// OK
            /// </summary>
            [JsonPropertyName("acs_users")]
            public List<AcsUser>? AcsUsers { get; init; }

            /// <summary>
            /// The pagination metadata for the page of results.
            /// </summary>
            [JsonPropertyName("pagination")]
            public Pagination? Pagination { get; init; }
        }

        /// <summary>
        /// Returns a list of all [access system users](https://docs.seam.co/low-level-apis/access-systems/user-management).
        /// </summary>
        public async Task<List<AcsUser>> ListAsync(
            ListRequest? request = null,
            CancellationToken cancellationToken = default
        )
        {
            var response = await _transport
                .SendAsync<ListResponse>(
                    HttpMethod.Get,
                    "/acs/users/list",
                    request,
                    cancellationToken
                )
                .ConfigureAwait(false);
            return response.AcsUsers
                ?? throw new HttpRequestException("Seam returned no acs_users for /acs/users/list");
        }

        /// <summary>Fetches one page of /acs/users/list with its pagination metadata.</summary>
        public async Task<SeamPage<AcsUser>> ListPageAsync(
            ListRequest? request = null,
            CancellationToken cancellationToken = default
        )
        {
            var response = await _transport
                .SendAsync<ListResponse>(
                    HttpMethod.Get,
                    "/acs/users/list",
                    request,
                    cancellationToken
                )
                .ConfigureAwait(false);
            var items =
                response.AcsUsers
                ?? throw new HttpRequestException("Seam returned no acs_users for /acs/users/list");
            var pagination =
                response.Pagination
                ?? throw new HttpRequestException(
                    "Seam returned no pagination for /acs/users/list"
                );
            return new SeamPage<AcsUser>(items, pagination);
        }

        /// <summary>Creates a paginator over /acs/users/list.</summary>
        public SeamPaginator<AcsUser> ListPager(ListRequest? request = null)
        {
            return new SeamPaginator<AcsUser>(
                (pageCursor, cancellationToken) =>
                    ListPageAsync(
                        pageCursor == null
                            ? request
                            : (request ?? new ListRequest()) with
                            {
                                PageCursor = pageCursor,
                            },
                        cancellationToken
                    )
            );
        }

        /// <summary>
        /// Request parameters for List ACS User-Accessible Entrances.
        /// </summary>
        public sealed record ListAccessibleEntrancesRequest
        {
            /// <summary>
            /// ID of the access system for which you want to list accessible entrances. You can only provide acs_system_id with user_identity_id.
            /// </summary>
            [JsonPropertyName("acs_system_id")]
            public string? AcsSystemId { get; init; }

            /// <summary>
            /// ID of the access system user for whom you want to list accessible entrances. You can only provide acs_user_id or user_identity_id.
            /// </summary>
            [JsonPropertyName("acs_user_id")]
            public string? AcsUserId { get; init; }

            /// <summary>
            /// ID of the user identity for whom you want to list accessible entrances. You can only provide acs_user_id or user_identity_id.
            /// </summary>
            [JsonPropertyName("user_identity_id")]
            public string? UserIdentityId { get; init; }

            internal void Validate()
            {
                if (AcsSystemId == null && AcsUserId == null && UserIdentityId == null)
                {
                    throw new ArgumentException(
                        "At least one parameter is required for /acs/users/list_accessible_entrances"
                    );
                }
            }
        }

        public sealed record ListAccessibleEntrancesResponse
        {
            /// <summary>
            /// OK
            /// </summary>
            [JsonPropertyName("acs_entrances")]
            public List<AcsEntrance>? AcsEntrances { get; init; }
        }

        /// <summary>
        /// Lists the [entrances](https://docs.seam.co/api/acs/entrances) to which a specified [access system user](https://docs.seam.co/low-level-apis/access-systems/user-management) has access.
        /// </summary>
        public async Task<List<AcsEntrance>> ListAccessibleEntrancesAsync(
            ListAccessibleEntrancesRequest request,
            CancellationToken cancellationToken = default
        )
        {
            request.Validate();
            var response = await _transport
                .SendAsync<ListAccessibleEntrancesResponse>(
                    HttpMethod.Get,
                    "/acs/users/list_accessible_entrances",
                    request,
                    cancellationToken
                )
                .ConfigureAwait(false);
            return response.AcsEntrances
                ?? throw new HttpRequestException(
                    "Seam returned no acs_entrances for /acs/users/list_accessible_entrances"
                );
        }

        /// <summary>
        /// Request parameters for Remove an ACS User from an Access Group.
        /// </summary>
        public sealed record RemoveFromAccessGroupRequest
        {
            /// <summary>
            /// ID of the access group from which you want to remove an access system user.
            /// </summary>
            [JsonPropertyName("acs_access_group_id")]
            public required string AcsAccessGroupId { get; init; }

            /// <summary>
            /// ID of the access system user that you want to remove from an access group. You can only provide acs_user_id or user_identity_id.
            /// </summary>
            [JsonPropertyName("acs_user_id")]
            public string? AcsUserId { get; init; }

            /// <summary>
            /// ID of the user identity that you want to remove from an access group. You can only provide acs_user_id or user_identity_id.
            /// </summary>
            [JsonPropertyName("user_identity_id")]
            public string? UserIdentityId { get; init; }
        }

        /// <summary>
        /// Removes a specified [access system user](https://docs.seam.co/low-level-apis/access-systems/user-management) from a specified [access group](https://docs.seam.co/low-level-apis/access-systems/user-management/assigning-users-to-access-groups).
        /// </summary>
        public async Task RemoveFromAccessGroupAsync(
            RemoveFromAccessGroupRequest request,
            CancellationToken cancellationToken = default
        )
        {
            await _transport
                .SendAsync(
                    HttpMethod.Delete,
                    "/acs/users/remove_from_access_group",
                    request,
                    cancellationToken
                )
                .ConfigureAwait(false);
        }

        /// <summary>
        /// Request parameters for Revoke ACS User Access to All Entrances.
        /// </summary>
        public sealed record RevokeAccessToAllEntrancesRequest
        {
            /// <summary>
            /// ID of the access system for which you want to revoke access. You can only provide acs_system_id with user_identity_id.
            /// </summary>
            [JsonPropertyName("acs_system_id")]
            public string? AcsSystemId { get; init; }

            /// <summary>
            /// ID of the access system user for whom you want to revoke access. You can only provide acs_user_id or user_identity_id.
            /// </summary>
            [JsonPropertyName("acs_user_id")]
            public string? AcsUserId { get; init; }

            /// <summary>
            /// ID of the user identity for whom you want to revoke access. You can only provide acs_user_id or user_identity_id.
            /// </summary>
            [JsonPropertyName("user_identity_id")]
            public string? UserIdentityId { get; init; }

            internal void Validate()
            {
                if (AcsSystemId == null && AcsUserId == null && UserIdentityId == null)
                {
                    throw new ArgumentException(
                        "At least one parameter is required for /acs/users/revoke_access_to_all_entrances"
                    );
                }
            }
        }

        /// <summary>
        /// Revokes access to all [entrances](https://docs.seam.co/api/acs/entrances) for a specified [access system user](https://docs.seam.co/low-level-apis/access-systems/user-management).
        /// </summary>
        public async Task RevokeAccessToAllEntrancesAsync(
            RevokeAccessToAllEntrancesRequest request,
            CancellationToken cancellationToken = default
        )
        {
            request.Validate();
            await _transport
                .SendAsync(
                    HttpMethod.Post,
                    "/acs/users/revoke_access_to_all_entrances",
                    request,
                    cancellationToken
                )
                .ConfigureAwait(false);
        }

        /// <summary>
        /// Request parameters for Suspend an ACS User.
        /// </summary>
        public sealed record SuspendRequest
        {
            /// <summary>
            /// ID of the access system that you want to suspend. You can only provide acs_user_id or the combination of acs_system_id and user_identity_id.
            /// </summary>
            [JsonPropertyName("acs_system_id")]
            public string? AcsSystemId { get; init; }

            /// <summary>
            /// ID of the access system user that you want to suspend. You can only provide acs_user_id or the combination of acs_system_id and user_identity_id.
            /// </summary>
            [JsonPropertyName("acs_user_id")]
            public string? AcsUserId { get; init; }

            /// <summary>
            /// ID of the user identity that you want to suspend. You can only provide acs_user_id or the combination of acs_system_id and user_identity_id.
            /// </summary>
            [JsonPropertyName("user_identity_id")]
            public string? UserIdentityId { get; init; }

            internal void Validate()
            {
                if (AcsSystemId == null && AcsUserId == null && UserIdentityId == null)
                {
                    throw new ArgumentException(
                        "At least one parameter is required for /acs/users/suspend"
                    );
                }
            }
        }

        /// <summary>
        /// [Suspends](https://docs.seam.co/low-level-apis/access-systems/user-management/suspending-and-unsuspending-users#suspend-an-acs-user) a specified [access system user](https://docs.seam.co/low-level-apis/access-systems/user-management). Suspending an access system user revokes their access temporarily. To restore an access system user&apos;s access, you can [unsuspend](https://docs.seam.co/api/acs/users/unsuspend) them.
        /// </summary>
        public async Task SuspendAsync(
            SuspendRequest request,
            CancellationToken cancellationToken = default
        )
        {
            request.Validate();
            await _transport
                .SendAsync(HttpMethod.Post, "/acs/users/suspend", request, cancellationToken)
                .ConfigureAwait(false);
        }

        /// <summary>
        /// Request parameters for Unsuspend an ACS User.
        /// </summary>
        public sealed record UnsuspendRequest
        {
            /// <summary>
            /// ID of the access system of the user that you want to unsuspend. You can only provide acs_system_id with user_identity_id.
            /// </summary>
            [JsonPropertyName("acs_system_id")]
            public string? AcsSystemId { get; init; }

            /// <summary>
            /// ID of the access system user that you want to unsuspend. You can only provide acs_user_id or the combination of acs_system_id and user_identity_id.
            /// </summary>
            [JsonPropertyName("acs_user_id")]
            public string? AcsUserId { get; init; }

            /// <summary>
            /// ID of the user identity that you want to unsuspend. You can only provide acs_user_id or the combination of acs_system_id and user_identity_id.
            /// </summary>
            [JsonPropertyName("user_identity_id")]
            public string? UserIdentityId { get; init; }

            internal void Validate()
            {
                if (AcsSystemId == null && AcsUserId == null && UserIdentityId == null)
                {
                    throw new ArgumentException(
                        "At least one parameter is required for /acs/users/unsuspend"
                    );
                }
            }
        }

        /// <summary>
        /// [Unsuspends](https://docs.seam.co/low-level-apis/access-systems/user-management/suspending-and-unsuspending-users#unsuspend-an-acs-user) a specified suspended [access system user](https://docs.seam.co/low-level-apis/access-systems/user-management). While [suspending an access system user](https://docs.seam.co/api/acs/users/suspend) revokes their access temporarily, unsuspending the access system user restores their access.
        /// </summary>
        public async Task UnsuspendAsync(
            UnsuspendRequest request,
            CancellationToken cancellationToken = default
        )
        {
            request.Validate();
            await _transport
                .SendAsync(HttpMethod.Post, "/acs/users/unsuspend", request, cancellationToken)
                .ConfigureAwait(false);
        }

        /// <summary>
        /// Request parameters for Update an ACS User.
        /// </summary>
        public sealed record UpdateRequest
        {
            /// <summary>
            /// `starts_at` and `ends_at` timestamps for the access system user&apos;s access. If you specify an `access_schedule`, you may include both `starts_at` and `ends_at`. If you omit `starts_at`, it defaults to the current time. `ends_at` is optional and must be a time in the future and after `starts_at`.
            /// </summary>
            [JsonPropertyName("access_schedule")]
            public Optional<UpdateRequestAccessSchedule> AccessSchedule { get; init; }

            /// <summary>
            /// ID of the access system that you want to update. You can only provide acs_system_id with user_identity_id.
            /// </summary>
            [JsonPropertyName("acs_system_id")]
            public string? AcsSystemId { get; init; }

            /// <summary>
            /// ID of the access system user that you want to update. You can only provide acs_user_id or user_identity_id.
            /// </summary>
            [JsonPropertyName("acs_user_id")]
            public string? AcsUserId { get; init; }

            [Obsolete("use email_address.")]
            [JsonPropertyName("email")]
            public string? Email { get; init; }

            /// <summary>
            /// Email address of the [access system user](https://docs.seam.co/low-level-apis/access-systems/user-management).
            /// </summary>
            [JsonPropertyName("email_address")]
            public string? EmailAddress { get; init; }

            /// <summary>
            /// Full name of the [access system user](https://docs.seam.co/low-level-apis/access-systems/user-management).
            /// </summary>
            [JsonPropertyName("full_name")]
            public string? FullName { get; init; }

            /// <summary>
            /// ID of the HID access control system associated with the user.
            /// </summary>
            [JsonPropertyName("hid_acs_system_id")]
            public string? HidAcsSystemId { get; init; }

            /// <summary>
            /// Phone number of the [access system user](https://docs.seam.co/low-level-apis/access-systems/user-management) in E.164 format (for example, `+15555550100`).
            /// </summary>
            [JsonPropertyName("phone_number")]
            public string? PhoneNumber { get; init; }

            /// <summary>
            /// ID of the user identity that you want to update. You can only provide acs_user_id or user_identity_id. If you provide user_identity_id, you must also provide acs_system_id.
            /// </summary>
            [JsonPropertyName("user_identity_id")]
            public string? UserIdentityId { get; init; }

            internal void Validate()
            {
                if (
                    !AccessSchedule.IsSet
                    && AcsSystemId == null
                    && AcsUserId == null
                    && Email == null
                    && EmailAddress == null
                    && FullName == null
                    && HidAcsSystemId == null
                    && PhoneNumber == null
                    && UserIdentityId == null
                )
                {
                    throw new ArgumentException(
                        "At least one parameter is required for /acs/users/update"
                    );
                }
            }
        }

        public sealed record UpdateRequestAccessSchedule
        {
            /// <summary>
            /// Ending timestamp for the access system user&apos;s access.
            /// </summary>
            [JsonPropertyName("ends_at")]
            public string? EndsAt { get; init; }

            /// <summary>
            /// Starting timestamp for the access system user&apos;s access.
            /// </summary>
            [JsonPropertyName("starts_at")]
            public string? StartsAt { get; init; }
        }

        /// <summary>
        /// Updates the properties of a specified [access system user](https://docs.seam.co/low-level-apis/access-systems/user-management).
        /// </summary>
        public async Task UpdateAsync(
            UpdateRequest request,
            CancellationToken cancellationToken = default
        )
        {
            request.Validate();
            await _transport
                .SendAsync(HttpMethod.Patch, "/acs/users/update", request, cancellationToken)
                .ConfigureAwait(false);
        }
    }
}
