// <auto-generated>
//   Generated by codegen/smith.ts from @seamapi/types. Do not edit.
// </auto-generated>
#nullable enable
#pragma warning disable CS0618 // The generated code references its own deprecated members.
using System.Runtime.Serialization;
using System.Text.Json;
using System.Text.Json.Serialization;
using Seam.Http;
using Seam.Models;

namespace Seam.Routes
{
    public sealed class ConnectWebviews
    {
        private readonly SeamHttpTransport _transport;
        private readonly ActionAttemptWait _waitForActionAttemptDefault;

        internal ConnectWebviews(
            SeamHttpTransport transport,
            ActionAttemptWait waitForActionAttemptDefault
        )
        {
            _transport = transport;
            _waitForActionAttemptDefault = waitForActionAttemptDefault;
        }

        /// <summary>
        /// Request parameters for Create a Connect Webview.
        /// </summary>
        public sealed record CreateRequest
        {
            /// <summary>
            /// List of accepted device capabilities that restrict the types of devices that can be connected through the Connect Webview. If not provided, defaults will be determined based on the accepted providers.
            /// </summary>
            [JsonConverter(typeof(SeamStringEnumConverter))]
            public enum AcceptedCapabilitiesEnum
            {
                [EnumMember(Value = "unrecognized")]
                Unrecognized = 0,

                [EnumMember(Value = "lock")]
                Lock = 1,

                [EnumMember(Value = "thermostat")]
                Thermostat = 2,

                [EnumMember(Value = "noise_sensor")]
                NoiseSensor = 3,

                [EnumMember(Value = "access_control")]
                AccessControl = 4,

                [EnumMember(Value = "camera")]
                Camera = 5,
            }

            /// <summary>
            /// Accepted device provider keys as an alternative to `provider_category`. Use this parameter to specify accepted providers explicitly. See [Customize the Brands to Display in Your Connect Webviews](https://docs.seam.co/core-concepts/connect-webviews/customizing-connect-webviews#customize-the-brands-to-display-in-your-connect-webviews). To list all provider keys, use [`/devices/list_device_providers`](https://docs.seam.co/api/devices/list_device_providers) with no filters.
            /// </summary>
            [JsonConverter(typeof(SeamStringEnumConverter))]
            public enum AcceptedProvidersEnum
            {
                [EnumMember(Value = "unrecognized")]
                Unrecognized = 0,

                [EnumMember(Value = "hotek")]
                Hotek = 1,

                [EnumMember(Value = "dormakaba_community")]
                DormakabaCommunity = 2,

                [EnumMember(Value = "legic_connect")]
                LegicConnect = 3,

                [EnumMember(Value = "akuvox")]
                Akuvox = 4,

                [EnumMember(Value = "august")]
                August = 5,

                [EnumMember(Value = "avigilon_alta")]
                AvigilonAlta = 6,

                [EnumMember(Value = "brivo")]
                Brivo = 7,

                [EnumMember(Value = "butterflymx")]
                Butterflymx = 8,

                [EnumMember(Value = "schlage")]
                Schlage = 9,

                [EnumMember(Value = "smartthings")]
                Smartthings = 10,

                [EnumMember(Value = "yale")]
                Yale = 11,

                [EnumMember(Value = "genie")]
                Genie = 12,

                [EnumMember(Value = "doorking")]
                Doorking = 13,

                [EnumMember(Value = "salto")]
                Salto = 14,

                [EnumMember(Value = "salto_ks")]
                SaltoKs = 15,

                [EnumMember(Value = "salto_ks_accept")]
                SaltoKsAccept = 16,

                [EnumMember(Value = "lockly")]
                Lockly = 17,

                [EnumMember(Value = "ttlock")]
                Ttlock = 18,

                [EnumMember(Value = "linear")]
                Linear = 19,

                [EnumMember(Value = "noiseaware")]
                Noiseaware = 20,

                [EnumMember(Value = "nuki")]
                Nuki = 21,

                [EnumMember(Value = "igloo")]
                Igloo = 22,

                [EnumMember(Value = "kwikset")]
                Kwikset = 23,

                [EnumMember(Value = "minut")]
                Minut = 24,

                [EnumMember(Value = "my_2n")]
                My_2n = 25,

                [EnumMember(Value = "controlbyweb")]
                Controlbyweb = 26,

                [EnumMember(Value = "nest")]
                Nest = 27,

                [EnumMember(Value = "igloohome")]
                Igloohome = 28,

                [EnumMember(Value = "ecobee")]
                Ecobee = 29,

                [EnumMember(Value = "four_suites")]
                FourSuites = 30,

                [EnumMember(Value = "dormakaba_oracode")]
                DormakabaOracode = 31,

                [EnumMember(Value = "pti")]
                Pti = 32,

                [EnumMember(Value = "wyze")]
                Wyze = 33,

                [EnumMember(Value = "seam_passport")]
                SeamPassport = 34,

                [EnumMember(Value = "visionline")]
                Visionline = 35,

                [EnumMember(Value = "assa_abloy_credential_service")]
                AssaAbloyCredentialService = 36,

                [EnumMember(Value = "tedee")]
                Tedee = 37,

                [EnumMember(Value = "honeywell_resideo")]
                HoneywellResideo = 38,

                [EnumMember(Value = "first_alert")]
                FirstAlert = 39,

                [EnumMember(Value = "latch")]
                Latch = 40,

                [EnumMember(Value = "akiles")]
                Akiles = 41,

                [EnumMember(Value = "assa_abloy_vostio")]
                AssaAbloyVostio = 42,

                [EnumMember(Value = "assa_abloy_vostio_credential_service")]
                AssaAbloyVostioCredentialService = 43,

                [EnumMember(Value = "tado")]
                Tado = 44,

                [EnumMember(Value = "salto_space")]
                SaltoSpace = 45,

                [EnumMember(Value = "sensi")]
                Sensi = 46,

                [EnumMember(Value = "keynest")]
                Keynest = 47,

                [EnumMember(Value = "korelock")]
                Korelock = 48,

                [EnumMember(Value = "keyincode")]
                Keyincode = 49,

                [EnumMember(Value = "dormakaba_ambiance")]
                DormakabaAmbiance = 50,

                [EnumMember(Value = "ultraloq")]
                Ultraloq = 51,

                [EnumMember(Value = "yacan")]
                Yacan = 52,

                [EnumMember(Value = "dusaw")]
                Dusaw = 53,

                [EnumMember(Value = "sifely")]
                Sifely = 54,

                [EnumMember(Value = "thirty_three_lock")]
                ThirtyThreeLock = 55,

                [EnumMember(Value = "ring")]
                Ring = 56,

                [EnumMember(Value = "ical")]
                Ical = 57,

                [EnumMember(Value = "lodgify")]
                Lodgify = 58,

                [EnumMember(Value = "hostaway")]
                Hostaway = 59,

                [EnumMember(Value = "guesty")]
                Guesty = 60,

                [EnumMember(Value = "acuity_scheduling")]
                AcuityScheduling = 61,

                [EnumMember(Value = "omnitec")]
                Omnitec = 62,

                [EnumMember(Value = "kisi")]
                Kisi = 63,

                [EnumMember(Value = "aqara")]
                Aqara = 64,

                [EnumMember(Value = "yale_access")]
                YaleAccess = 65,

                [EnumMember(Value = "hid_cm")]
                HidCm = 66,

                [EnumMember(Value = "google_nest")]
                GoogleNest = 67,

                [EnumMember(Value = "slack")]
                Slack = 68,
            }

            /// <summary>
            /// Specifies the category of providers that you want to include. To list all providers within a category, use [`/devices/list_device_providers`](https://docs.seam.co/api/devices/list_device_providers) with the desired `provider_category` filter.
            /// </summary>
            [JsonConverter(typeof(SeamStringEnumConverter))]
            public enum ProviderCategoryEnum
            {
                [EnumMember(Value = "unrecognized")]
                Unrecognized = 0,

                [EnumMember(Value = "stable")]
                Stable = 1,

                [EnumMember(Value = "consumer_smartlocks")]
                ConsumerSmartlocks = 2,

                [EnumMember(Value = "beta")]
                Beta = 3,

                [EnumMember(Value = "thermostats")]
                Thermostats = 4,

                [EnumMember(Value = "noise_sensors")]
                NoiseSensors = 5,

                [EnumMember(Value = "access_control_systems")]
                AccessControlSystems = 6,

                [EnumMember(Value = "cameras")]
                Cameras = 7,

                [EnumMember(Value = "connectors")]
                Connectors = 8,

                [EnumMember(Value = "internal_beta")]
                InternalBeta = 9,
            }

            /// <summary>
            /// List of accepted device capabilities that restrict the types of devices that can be connected through the Connect Webview. If not provided, defaults will be determined based on the accepted providers.
            /// </summary>
            [JsonPropertyName("accepted_capabilities")]
            public List<CreateRequest.AcceptedCapabilitiesEnum>? AcceptedCapabilities { get; init; }

            /// <summary>
            /// Accepted device provider keys as an alternative to `provider_category`. Use this parameter to specify accepted providers explicitly. See [Customize the Brands to Display in Your Connect Webviews](https://docs.seam.co/core-concepts/connect-webviews/customizing-connect-webviews#customize-the-brands-to-display-in-your-connect-webviews). To list all provider keys, use [`/devices/list_device_providers`](https://docs.seam.co/api/devices/list_device_providers) with no filters.
            /// </summary>
            [JsonPropertyName("accepted_providers")]
            public List<CreateRequest.AcceptedProvidersEnum>? AcceptedProviders { get; init; }

            /// <summary>
            /// Indicates whether newly-added devices should appear as [managed devices](https://docs.seam.co/core-concepts/devices/managed-and-unmanaged-devices). See also: [Customize the Behavior Settings of Your Connect Webviews](https://docs.seam.co/core-concepts/connect-webviews/customizing-connect-webviews#customize-the-behavior-settings-of-your-connect-webviews).
            /// </summary>
            [JsonPropertyName("automatically_manage_new_devices")]
            public bool? AutomaticallyManageNewDevices { get; init; }

            /// <summary>
            /// Custom metadata that you want to associate with the Connect Webview. Supports up to 50 JSON key:value pairs, with key names up to 40 characters long that cannot contain a period (.). [Adding custom metadata to a Connect Webview](https://docs.seam.co/core-concepts/connect-webviews/attaching-custom-data-to-the-connect-webview) enables you to store custom information, like customer details or internal IDs from your application. The custom metadata is then transferred to any [connected accounts](https://docs.seam.co/core-concepts/connected-accounts) that were connected using the Connect Webview, making it easy to find and filter these resources in your [workspace](https://docs.seam.co/core-concepts/workspaces). You can also [filter Connect Webviews by custom metadata](https://docs.seam.co/core-concepts/connect-webviews/filtering-connect-webviews-by-custom-metadata). Set a key to `null` or to an empty string to remove that key from the custom metadata.
            /// </summary>
            [JsonPropertyName("custom_metadata")]
            public object? CustomMetadata { get; init; }

            /// <summary>
            /// Alternative URL that you want to redirect the user to on an error. If you do not set this parameter, the Connect Webview falls back to the `custom_redirect_url`.
            /// </summary>
            [JsonPropertyName("custom_redirect_failure_url")]
            public string? CustomRedirectFailureUrl { get; init; }

            /// <summary>
            /// URL that you want to redirect the user to after the provider login is complete.
            /// </summary>
            [JsonPropertyName("custom_redirect_url")]
            public string? CustomRedirectUrl { get; init; }

            /// <summary>
            /// Associate the Connect Webview, the connected account, and all resources under the connected account with a customer. If the connected account already exists, it will be associated with the customer. If the connected account already exists, but is already associated with a customer, the Connect Webview will show an error.
            /// </summary>
            [JsonPropertyName("customer_key")]
            public string? CustomerKey { get; init; }

            /// <summary>
            /// List of provider keys to exclude from the Connect Webview. These providers will not be shown when the user tries to connect an account.
            /// </summary>
            [JsonPropertyName("excluded_providers")]
            public List<string>? ExcludedProviders { get; init; }

            /// <summary>
            /// Specifies the category of providers that you want to include. To list all providers within a category, use [`/devices/list_device_providers`](https://docs.seam.co/api/devices/list_device_providers) with the desired `provider_category` filter.
            /// </summary>
            [JsonPropertyName("provider_category")]
            public CreateRequest.ProviderCategoryEnum? ProviderCategory { get; init; }

            /// <summary>
            /// Indicates whether Seam should finish syncing all devices in a newly-connected account before completing the associated Connect Webview. See also: [Customize the Behavior Settings of Your Connect Webviews](https://docs.seam.co/core-concepts/connect-webviews/customizing-connect-webviews#customize-the-behavior-settings-of-your-connect-webviews).
            /// </summary>
            [JsonPropertyName("wait_for_device_creation")]
            public bool? WaitForDeviceCreation { get; init; }
        }

        public sealed record CreateResponse
        {
            /// <summary>
            /// OK
            /// </summary>
            [JsonPropertyName("connect_webview")]
            public ConnectWebview? ConnectWebview { get; init; }
        }

        /// <summary>
        /// Creates a new [Connect Webview](https://docs.seam.co/core-concepts/connect-webviews).
        ///
        /// To enable a user to connect their devices or systems to Seam, they must sign in to their device or system account. To enable a user to sign in, you create a `connect_webview`. After creating the Connect Webview, you receive a URL that you can use to display the visual component of this Connect Webview for your user. You can open an iframe or new window to display the Connect Webview.
        ///
        /// You should make a new `connect_webview` for each unique login request. Each `connect_webview` tracks the user that signed in with it. You receive an error if you reuse a Connect Webview for the same user twice or if you use the same Connect Webview for multiple users.
        ///
        /// See also: [Connect Webview Process](https://docs.seam.co/core-concepts/connect-webviews/connect-webview-process).
        /// </summary>
        public async Task<ConnectWebview> CreateAsync(
            CreateRequest? request = null,
            CancellationToken cancellationToken = default
        )
        {
            var response = await _transport
                .SendAsync<CreateResponse>(
                    HttpMethod.Post,
                    "/connect_webviews/create",
                    request,
                    "connect_webview",
                    cancellationToken
                )
                .ConfigureAwait(false);
            return response.Read(r => r.ConnectWebview);
        }

        /// <summary>
        /// Request parameters for Delete a Connect Webview.
        /// </summary>
        public sealed record DeleteRequest
        {
            /// <summary>
            /// ID of the Connect Webview that you want to delete.
            /// </summary>
            [JsonPropertyName("connect_webview_id")]
            public required string ConnectWebviewId { get; init; }
        }

        /// <summary>
        /// Deletes a [Connect Webview](https://docs.seam.co/core-concepts/connect-webviews).
        ///
        /// You do not need to delete a Connect Webview once a user completes it. Instead, you can simply ignore completed Connect Webviews.
        /// </summary>
        public async Task DeleteAsync(
            DeleteRequest request,
            CancellationToken cancellationToken = default
        )
        {
            await _transport
                .SendAsync(
                    HttpMethod.Delete,
                    "/connect_webviews/delete",
                    request,
                    cancellationToken
                )
                .ConfigureAwait(false);
        }

        /// <summary>
        /// Request parameters for Get a Connect Webview.
        /// </summary>
        public sealed record GetRequest
        {
            /// <summary>
            /// ID of the Connect Webview that you want to get.
            /// </summary>
            [JsonPropertyName("connect_webview_id")]
            public required string ConnectWebviewId { get; init; }
        }

        public sealed record GetResponse
        {
            /// <summary>
            /// OK
            /// </summary>
            [JsonPropertyName("connect_webview")]
            public ConnectWebview? ConnectWebview { get; init; }
        }

        /// <summary>
        /// Returns a specified [Connect Webview](https://docs.seam.co/core-concepts/connect-webviews).
        ///
        /// Unless you&apos;re using a `custom_redirect_url`, you should poll a newly-created `connect_webview` to find out if the user has signed in or to get details about what devices they&apos;ve connected.
        /// </summary>
        public async Task<ConnectWebview> GetAsync(
            GetRequest request,
            CancellationToken cancellationToken = default
        )
        {
            var response = await _transport
                .SendAsync<GetResponse>(
                    HttpMethod.Get,
                    "/connect_webviews/get",
                    request,
                    "connect_webview",
                    cancellationToken
                )
                .ConfigureAwait(false);
            return response.Read(r => r.ConnectWebview);
        }

        /// <summary>
        /// Request parameters for List Connect Webviews.
        /// </summary>
        public sealed record ListRequest
        {
            /// <summary>
            /// Custom metadata pairs by which you want to [filter Connect Webviews](https://docs.seam.co/core-concepts/connect-webviews/filtering-connect-webviews-by-custom-metadata). Returns Connect Webviews with `custom_metadata` that contains all of the provided key:value pairs. Key names cannot contain a period (.). Specify `null` to match a key that is unset. A key given an empty string is omitted from the filter.
            /// </summary>
            [JsonPropertyName("custom_metadata_has")]
            public object? CustomMetadataHas { get; init; }

            /// <summary>
            /// Customer key for which you want to list connect webviews.
            /// </summary>
            [JsonPropertyName("customer_key")]
            public string? CustomerKey { get; init; }

            /// <summary>
            /// Maximum number of records to return per page.
            /// </summary>
            [JsonPropertyName("limit")]
            public float? Limit { get; init; }

            /// <summary>
            /// Identifies the specific page of results to return, obtained from the previous page&apos;s `next_page_cursor`.
            /// </summary>
            [JsonPropertyName("page_cursor")]
            public Optional<string> PageCursor { get; init; }

            /// <summary>
            /// String for which to search. Filters returned Connect Webviews to include all records that satisfy a partial match using `connect_webview_id`, `accepted_providers`, `custom_metadata`, or `customer_key`.
            /// </summary>
            [JsonPropertyName("search")]
            public string? Search { get; init; }

            /// <summary>
            /// Your user ID for the user by which you want to filter Connect Webviews.
            /// </summary>
            [JsonPropertyName("user_identifier_key")]
            public string? UserIdentifierKey { get; init; }
        }

        public sealed record ListResponse
        {
            /// <summary>
            /// OK
            /// </summary>
            [JsonPropertyName("connect_webviews")]
            public List<ConnectWebview>? ConnectWebviews { get; init; }

            /// <summary>
            /// The pagination metadata for the page of results.
            /// </summary>
            [JsonPropertyName("pagination")]
            public Pagination? Pagination { get; init; }
        }

        /// <summary>
        /// Returns a list of all [Connect Webviews](https://docs.seam.co/core-concepts/connect-webviews).
        /// </summary>
        public async Task<List<ConnectWebview>> ListAsync(
            ListRequest? request = null,
            CancellationToken cancellationToken = default
        )
        {
            var response = await _transport
                .SendAsync<ListResponse>(
                    HttpMethod.Get,
                    "/connect_webviews/list",
                    request,
                    "connect_webviews",
                    cancellationToken
                )
                .ConfigureAwait(false);
            return response.Read(r => r.ConnectWebviews);
        }

        /// <summary>Fetches one page of /connect_webviews/list with its pagination metadata.</summary>
        public async Task<SeamPage<ConnectWebview>> ListPageAsync(
            ListRequest? request = null,
            CancellationToken cancellationToken = default
        )
        {
            var response = await _transport
                .SendAsync<ListResponse>(
                    HttpMethod.Get,
                    "/connect_webviews/list",
                    request,
                    "connect_webviews",
                    cancellationToken
                )
                .ConfigureAwait(false);
            return new SeamPage<ConnectWebview>(
                response.Read(r => r.ConnectWebviews),
                response.Read("pagination", r => r.Pagination)
            );
        }

        /// <summary>Creates a paginator over /connect_webviews/list.</summary>
        public SeamPaginator<ConnectWebview> ListPager(ListRequest? request = null)
        {
            return new SeamPaginator<ConnectWebview>(
                (pageCursor, cancellationToken) =>
                    ListPageAsync(
                        pageCursor == null
                            ? request
                            : (request ?? new ListRequest()) with
                            {
                                PageCursor = pageCursor,
                            },
                        cancellationToken
                    )
            );
        }
    }
}
