// <auto-generated>
//   Generated by codegen/smith.ts from @seamapi/types. Do not edit.
// </auto-generated>
#nullable enable
#pragma warning disable CS0618 // The generated code references its own deprecated members.
using System.Runtime.Serialization;
using System.Text.Json;
using System.Text.Json.Serialization;
using Seam.Http;
using Seam.Models;

namespace Seam.Routes
{
    public sealed class ConnectedAccountsSimulate
    {
        private readonly SeamHttpTransport _transport;
        private readonly ActionAttemptWait _waitForActionAttemptDefault;

        internal ConnectedAccountsSimulate(
            SeamHttpTransport transport,
            ActionAttemptWait waitForActionAttemptDefault
        )
        {
            _transport = transport;
            _waitForActionAttemptDefault = waitForActionAttemptDefault;
        }

        /// <summary>
        /// Request parameters for Simulate Connected Account Disconnection.
        /// </summary>
        public sealed record DisconnectRequest
        {
            /// <summary>
            /// ID of the connected account you want to simulate as disconnected.
            /// </summary>
            [JsonPropertyName("connected_account_id")]
            public required string ConnectedAccountId { get; init; }
        }

        /// <summary>
        /// Simulates a connected account becoming disconnected from Seam. Only applicable for [sandbox workspaces](https://docs.seam.co/core-concepts/workspaces#sandbox-workspaces).
        /// </summary>
        public async Task DisconnectAsync(
            DisconnectRequest request,
            CancellationToken cancellationToken = default
        )
        {
            await _transport
                .SendAsync(
                    HttpMethod.Post,
                    "/connected_accounts/simulate/disconnect",
                    request,
                    cancellationToken
                )
                .ConfigureAwait(false);
        }
    }
}
