// <auto-generated>
//   Generated by codegen/smith.ts from @seamapi/types. Do not edit.
// </auto-generated>
#nullable enable
#pragma warning disable CS0618 // The generated code references its own deprecated members.
using System.Runtime.Serialization;
using System.Text.Json;
using System.Text.Json.Serialization;
using Seam.Http;
using Seam.Models;

namespace Seam.Routes
{
    public sealed class Events
    {
        private readonly SeamHttpTransport _transport;
        private readonly ActionAttemptWait _waitForActionAttemptDefault;

        internal Events(SeamHttpTransport transport, ActionAttemptWait waitForActionAttemptDefault)
        {
            _transport = transport;
            _waitForActionAttemptDefault = waitForActionAttemptDefault;
        }

        /// <summary>
        /// Request parameters for Get an Event.
        /// </summary>
        public sealed record GetRequest
        {
            /// <summary>
            /// Unique identifier for the device that triggered the event that you want to get.
            /// </summary>
            [JsonPropertyName("device_id")]
            public string? DeviceId { get; init; }

            /// <summary>
            /// Unique identifier for the event that you want to get.
            /// </summary>
            [JsonPropertyName("event_id")]
            public string? EventId { get; init; }

            /// <summary>
            /// Type of the event that you want to get.
            /// </summary>
            [JsonPropertyName("event_type")]
            public string? EventType { get; init; }

            internal void Validate()
            {
                if (DeviceId == null && EventId == null && EventType == null)
                {
                    throw new ArgumentException(
                        "At least one parameter is required for /events/get"
                    );
                }
            }
        }

        public sealed record GetResponse
        {
            /// <summary>
            /// OK
            /// </summary>
            [JsonPropertyName("event")]
            public Event? Event { get; init; }
        }

        /// <summary>
        /// Returns a specified event. This endpoint returns the same event that would be sent to a [webhook](https://docs.seam.co/developer-tools/webhooks), but it enables you to retrieve an event that already took place.
        /// </summary>
        public async Task<Event> GetAsync(
            GetRequest request,
            CancellationToken cancellationToken = default
        )
        {
            request.Validate();
            var response = await _transport
                .SendAsync<GetResponse>(
                    HttpMethod.Get,
                    "/events/get",
                    request,
                    "event",
                    cancellationToken
                )
                .ConfigureAwait(false);
            return response.Read(r => r.Event);
        }

        /// <summary>
        /// Request parameters for List Events.
        /// </summary>
        public sealed record ListRequest
        {
            /// <summary>
            /// Type of the events that you want to list.
            /// </summary>
            [JsonConverter(typeof(SeamStringEnumConverter))]
            public enum EventTypeEnum
            {
                [EnumMember(Value = "unrecognized")]
                Unrecognized = 0,

                [EnumMember(Value = "access_code.created")]
                AccessCodeCreated = 1,

                [EnumMember(Value = "access_code.changed")]
                AccessCodeChanged = 2,

                [EnumMember(Value = "access_code.name_changed")]
                AccessCodeNameChanged = 3,

                [EnumMember(Value = "access_code.code_changed")]
                AccessCodeCodeChanged = 4,

                [EnumMember(Value = "access_code.time_frame_changed")]
                AccessCodeTimeFrameChanged = 5,

                [EnumMember(Value = "access_code.mutations_requested")]
                AccessCodeMutationsRequested = 6,

                [EnumMember(Value = "access_code.scheduled_on_device")]
                AccessCodeScheduledOnDevice = 7,

                [EnumMember(Value = "access_code.set_on_device")]
                AccessCodeSetOnDevice = 8,

                [EnumMember(Value = "access_code.removed_from_device")]
                AccessCodeRemovedFromDevice = 9,

                [EnumMember(Value = "access_code.delay_in_setting_on_device")]
                AccessCodeDelayInSettingOnDevice = 10,

                [EnumMember(Value = "access_code.failed_to_set_on_device")]
                AccessCodeFailedToSetOnDevice = 11,

                [EnumMember(Value = "access_code.issued")]
                AccessCodeIssued = 12,

                [EnumMember(Value = "access_code.delay_in_issuing")]
                AccessCodeDelayInIssuing = 13,

                [EnumMember(Value = "access_code.failed_to_issue")]
                AccessCodeFailedToIssue = 14,

                [EnumMember(Value = "access_code.delay_in_applying_mutations")]
                AccessCodeDelayInApplyingMutations = 15,

                [EnumMember(Value = "access_code.failed_to_apply_mutations")]
                AccessCodeFailedToApplyMutations = 16,

                [EnumMember(Value = "access_code.failed_to_expire")]
                AccessCodeFailedToExpire = 17,

                [EnumMember(Value = "access_code.deleted")]
                AccessCodeDeleted = 18,

                [EnumMember(Value = "access_code.delay_in_removing_from_device")]
                AccessCodeDelayInRemovingFromDevice = 19,

                [EnumMember(Value = "access_code.failed_to_remove_from_device")]
                AccessCodeFailedToRemoveFromDevice = 20,

                [EnumMember(Value = "access_code.modified_external_to_seam")]
                AccessCodeModifiedExternalToSeam = 21,

                [EnumMember(Value = "access_code.deleted_external_to_seam")]
                AccessCodeDeletedExternalToSeam = 22,

                [EnumMember(Value = "access_code.backup_access_code_pulled")]
                AccessCodeBackupAccessCodePulled = 23,

                [EnumMember(Value = "access_code.unmanaged.converted_to_managed")]
                AccessCodeUnmanagedConvertedToManaged = 24,

                [EnumMember(Value = "access_code.unmanaged.failed_to_convert_to_managed")]
                AccessCodeUnmanagedFailedToConvertToManaged = 25,

                [EnumMember(Value = "access_code.unmanaged.created")]
                AccessCodeUnmanagedCreated = 26,

                [EnumMember(Value = "access_code.unmanaged.removed")]
                AccessCodeUnmanagedRemoved = 27,

                [EnumMember(Value = "access_grant.created")]
                AccessGrantCreated = 28,

                [EnumMember(Value = "access_grant.deleted")]
                AccessGrantDeleted = 29,

                [EnumMember(Value = "access_grant.access_granted_to_all_doors")]
                AccessGrantAccessGrantedToAllDoors = 30,

                [EnumMember(Value = "access_grant.access_granted_to_door")]
                AccessGrantAccessGrantedToDoor = 31,

                [EnumMember(Value = "access_grant.access_to_door_lost")]
                AccessGrantAccessToDoorLost = 32,

                [EnumMember(Value = "access_grant.access_times_changed")]
                AccessGrantAccessTimesChanged = 33,

                [EnumMember(Value = "access_grant.could_not_create_requested_access_methods")]
                AccessGrantCouldNotCreateRequestedAccessMethods = 34,

                [EnumMember(Value = "access_method.issued")]
                AccessMethodIssued = 35,

                [EnumMember(Value = "access_method.revoked")]
                AccessMethodRevoked = 36,

                [EnumMember(Value = "access_method.card_encoding_required")]
                AccessMethodCardEncodingRequired = 37,

                [EnumMember(Value = "access_method.deleted")]
                AccessMethodDeleted = 38,

                [EnumMember(Value = "access_method.reissued")]
                AccessMethodReissued = 39,

                [EnumMember(Value = "access_method.created")]
                AccessMethodCreated = 40,

                [EnumMember(Value = "access_method.delay_in_issuing")]
                AccessMethodDelayInIssuing = 41,

                [EnumMember(Value = "access_method.failed_to_issue")]
                AccessMethodFailedToIssue = 42,

                [EnumMember(Value = "acs_system.connected")]
                AcsSystemConnected = 43,

                [EnumMember(Value = "acs_system.added")]
                AcsSystemAdded = 44,

                [EnumMember(Value = "acs_system.disconnected")]
                AcsSystemDisconnected = 45,

                [EnumMember(Value = "acs_credential.deleted")]
                AcsCredentialDeleted = 46,

                [EnumMember(Value = "acs_credential.issued")]
                AcsCredentialIssued = 47,

                [EnumMember(Value = "acs_credential.reissued")]
                AcsCredentialReissued = 48,

                [EnumMember(Value = "acs_credential.invalidated")]
                AcsCredentialInvalidated = 49,

                [EnumMember(Value = "acs_user.created")]
                AcsUserCreated = 50,

                [EnumMember(Value = "acs_user.deleted")]
                AcsUserDeleted = 51,

                [EnumMember(Value = "acs_encoder.added")]
                AcsEncoderAdded = 52,

                [EnumMember(Value = "acs_encoder.removed")]
                AcsEncoderRemoved = 53,

                [EnumMember(Value = "acs_access_group.deleted")]
                AcsAccessGroupDeleted = 54,

                [EnumMember(Value = "acs_entrance.added")]
                AcsEntranceAdded = 55,

                [EnumMember(Value = "acs_entrance.removed")]
                AcsEntranceRemoved = 56,

                [EnumMember(Value = "client_session.deleted")]
                ClientSessionDeleted = 57,

                [EnumMember(Value = "connected_account.connected")]
                ConnectedAccountConnected = 58,

                [EnumMember(Value = "connected_account.created")]
                ConnectedAccountCreated = 59,

                [EnumMember(Value = "connected_account.successful_login")]
                ConnectedAccountSuccessfulLogin = 60,

                [EnumMember(Value = "connected_account.disconnected")]
                ConnectedAccountDisconnected = 61,

                [EnumMember(Value = "connected_account.completed_first_sync")]
                ConnectedAccountCompletedFirstSync = 62,

                [EnumMember(Value = "connected_account.deleted")]
                ConnectedAccountDeleted = 63,

                [EnumMember(Value = "connected_account.completed_first_sync_after_reconnection")]
                ConnectedAccountCompletedFirstSyncAfterReconnection = 64,

                [EnumMember(Value = "connected_account.reauthorization_requested")]
                ConnectedAccountReauthorizationRequested = 65,

                [EnumMember(Value = "action_attempt.lock_door.succeeded")]
                ActionAttemptLockDoorSucceeded = 66,

                [EnumMember(Value = "action_attempt.lock_door.failed")]
                ActionAttemptLockDoorFailed = 67,

                [EnumMember(Value = "action_attempt.unlock_door.succeeded")]
                ActionAttemptUnlockDoorSucceeded = 68,

                [EnumMember(Value = "action_attempt.unlock_door.failed")]
                ActionAttemptUnlockDoorFailed = 69,

                [EnumMember(Value = "action_attempt.simulate_keypad_code_entry.succeeded")]
                ActionAttemptSimulateKeypadCodeEntrySucceeded = 70,

                [EnumMember(Value = "action_attempt.simulate_keypad_code_entry.failed")]
                ActionAttemptSimulateKeypadCodeEntryFailed = 71,

                [EnumMember(Value = "action_attempt.simulate_manual_lock_via_keypad.succeeded")]
                ActionAttemptSimulateManualLockViaKeypadSucceeded = 72,

                [EnumMember(Value = "action_attempt.simulate_manual_lock_via_keypad.failed")]
                ActionAttemptSimulateManualLockViaKeypadFailed = 73,

                [EnumMember(Value = "connect_webview.login_succeeded")]
                ConnectWebviewLoginSucceeded = 74,

                [EnumMember(Value = "connect_webview.login_failed")]
                ConnectWebviewLoginFailed = 75,

                [EnumMember(Value = "device.connected")]
                DeviceConnected = 76,

                [EnumMember(Value = "device.added")]
                DeviceAdded = 77,

                [EnumMember(Value = "device.converted_to_unmanaged")]
                DeviceConvertedToUnmanaged = 78,

                [EnumMember(Value = "device.unmanaged.converted_to_managed")]
                DeviceUnmanagedConvertedToManaged = 79,

                [EnumMember(Value = "device.unmanaged.connected")]
                DeviceUnmanagedConnected = 80,

                [EnumMember(Value = "device.disconnected")]
                DeviceDisconnected = 81,

                [EnumMember(Value = "device.unmanaged.disconnected")]
                DeviceUnmanagedDisconnected = 82,

                [EnumMember(Value = "device.tampered")]
                DeviceTampered = 83,

                [EnumMember(Value = "device.low_battery")]
                DeviceLowBattery = 84,

                [EnumMember(Value = "device.battery_status_changed")]
                DeviceBatteryStatusChanged = 85,

                [EnumMember(Value = "device.removed")]
                DeviceRemoved = 86,

                [EnumMember(Value = "device.deleted")]
                DeviceDeleted = 87,

                [EnumMember(Value = "device.third_party_integration_detected")]
                DeviceThirdPartyIntegrationDetected = 88,

                [EnumMember(Value = "device.third_party_integration_no_longer_detected")]
                DeviceThirdPartyIntegrationNoLongerDetected = 89,

                [EnumMember(Value = "device.salto.privacy_mode_activated")]
                DeviceSaltoPrivacyModeActivated = 90,

                [EnumMember(Value = "device.salto.privacy_mode_deactivated")]
                DeviceSaltoPrivacyModeDeactivated = 91,

                [EnumMember(Value = "device.connection_became_flaky")]
                DeviceConnectionBecameFlaky = 92,

                [EnumMember(Value = "device.connection_stabilized")]
                DeviceConnectionStabilized = 93,

                [EnumMember(Value = "device.error.subscription_required")]
                DeviceErrorSubscriptionRequired = 94,

                [EnumMember(Value = "device.error.subscription_required.resolved")]
                DeviceErrorSubscriptionRequiredResolved = 95,

                [EnumMember(Value = "device.accessory_keypad_connected")]
                DeviceAccessoryKeypadConnected = 96,

                [EnumMember(Value = "device.accessory_keypad_disconnected")]
                DeviceAccessoryKeypadDisconnected = 97,

                [EnumMember(Value = "noise_sensor.noise_threshold_triggered")]
                NoiseSensorNoiseThresholdTriggered = 98,

                [EnumMember(Value = "lock.locked")]
                LockLocked = 99,

                [EnumMember(Value = "lock.unlocked")]
                LockUnlocked = 100,

                [EnumMember(Value = "lock.access_denied")]
                LockAccessDenied = 101,

                [EnumMember(Value = "thermostat.climate_preset_activated")]
                ThermostatClimatePresetActivated = 102,

                [EnumMember(Value = "thermostat.manually_adjusted")]
                ThermostatManuallyAdjusted = 103,

                [EnumMember(Value = "thermostat.temperature_threshold_exceeded")]
                ThermostatTemperatureThresholdExceeded = 104,

                [EnumMember(Value = "thermostat.temperature_threshold_no_longer_exceeded")]
                ThermostatTemperatureThresholdNoLongerExceeded = 105,

                [EnumMember(Value = "thermostat.temperature_reached_set_point")]
                ThermostatTemperatureReachedSetPoint = 106,

                [EnumMember(Value = "thermostat.temperature_changed")]
                ThermostatTemperatureChanged = 107,

                [EnumMember(Value = "device.name_changed")]
                DeviceNameChanged = 108,

                [EnumMember(Value = "camera.activated")]
                CameraActivated = 109,

                [EnumMember(Value = "device.doorbell_rang")]
                DeviceDoorbellRang = 110,

                [EnumMember(Value = "enrollment_automation.deleted")]
                EnrollmentAutomationDeleted = 111,

                [EnumMember(Value = "phone.deactivated")]
                PhoneDeactivated = 112,

                [EnumMember(Value = "space.device_membership_changed")]
                SpaceDeviceMembershipChanged = 113,

                [EnumMember(Value = "space.created")]
                SpaceCreated = 114,

                [EnumMember(Value = "space.deleted")]
                SpaceDeleted = 115,
            }

            /// <summary>
            /// Types of the events that you want to list.
            /// </summary>
            [JsonConverter(typeof(SeamStringEnumConverter))]
            public enum EventTypesEnum
            {
                [EnumMember(Value = "unrecognized")]
                Unrecognized = 0,

                [EnumMember(Value = "access_code.created")]
                AccessCodeCreated = 1,

                [EnumMember(Value = "access_code.changed")]
                AccessCodeChanged = 2,

                [EnumMember(Value = "access_code.name_changed")]
                AccessCodeNameChanged = 3,

                [EnumMember(Value = "access_code.code_changed")]
                AccessCodeCodeChanged = 4,

                [EnumMember(Value = "access_code.time_frame_changed")]
                AccessCodeTimeFrameChanged = 5,

                [EnumMember(Value = "access_code.mutations_requested")]
                AccessCodeMutationsRequested = 6,

                [EnumMember(Value = "access_code.scheduled_on_device")]
                AccessCodeScheduledOnDevice = 7,

                [EnumMember(Value = "access_code.set_on_device")]
                AccessCodeSetOnDevice = 8,

                [EnumMember(Value = "access_code.removed_from_device")]
                AccessCodeRemovedFromDevice = 9,

                [EnumMember(Value = "access_code.delay_in_setting_on_device")]
                AccessCodeDelayInSettingOnDevice = 10,

                [EnumMember(Value = "access_code.failed_to_set_on_device")]
                AccessCodeFailedToSetOnDevice = 11,

                [EnumMember(Value = "access_code.issued")]
                AccessCodeIssued = 12,

                [EnumMember(Value = "access_code.delay_in_issuing")]
                AccessCodeDelayInIssuing = 13,

                [EnumMember(Value = "access_code.failed_to_issue")]
                AccessCodeFailedToIssue = 14,

                [EnumMember(Value = "access_code.delay_in_applying_mutations")]
                AccessCodeDelayInApplyingMutations = 15,

                [EnumMember(Value = "access_code.failed_to_apply_mutations")]
                AccessCodeFailedToApplyMutations = 16,

                [EnumMember(Value = "access_code.failed_to_expire")]
                AccessCodeFailedToExpire = 17,

                [EnumMember(Value = "access_code.deleted")]
                AccessCodeDeleted = 18,

                [EnumMember(Value = "access_code.delay_in_removing_from_device")]
                AccessCodeDelayInRemovingFromDevice = 19,

                [EnumMember(Value = "access_code.failed_to_remove_from_device")]
                AccessCodeFailedToRemoveFromDevice = 20,

                [EnumMember(Value = "access_code.modified_external_to_seam")]
                AccessCodeModifiedExternalToSeam = 21,

                [EnumMember(Value = "access_code.deleted_external_to_seam")]
                AccessCodeDeletedExternalToSeam = 22,

                [EnumMember(Value = "access_code.backup_access_code_pulled")]
                AccessCodeBackupAccessCodePulled = 23,

                [EnumMember(Value = "access_code.unmanaged.converted_to_managed")]
                AccessCodeUnmanagedConvertedToManaged = 24,

                [EnumMember(Value = "access_code.unmanaged.failed_to_convert_to_managed")]
                AccessCodeUnmanagedFailedToConvertToManaged = 25,

                [EnumMember(Value = "access_code.unmanaged.created")]
                AccessCodeUnmanagedCreated = 26,

                [EnumMember(Value = "access_code.unmanaged.removed")]
                AccessCodeUnmanagedRemoved = 27,

                [EnumMember(Value = "access_grant.created")]
                AccessGrantCreated = 28,

                [EnumMember(Value = "access_grant.deleted")]
                AccessGrantDeleted = 29,

                [EnumMember(Value = "access_grant.access_granted_to_all_doors")]
                AccessGrantAccessGrantedToAllDoors = 30,

                [EnumMember(Value = "access_grant.access_granted_to_door")]
                AccessGrantAccessGrantedToDoor = 31,

                [EnumMember(Value = "access_grant.access_to_door_lost")]
                AccessGrantAccessToDoorLost = 32,

                [EnumMember(Value = "access_grant.access_times_changed")]
                AccessGrantAccessTimesChanged = 33,

                [EnumMember(Value = "access_grant.could_not_create_requested_access_methods")]
                AccessGrantCouldNotCreateRequestedAccessMethods = 34,

                [EnumMember(Value = "access_method.issued")]
                AccessMethodIssued = 35,

                [EnumMember(Value = "access_method.revoked")]
                AccessMethodRevoked = 36,

                [EnumMember(Value = "access_method.card_encoding_required")]
                AccessMethodCardEncodingRequired = 37,

                [EnumMember(Value = "access_method.deleted")]
                AccessMethodDeleted = 38,

                [EnumMember(Value = "access_method.reissued")]
                AccessMethodReissued = 39,

                [EnumMember(Value = "access_method.created")]
                AccessMethodCreated = 40,

                [EnumMember(Value = "access_method.delay_in_issuing")]
                AccessMethodDelayInIssuing = 41,

                [EnumMember(Value = "access_method.failed_to_issue")]
                AccessMethodFailedToIssue = 42,

                [EnumMember(Value = "acs_system.connected")]
                AcsSystemConnected = 43,

                [EnumMember(Value = "acs_system.added")]
                AcsSystemAdded = 44,

                [EnumMember(Value = "acs_system.disconnected")]
                AcsSystemDisconnected = 45,

                [EnumMember(Value = "acs_credential.deleted")]
                AcsCredentialDeleted = 46,

                [EnumMember(Value = "acs_credential.issued")]
                AcsCredentialIssued = 47,

                [EnumMember(Value = "acs_credential.reissued")]
                AcsCredentialReissued = 48,

                [EnumMember(Value = "acs_credential.invalidated")]
                AcsCredentialInvalidated = 49,

                [EnumMember(Value = "acs_user.created")]
                AcsUserCreated = 50,

                [EnumMember(Value = "acs_user.deleted")]
                AcsUserDeleted = 51,

                [EnumMember(Value = "acs_encoder.added")]
                AcsEncoderAdded = 52,

                [EnumMember(Value = "acs_encoder.removed")]
                AcsEncoderRemoved = 53,

                [EnumMember(Value = "acs_access_group.deleted")]
                AcsAccessGroupDeleted = 54,

                [EnumMember(Value = "acs_entrance.added")]
                AcsEntranceAdded = 55,

                [EnumMember(Value = "acs_entrance.removed")]
                AcsEntranceRemoved = 56,

                [EnumMember(Value = "client_session.deleted")]
                ClientSessionDeleted = 57,

                [EnumMember(Value = "connected_account.connected")]
                ConnectedAccountConnected = 58,

                [EnumMember(Value = "connected_account.created")]
                ConnectedAccountCreated = 59,

                [EnumMember(Value = "connected_account.successful_login")]
                ConnectedAccountSuccessfulLogin = 60,

                [EnumMember(Value = "connected_account.disconnected")]
                ConnectedAccountDisconnected = 61,

                [EnumMember(Value = "connected_account.completed_first_sync")]
                ConnectedAccountCompletedFirstSync = 62,

                [EnumMember(Value = "connected_account.deleted")]
                ConnectedAccountDeleted = 63,

                [EnumMember(Value = "connected_account.completed_first_sync_after_reconnection")]
                ConnectedAccountCompletedFirstSyncAfterReconnection = 64,

                [EnumMember(Value = "connected_account.reauthorization_requested")]
                ConnectedAccountReauthorizationRequested = 65,

                [EnumMember(Value = "action_attempt.lock_door.succeeded")]
                ActionAttemptLockDoorSucceeded = 66,

                [EnumMember(Value = "action_attempt.lock_door.failed")]
                ActionAttemptLockDoorFailed = 67,

                [EnumMember(Value = "action_attempt.unlock_door.succeeded")]
                ActionAttemptUnlockDoorSucceeded = 68,

                [EnumMember(Value = "action_attempt.unlock_door.failed")]
                ActionAttemptUnlockDoorFailed = 69,

                [EnumMember(Value = "action_attempt.simulate_keypad_code_entry.succeeded")]
                ActionAttemptSimulateKeypadCodeEntrySucceeded = 70,

                [EnumMember(Value = "action_attempt.simulate_keypad_code_entry.failed")]
                ActionAttemptSimulateKeypadCodeEntryFailed = 71,

                [EnumMember(Value = "action_attempt.simulate_manual_lock_via_keypad.succeeded")]
                ActionAttemptSimulateManualLockViaKeypadSucceeded = 72,

                [EnumMember(Value = "action_attempt.simulate_manual_lock_via_keypad.failed")]
                ActionAttemptSimulateManualLockViaKeypadFailed = 73,

                [EnumMember(Value = "connect_webview.login_succeeded")]
                ConnectWebviewLoginSucceeded = 74,

                [EnumMember(Value = "connect_webview.login_failed")]
                ConnectWebviewLoginFailed = 75,

                [EnumMember(Value = "device.connected")]
                DeviceConnected = 76,

                [EnumMember(Value = "device.added")]
                DeviceAdded = 77,

                [EnumMember(Value = "device.converted_to_unmanaged")]
                DeviceConvertedToUnmanaged = 78,

                [EnumMember(Value = "device.unmanaged.converted_to_managed")]
                DeviceUnmanagedConvertedToManaged = 79,

                [EnumMember(Value = "device.unmanaged.connected")]
                DeviceUnmanagedConnected = 80,

                [EnumMember(Value = "device.disconnected")]
                DeviceDisconnected = 81,

                [EnumMember(Value = "device.unmanaged.disconnected")]
                DeviceUnmanagedDisconnected = 82,

                [EnumMember(Value = "device.tampered")]
                DeviceTampered = 83,

                [EnumMember(Value = "device.low_battery")]
                DeviceLowBattery = 84,

                [EnumMember(Value = "device.battery_status_changed")]
                DeviceBatteryStatusChanged = 85,

                [EnumMember(Value = "device.removed")]
                DeviceRemoved = 86,

                [EnumMember(Value = "device.deleted")]
                DeviceDeleted = 87,

                [EnumMember(Value = "device.third_party_integration_detected")]
                DeviceThirdPartyIntegrationDetected = 88,

                [EnumMember(Value = "device.third_party_integration_no_longer_detected")]
                DeviceThirdPartyIntegrationNoLongerDetected = 89,

                [EnumMember(Value = "device.salto.privacy_mode_activated")]
                DeviceSaltoPrivacyModeActivated = 90,

                [EnumMember(Value = "device.salto.privacy_mode_deactivated")]
                DeviceSaltoPrivacyModeDeactivated = 91,

                [EnumMember(Value = "device.connection_became_flaky")]
                DeviceConnectionBecameFlaky = 92,

                [EnumMember(Value = "device.connection_stabilized")]
                DeviceConnectionStabilized = 93,

                [EnumMember(Value = "device.error.subscription_required")]
                DeviceErrorSubscriptionRequired = 94,

                [EnumMember(Value = "device.error.subscription_required.resolved")]
                DeviceErrorSubscriptionRequiredResolved = 95,

                [EnumMember(Value = "device.accessory_keypad_connected")]
                DeviceAccessoryKeypadConnected = 96,

                [EnumMember(Value = "device.accessory_keypad_disconnected")]
                DeviceAccessoryKeypadDisconnected = 97,

                [EnumMember(Value = "noise_sensor.noise_threshold_triggered")]
                NoiseSensorNoiseThresholdTriggered = 98,

                [EnumMember(Value = "lock.locked")]
                LockLocked = 99,

                [EnumMember(Value = "lock.unlocked")]
                LockUnlocked = 100,

                [EnumMember(Value = "lock.access_denied")]
                LockAccessDenied = 101,

                [EnumMember(Value = "thermostat.climate_preset_activated")]
                ThermostatClimatePresetActivated = 102,

                [EnumMember(Value = "thermostat.manually_adjusted")]
                ThermostatManuallyAdjusted = 103,

                [EnumMember(Value = "thermostat.temperature_threshold_exceeded")]
                ThermostatTemperatureThresholdExceeded = 104,

                [EnumMember(Value = "thermostat.temperature_threshold_no_longer_exceeded")]
                ThermostatTemperatureThresholdNoLongerExceeded = 105,

                [EnumMember(Value = "thermostat.temperature_reached_set_point")]
                ThermostatTemperatureReachedSetPoint = 106,

                [EnumMember(Value = "thermostat.temperature_changed")]
                ThermostatTemperatureChanged = 107,

                [EnumMember(Value = "device.name_changed")]
                DeviceNameChanged = 108,

                [EnumMember(Value = "camera.activated")]
                CameraActivated = 109,

                [EnumMember(Value = "device.doorbell_rang")]
                DeviceDoorbellRang = 110,

                [EnumMember(Value = "enrollment_automation.deleted")]
                EnrollmentAutomationDeleted = 111,

                [EnumMember(Value = "phone.deactivated")]
                PhoneDeactivated = 112,

                [EnumMember(Value = "space.device_membership_changed")]
                SpaceDeviceMembershipChanged = 113,

                [EnumMember(Value = "space.created")]
                SpaceCreated = 114,

                [EnumMember(Value = "space.deleted")]
                SpaceDeleted = 115,
            }

            /// <summary>
            /// ID of the access code for which you want to list events.
            /// </summary>
            [JsonPropertyName("access_code_id")]
            public string? AccessCodeId { get; init; }

            /// <summary>
            /// IDs of the access codes for which you want to list events.
            /// </summary>
            [JsonPropertyName("access_code_ids")]
            public List<string>? AccessCodeIds { get; init; }

            /// <summary>
            /// ID of the access grant for which you want to list events.
            /// </summary>
            [JsonPropertyName("access_grant_id")]
            public string? AccessGrantId { get; init; }

            /// <summary>
            /// IDs of the access grants for which you want to list events.
            /// </summary>
            [JsonPropertyName("access_grant_ids")]
            public List<string>? AccessGrantIds { get; init; }

            /// <summary>
            /// ID of the access method for which you want to list events.
            /// </summary>
            [JsonPropertyName("access_method_id")]
            public string? AccessMethodId { get; init; }

            /// <summary>
            /// IDs of the access methods for which you want to list events.
            /// </summary>
            [JsonPropertyName("access_method_ids")]
            public List<string>? AccessMethodIds { get; init; }

            /// <summary>
            /// ID of the ACS access group for which you want to list events.
            /// </summary>
            [JsonPropertyName("acs_access_group_id")]
            public string? AcsAccessGroupId { get; init; }

            /// <summary>
            /// ID of the ACS credential for which you want to list events.
            /// </summary>
            [JsonPropertyName("acs_credential_id")]
            public string? AcsCredentialId { get; init; }

            /// <summary>
            /// ID of the ACS encoder for which you want to list events.
            /// </summary>
            [JsonPropertyName("acs_encoder_id")]
            public string? AcsEncoderId { get; init; }

            /// <summary>
            /// ID of the ACS entrance for which you want to list events.
            /// </summary>
            [JsonPropertyName("acs_entrance_id")]
            public string? AcsEntranceId { get; init; }

            /// <summary>
            /// ID of the access system for which you want to list events.
            /// </summary>
            [JsonPropertyName("acs_system_id")]
            public string? AcsSystemId { get; init; }

            /// <summary>
            /// IDs of the access systems for which you want to list events.
            /// </summary>
            [JsonPropertyName("acs_system_ids")]
            public List<string>? AcsSystemIds { get; init; }

            /// <summary>
            /// ID of the ACS user for which you want to list events.
            /// </summary>
            [JsonPropertyName("acs_user_id")]
            public string? AcsUserId { get; init; }

            /// <summary>
            /// Lower and upper timestamps to define an exclusive interval containing the events that you want to list. You must include `since` or `between`.
            /// </summary>
            [JsonPropertyName("between")]
            public List<string>? Between { get; init; }

            /// <summary>
            /// ID of the Connect Webview for which you want to list events.
            /// </summary>
            [JsonPropertyName("connect_webview_id")]
            public string? ConnectWebviewId { get; init; }

            /// <summary>
            /// ID of the connected account for which you want to list events.
            /// </summary>
            [JsonPropertyName("connected_account_id")]
            public string? ConnectedAccountId { get; init; }

            /// <summary>
            /// Customer key for which you want to list events.
            /// </summary>
            [JsonPropertyName("customer_key")]
            public string? CustomerKey { get; init; }

            /// <summary>
            /// ID of the device for which you want to list events.
            /// </summary>
            [JsonPropertyName("device_id")]
            public string? DeviceId { get; init; }

            /// <summary>
            /// IDs of the devices for which you want to list events.
            /// </summary>
            [JsonPropertyName("device_ids")]
            public List<string>? DeviceIds { get; init; }

            /// <summary>
            /// IDs of the events that you want to list.
            /// </summary>
            [JsonPropertyName("event_ids")]
            public List<string>? EventIds { get; init; }

            /// <summary>
            /// Type of the events that you want to list.
            /// </summary>
            [JsonPropertyName("event_type")]
            public ListRequest.EventTypeEnum? EventType { get; init; }

            /// <summary>
            /// Types of the events that you want to list.
            /// </summary>
            [JsonPropertyName("event_types")]
            public List<ListRequest.EventTypesEnum>? EventTypes { get; init; }

            /// <summary>
            /// Numerical limit on the number of events to return.
            /// </summary>
            [JsonPropertyName("limit")]
            public float? Limit { get; init; }

            /// <summary>
            /// Timestamp to indicate the beginning generation time for the events that you want to list. You must include `since` or `between`.
            /// </summary>
            [JsonPropertyName("since")]
            public string? Since { get; init; }

            /// <summary>
            /// ID of the space for which you want to list events.
            /// </summary>
            [JsonPropertyName("space_id")]
            public string? SpaceId { get; init; }

            /// <summary>
            /// IDs of the spaces for which you want to list events.
            /// </summary>
            [JsonPropertyName("space_ids")]
            public List<string>? SpaceIds { get; init; }

            /// <summary>
            /// Offset for the events that you want to list.
            /// </summary>
            [JsonPropertyName("unstable_offset")]
            public float? UnstableOffset { get; init; }

            /// <summary>
            /// ID of the user identity for which you want to list events.
            /// </summary>
            [JsonPropertyName("user_identity_id")]
            public string? UserIdentityId { get; init; }

            internal void Validate()
            {
                if (
                    AccessCodeId == null
                    && AccessCodeIds == null
                    && AccessGrantId == null
                    && AccessGrantIds == null
                    && AccessMethodId == null
                    && AccessMethodIds == null
                    && AcsAccessGroupId == null
                    && AcsCredentialId == null
                    && AcsEncoderId == null
                    && AcsEntranceId == null
                    && AcsSystemId == null
                    && AcsSystemIds == null
                    && AcsUserId == null
                    && Between == null
                    && ConnectWebviewId == null
                    && ConnectedAccountId == null
                    && CustomerKey == null
                    && DeviceId == null
                    && DeviceIds == null
                    && EventIds == null
                    && EventType == null
                    && EventTypes == null
                    && Since == null
                    && SpaceId == null
                    && SpaceIds == null
                    && UnstableOffset == null
                    && UserIdentityId == null
                )
                {
                    throw new ArgumentException(
                        "At least one parameter is required for /events/list"
                    );
                }
            }
        }

        public sealed record ListResponse
        {
            /// <summary>
            /// OK
            /// </summary>
            [JsonPropertyName("events")]
            public List<Event>? Events { get; init; }
        }

        /// <summary>
        /// Returns a list of all events. This endpoint returns the same events that would be sent to a [webhook](https://docs.seam.co/developer-tools/webhooks), but it enables you to filter or see events that already took place.
        /// </summary>
        public async Task<List<Event>> ListAsync(
            ListRequest request,
            CancellationToken cancellationToken = default
        )
        {
            request.Validate();
            var response = await _transport
                .SendAsync<ListResponse>(
                    HttpMethod.Get,
                    "/events/list",
                    request,
                    "events",
                    cancellationToken
                )
                .ConfigureAwait(false);
            return response.Read(r => r.Events);
        }
    }
}
