// <auto-generated>
//   Generated by codegen/smith.ts from @seamapi/types. Do not edit.
// </auto-generated>
#nullable enable
#pragma warning disable CS0618 // The generated code references its own deprecated members.
using System.Runtime.Serialization;
using System.Text.Json;
using System.Text.Json.Serialization;
using Seam.Http;
using Seam.Models;

namespace Seam.Routes
{
    public sealed class InstantKeys
    {
        private readonly SeamHttpTransport _transport;
        private readonly ActionAttemptWait _waitForActionAttemptDefault;

        internal InstantKeys(
            SeamHttpTransport transport,
            ActionAttemptWait waitForActionAttemptDefault
        )
        {
            _transport = transport;
            _waitForActionAttemptDefault = waitForActionAttemptDefault;
        }

        /// <summary>
        /// Request parameters for Delete an Instant Key.
        /// </summary>
        public sealed record DeleteRequest
        {
            /// <summary>
            /// ID of the Instant Key that you want to delete.
            /// </summary>
            [JsonPropertyName("instant_key_id")]
            public required string InstantKeyId { get; init; }
        }

        /// <summary>
        /// Deletes a specified [Instant Key](https://docs.seam.co/capability-guides/instant-keys).
        /// </summary>
        public async Task DeleteAsync(
            DeleteRequest request,
            CancellationToken cancellationToken = default
        )
        {
            await _transport
                .SendAsync(HttpMethod.Delete, "/instant_keys/delete", request, cancellationToken)
                .ConfigureAwait(false);
        }

        /// <summary>
        /// Request parameters for Get an Instant Key.
        /// </summary>
        public sealed record GetRequest
        {
            /// <summary>
            /// ID of the instant key to get.
            /// </summary>
            [JsonPropertyName("instant_key_id")]
            public string? InstantKeyId { get; init; }

            /// <summary>
            /// URL of the instant key to get.
            /// </summary>
            [JsonPropertyName("instant_key_url")]
            public string? InstantKeyUrl { get; init; }

            internal void Validate()
            {
                if (InstantKeyId == null && InstantKeyUrl == null)
                {
                    throw new ArgumentException(
                        "At least one parameter is required for /instant_keys/get"
                    );
                }
            }
        }

        public sealed record GetResponse
        {
            /// <summary>
            /// OK
            /// </summary>
            [JsonPropertyName("instant_key")]
            public InstantKey? InstantKey { get; init; }
        }

        /// <summary>
        /// Gets an [instant key](https://docs.seam.co/capability-guides/instant-keys).
        /// </summary>
        public async Task<InstantKey> GetAsync(
            GetRequest request,
            CancellationToken cancellationToken = default
        )
        {
            request.Validate();
            var response = await _transport
                .SendAsync<GetResponse>(
                    HttpMethod.Get,
                    "/instant_keys/get",
                    request,
                    "instant_key",
                    cancellationToken
                )
                .ConfigureAwait(false);
            return response.Read(r => r.InstantKey);
        }

        /// <summary>
        /// Request parameters for List Instant Keys.
        /// </summary>
        public sealed record ListRequest
        {
            /// <summary>
            /// ID of the user identity by which you want to filter the list of Instant Keys.
            /// </summary>
            [JsonPropertyName("user_identity_id")]
            public string? UserIdentityId { get; init; }
        }

        public sealed record ListResponse
        {
            /// <summary>
            /// OK
            /// </summary>
            [JsonPropertyName("instant_keys")]
            public List<InstantKey>? InstantKeys { get; init; }
        }

        /// <summary>
        /// Returns a list of all [instant keys](https://docs.seam.co/capability-guides/instant-keys).
        /// </summary>
        public async Task<List<InstantKey>> ListAsync(
            ListRequest? request = null,
            CancellationToken cancellationToken = default
        )
        {
            var response = await _transport
                .SendAsync<ListResponse>(
                    HttpMethod.Get,
                    "/instant_keys/list",
                    request,
                    "instant_keys",
                    cancellationToken
                )
                .ConfigureAwait(false);
            return response.Read(r => r.InstantKeys);
        }
    }
}
