// <auto-generated>
//   Generated by codegen/smith.ts from @seamapi/types. Do not edit.
// </auto-generated>
#nullable enable
#pragma warning disable CS0618 // The generated code references its own deprecated members.
using System.Runtime.Serialization;
using System.Text.Json;
using System.Text.Json.Serialization;
using Seam.Http;
using Seam.Models;

namespace Seam.Routes
{
    public sealed class Locks
    {
        private readonly SeamHttpTransport _transport;
        private readonly ActionAttemptWait _waitForActionAttemptDefault;

        internal Locks(SeamHttpTransport transport, ActionAttemptWait waitForActionAttemptDefault)
        {
            _transport = transport;
            _waitForActionAttemptDefault = waitForActionAttemptDefault;
            Simulate = new LocksSimulate(transport, waitForActionAttemptDefault);
        }

        public LocksSimulate Simulate { get; }

        /// <summary>
        /// Request parameters for Configure Auto-Lock.
        /// </summary>
        public sealed record ConfigureAutoLockRequest
        {
            /// <summary>
            /// Delay in seconds before the lock automatically locks. Required when enabling auto-lock. Must be between 1 and 60.
            /// </summary>
            [JsonPropertyName("auto_lock_delay_seconds")]
            public float? AutoLockDelaySeconds { get; init; }

            /// <summary>
            /// Whether to enable or disable auto-lock.
            /// </summary>
            [JsonPropertyName("auto_lock_enabled")]
            public required bool AutoLockEnabled { get; init; }

            /// <summary>
            /// ID of the lock for which you want to configure the auto-lock.
            /// </summary>
            [JsonPropertyName("device_id")]
            public required string DeviceId { get; init; }
        }

        public sealed record ConfigureAutoLockResponse
        {
            /// <summary>
            /// OK
            /// </summary>
            [JsonPropertyName("action_attempt")]
            public ActionAttempt? ActionAttempt { get; init; }
        }

        /// <summary>
        /// Configures the auto-lock setting for a specified [lock](https://docs.seam.co/low-level-apis/smart-locks).
        /// </summary>
        public async Task<ActionAttempt> ConfigureAutoLockAsync(
            ConfigureAutoLockRequest request,
            ActionAttemptWait? waitForActionAttempt = null,
            CancellationToken cancellationToken = default
        )
        {
            var response = await _transport
                .SendAsync<ConfigureAutoLockResponse>(
                    HttpMethod.Post,
                    "/locks/configure_auto_lock",
                    request,
                    "action_attempt",
                    cancellationToken
                )
                .ConfigureAwait(false);
            var actionAttempt = response.Read(r => r.ActionAttempt);
            return await ActionAttemptResolver
                .ResolveAsync(
                    actionAttempt,
                    _transport,
                    waitForActionAttempt ?? _waitForActionAttemptDefault,
                    cancellationToken
                )
                .ConfigureAwait(false);
        }

        /// <summary>
        /// Request parameters for Get a Lock.
        /// </summary>
        [Obsolete("Use `/devices/get` instead.")]
        public sealed record GetRequest
        {
            /// <summary>
            /// ID of the lock that you want to get.
            /// </summary>
            [JsonPropertyName("device_id")]
            public string? DeviceId { get; init; }

            /// <summary>
            /// Name of the lock that you want to get.
            /// </summary>
            [JsonPropertyName("name")]
            public string? Name { get; init; }

            internal void Validate()
            {
                if (DeviceId == null && Name == null)
                {
                    throw new ArgumentException(
                        "At least one parameter is required for /locks/get"
                    );
                }
            }
        }

        public sealed record GetResponse
        {
            /// <summary>
            /// OK
            /// </summary>
            [JsonPropertyName("device")]
            public Device? Device { get; init; }
        }

        /// <summary>
        /// Returns a specified [lock](https://docs.seam.co/low-level-apis/smart-locks).
        /// </summary>
        [Obsolete("Use `/devices/get` instead.")]
        public async Task<Device> GetAsync(
            GetRequest request,
            CancellationToken cancellationToken = default
        )
        {
            request.Validate();
            var response = await _transport
                .SendAsync<GetResponse>(
                    HttpMethod.Get,
                    "/locks/get",
                    request,
                    "device",
                    cancellationToken
                )
                .ConfigureAwait(false);
            return response.Read(r => r.Device);
        }

        /// <summary>
        /// Request parameters for List Locks.
        /// </summary>
        public sealed record ListRequest
        {
            /// <summary>
            /// Device type of the locks that you want to list.
            /// </summary>
            [JsonConverter(typeof(SeamStringEnumConverter))]
            public enum DeviceTypeEnum
            {
                [EnumMember(Value = "unrecognized")]
                Unrecognized = 0,

                [EnumMember(Value = "akuvox_lock")]
                AkuvoxLock = 1,

                [EnumMember(Value = "august_lock")]
                AugustLock = 2,

                [EnumMember(Value = "brivo_access_point")]
                BrivoAccessPoint = 3,

                [EnumMember(Value = "butterflymx_panel")]
                ButterflymxPanel = 4,

                [EnumMember(Value = "avigilon_alta_entry")]
                AvigilonAltaEntry = 5,

                [EnumMember(Value = "doorking_lock")]
                DoorkingLock = 6,

                [EnumMember(Value = "genie_door")]
                GenieDoor = 7,

                [EnumMember(Value = "igloo_lock")]
                IglooLock = 8,

                [EnumMember(Value = "linear_lock")]
                LinearLock = 9,

                [EnumMember(Value = "lockly_lock")]
                LocklyLock = 10,

                [EnumMember(Value = "kwikset_lock")]
                KwiksetLock = 11,

                [EnumMember(Value = "nuki_lock")]
                NukiLock = 12,

                [EnumMember(Value = "salto_lock")]
                SaltoLock = 13,

                [EnumMember(Value = "schlage_lock")]
                SchlageLock = 14,

                [EnumMember(Value = "smartthings_lock")]
                SmartthingsLock = 15,

                [EnumMember(Value = "wyze_lock")]
                WyzeLock = 16,

                [EnumMember(Value = "yale_lock")]
                YaleLock = 17,

                [EnumMember(Value = "two_n_intercom")]
                TwoNIntercom = 18,

                [EnumMember(Value = "controlbyweb_device")]
                ControlbywebDevice = 19,

                [EnumMember(Value = "ttlock_lock")]
                TtlockLock = 20,

                [EnumMember(Value = "igloohome_lock")]
                IgloohomeLock = 21,

                [EnumMember(Value = "four_suites_door")]
                FourSuitesDoor = 22,

                [EnumMember(Value = "dormakaba_oracode_door")]
                DormakabaOracodeDoor = 23,

                [EnumMember(Value = "tedee_lock")]
                TedeeLock = 24,

                [EnumMember(Value = "akiles_lock")]
                AkilesLock = 25,

                [EnumMember(Value = "ultraloq_lock")]
                UltraloqLock = 26,

                [EnumMember(Value = "yacan_lock")]
                YacanLock = 27,

                [EnumMember(Value = "keyincode_lock")]
                KeyincodeLock = 28,

                [EnumMember(Value = "omnitec_lock")]
                OmnitecLock = 29,

                [EnumMember(Value = "kisi_lock")]
                KisiLock = 30,

                [EnumMember(Value = "aqara_lock")]
                AqaraLock = 31,
            }

            /// <summary>
            /// Device types of the locks that you want to list.
            /// </summary>
            [JsonConverter(typeof(SeamStringEnumConverter))]
            public enum DeviceTypesEnum
            {
                [EnumMember(Value = "unrecognized")]
                Unrecognized = 0,

                [EnumMember(Value = "akuvox_lock")]
                AkuvoxLock = 1,

                [EnumMember(Value = "august_lock")]
                AugustLock = 2,

                [EnumMember(Value = "brivo_access_point")]
                BrivoAccessPoint = 3,

                [EnumMember(Value = "butterflymx_panel")]
                ButterflymxPanel = 4,

                [EnumMember(Value = "avigilon_alta_entry")]
                AvigilonAltaEntry = 5,

                [EnumMember(Value = "doorking_lock")]
                DoorkingLock = 6,

                [EnumMember(Value = "genie_door")]
                GenieDoor = 7,

                [EnumMember(Value = "igloo_lock")]
                IglooLock = 8,

                [EnumMember(Value = "linear_lock")]
                LinearLock = 9,

                [EnumMember(Value = "lockly_lock")]
                LocklyLock = 10,

                [EnumMember(Value = "kwikset_lock")]
                KwiksetLock = 11,

                [EnumMember(Value = "nuki_lock")]
                NukiLock = 12,

                [EnumMember(Value = "salto_lock")]
                SaltoLock = 13,

                [EnumMember(Value = "schlage_lock")]
                SchlageLock = 14,

                [EnumMember(Value = "smartthings_lock")]
                SmartthingsLock = 15,

                [EnumMember(Value = "wyze_lock")]
                WyzeLock = 16,

                [EnumMember(Value = "yale_lock")]
                YaleLock = 17,

                [EnumMember(Value = "two_n_intercom")]
                TwoNIntercom = 18,

                [EnumMember(Value = "controlbyweb_device")]
                ControlbywebDevice = 19,

                [EnumMember(Value = "ttlock_lock")]
                TtlockLock = 20,

                [EnumMember(Value = "igloohome_lock")]
                IgloohomeLock = 21,

                [EnumMember(Value = "four_suites_door")]
                FourSuitesDoor = 22,

                [EnumMember(Value = "dormakaba_oracode_door")]
                DormakabaOracodeDoor = 23,

                [EnumMember(Value = "tedee_lock")]
                TedeeLock = 24,

                [EnumMember(Value = "akiles_lock")]
                AkilesLock = 25,

                [EnumMember(Value = "ultraloq_lock")]
                UltraloqLock = 26,

                [EnumMember(Value = "yacan_lock")]
                YacanLock = 27,

                [EnumMember(Value = "keyincode_lock")]
                KeyincodeLock = 28,

                [EnumMember(Value = "omnitec_lock")]
                OmnitecLock = 29,

                [EnumMember(Value = "kisi_lock")]
                KisiLock = 30,

                [EnumMember(Value = "aqara_lock")]
                AqaraLock = 31,
            }

            /// <summary>
            /// Manufacturer of the locks that you want to list.
            /// </summary>
            [JsonConverter(typeof(SeamStringEnumConverter))]
            public enum ManufacturerEnum
            {
                [EnumMember(Value = "unrecognized")]
                Unrecognized = 0,

                [EnumMember(Value = "akuvox")]
                Akuvox = 1,

                [EnumMember(Value = "august")]
                August = 2,

                [EnumMember(Value = "brivo")]
                Brivo = 3,

                [EnumMember(Value = "butterflymx")]
                Butterflymx = 4,

                [EnumMember(Value = "avigilon_alta")]
                AvigilonAlta = 5,

                [EnumMember(Value = "doorking")]
                Doorking = 6,

                [EnumMember(Value = "genie")]
                Genie = 7,

                [EnumMember(Value = "igloo")]
                Igloo = 8,

                [EnumMember(Value = "linear")]
                Linear = 9,

                [EnumMember(Value = "lockly")]
                Lockly = 10,

                [EnumMember(Value = "kwikset")]
                Kwikset = 11,

                [EnumMember(Value = "nuki")]
                Nuki = 12,

                [EnumMember(Value = "salto")]
                Salto = 13,

                [EnumMember(Value = "schlage")]
                Schlage = 14,

                [EnumMember(Value = "seam")]
                Seam = 15,

                [EnumMember(Value = "wyze")]
                Wyze = 16,

                [EnumMember(Value = "yale")]
                Yale = 17,

                [EnumMember(Value = "two_n")]
                TwoN = 18,

                [EnumMember(Value = "controlbyweb")]
                Controlbyweb = 19,

                [EnumMember(Value = "ttlock")]
                Ttlock = 20,

                [EnumMember(Value = "igloohome")]
                Igloohome = 21,

                [EnumMember(Value = "four_suites")]
                FourSuites = 22,

                [EnumMember(Value = "dormakaba_oracode")]
                DormakabaOracode = 23,

                [EnumMember(Value = "tedee")]
                Tedee = 24,

                [EnumMember(Value = "keyincode")]
                Keyincode = 25,

                [EnumMember(Value = "akiles")]
                Akiles = 26,

                [EnumMember(Value = "aqara")]
                Aqara = 27,

                [EnumMember(Value = "korelock")]
                Korelock = 28,

                [EnumMember(Value = "smartthings")]
                Smartthings = 29,

                [EnumMember(Value = "ultraloq")]
                Ultraloq = 30,

                [EnumMember(Value = "omnitec")]
                Omnitec = 31,

                [EnumMember(Value = "kisi")]
                Kisi = 32,

                [EnumMember(Value = "yacan")]
                Yacan = 33,
            }

            /// <summary>
            /// ID of the Connect Webview for which you want to list devices.
            /// </summary>
            [JsonPropertyName("connect_webview_id")]
            public string? ConnectWebviewId { get; init; }

            /// <summary>
            /// ID of the connected account for which you want to list devices.
            /// </summary>
            [JsonPropertyName("connected_account_id")]
            public string? ConnectedAccountId { get; init; }

            /// <summary>
            /// Customer key for which you want to list devices.
            /// </summary>
            [JsonPropertyName("customer_key")]
            public string? CustomerKey { get; init; }

            /// <summary>
            /// Device type of the locks that you want to list.
            /// </summary>
            [JsonPropertyName("device_type")]
            public ListRequest.DeviceTypeEnum? DeviceType { get; init; }

            /// <summary>
            /// Device types of the locks that you want to list.
            /// </summary>
            [JsonPropertyName("device_types")]
            public List<ListRequest.DeviceTypesEnum>? DeviceTypes { get; init; }

            /// <summary>
            /// Manufacturer of the locks that you want to list.
            /// </summary>
            [JsonPropertyName("manufacturer")]
            public ListRequest.ManufacturerEnum? Manufacturer { get; init; }
        }

        public sealed record ListResponse
        {
            /// <summary>
            /// OK
            /// </summary>
            [JsonPropertyName("devices")]
            public List<Device>? Devices { get; init; }
        }

        /// <summary>
        /// Returns a list of all [locks](https://docs.seam.co/low-level-apis/smart-locks).
        /// </summary>
        public async Task<List<Device>> ListAsync(
            ListRequest? request = null,
            CancellationToken cancellationToken = default
        )
        {
            var response = await _transport
                .SendAsync<ListResponse>(
                    HttpMethod.Get,
                    "/locks/list",
                    request,
                    "devices",
                    cancellationToken
                )
                .ConfigureAwait(false);
            return response.Read(r => r.Devices);
        }

        /// <summary>
        /// Request parameters for Lock a Lock.
        /// </summary>
        public sealed record LockDoorRequest
        {
            /// <summary>
            /// ID of the lock that you want to lock.
            /// </summary>
            [JsonPropertyName("device_id")]
            public required string DeviceId { get; init; }
        }

        public sealed record LockDoorResponse
        {
            /// <summary>
            /// OK
            /// </summary>
            [JsonPropertyName("action_attempt")]
            public ActionAttempt? ActionAttempt { get; init; }
        }

        /// <summary>
        /// Locks a [lock](https://docs.seam.co/low-level-apis/smart-locks). See also [Locking and Unlocking Smart Locks](https://docs.seam.co/low-level-apis/smart-locks/lock-and-unlock).
        /// </summary>
        public async Task<ActionAttempt> LockDoorAsync(
            LockDoorRequest request,
            ActionAttemptWait? waitForActionAttempt = null,
            CancellationToken cancellationToken = default
        )
        {
            var response = await _transport
                .SendAsync<LockDoorResponse>(
                    HttpMethod.Post,
                    "/locks/lock_door",
                    request,
                    "action_attempt",
                    cancellationToken
                )
                .ConfigureAwait(false);
            var actionAttempt = response.Read(r => r.ActionAttempt);
            return await ActionAttemptResolver
                .ResolveAsync(
                    actionAttempt,
                    _transport,
                    waitForActionAttempt ?? _waitForActionAttemptDefault,
                    cancellationToken
                )
                .ConfigureAwait(false);
        }

        /// <summary>
        /// Request parameters for Unlock a Lock.
        /// </summary>
        public sealed record UnlockDoorRequest
        {
            /// <summary>
            /// ID of the lock that you want to unlock.
            /// </summary>
            [JsonPropertyName("device_id")]
            public required string DeviceId { get; init; }
        }

        public sealed record UnlockDoorResponse
        {
            /// <summary>
            /// OK
            /// </summary>
            [JsonPropertyName("action_attempt")]
            public ActionAttempt? ActionAttempt { get; init; }
        }

        /// <summary>
        /// Unlocks a [lock](https://docs.seam.co/low-level-apis/smart-locks). See also [Locking and Unlocking Smart Locks](https://docs.seam.co/low-level-apis/smart-locks/lock-and-unlock).
        /// </summary>
        public async Task<ActionAttempt> UnlockDoorAsync(
            UnlockDoorRequest request,
            ActionAttemptWait? waitForActionAttempt = null,
            CancellationToken cancellationToken = default
        )
        {
            var response = await _transport
                .SendAsync<UnlockDoorResponse>(
                    HttpMethod.Post,
                    "/locks/unlock_door",
                    request,
                    "action_attempt",
                    cancellationToken
                )
                .ConfigureAwait(false);
            var actionAttempt = response.Read(r => r.ActionAttempt);
            return await ActionAttemptResolver
                .ResolveAsync(
                    actionAttempt,
                    _transport,
                    waitForActionAttempt ?? _waitForActionAttemptDefault,
                    cancellationToken
                )
                .ConfigureAwait(false);
        }
    }
}
