// <auto-generated>
//   Generated by codegen/smith.ts from @seamapi/types. Do not edit.
// </auto-generated>
#nullable enable
#pragma warning disable CS0618 // The generated code references its own deprecated members.
using System.Runtime.Serialization;
using System.Text.Json;
using System.Text.Json.Serialization;
using Seam.Http;
using Seam.Models;

namespace Seam.Routes
{
    public sealed class NoiseSensorsSimulate
    {
        private readonly SeamHttpTransport _transport;
        private readonly ActionAttemptWait _waitForActionAttemptDefault;

        internal NoiseSensorsSimulate(
            SeamHttpTransport transport,
            ActionAttemptWait waitForActionAttemptDefault
        )
        {
            _transport = transport;
            _waitForActionAttemptDefault = waitForActionAttemptDefault;
        }

        /// <summary>
        /// Request parameters for Simulate Triggering a Noise Threshold.
        /// </summary>
        public sealed record TriggerNoiseThresholdRequest
        {
            /// <summary>
            /// ID of the device for which you want to simulate the triggering of a noise threshold.
            /// </summary>
            [JsonPropertyName("device_id")]
            public required string DeviceId { get; init; }
        }

        /// <summary>
        /// Simulates the triggering of a [noise threshold](https://docs.seam.co/capability-guides/noise-sensors/configure-noise-threshold-settings) for a [noise sensor](https://docs.seam.co/capability-guides/noise-sensors) in a [sandbox workspace](https://docs.seam.co/core-concepts/workspaces#sandbox-workspaces).
        /// </summary>
        public async Task TriggerNoiseThresholdAsync(
            TriggerNoiseThresholdRequest request,
            CancellationToken cancellationToken = default
        )
        {
            await _transport
                .SendAsync(
                    HttpMethod.Post,
                    "/noise_sensors/simulate/trigger_noise_threshold",
                    request,
                    cancellationToken
                )
                .ConfigureAwait(false);
        }
    }
}
