// <auto-generated>
//   Generated by codegen/smith.ts from @seamapi/types. Do not edit.
// </auto-generated>
#nullable enable
#pragma warning disable CS0618 // The generated code references its own deprecated members.
using System.Runtime.Serialization;
using System.Text.Json;
using System.Text.Json.Serialization;
using Seam.Http;
using Seam.Models;

namespace Seam.Routes
{
    public sealed class Phones
    {
        private readonly SeamHttpTransport _transport;
        private readonly ActionAttemptWait _waitForActionAttemptDefault;

        internal Phones(SeamHttpTransport transport, ActionAttemptWait waitForActionAttemptDefault)
        {
            _transport = transport;
            _waitForActionAttemptDefault = waitForActionAttemptDefault;
            Simulate = new PhonesSimulate(transport, waitForActionAttemptDefault);
        }

        public PhonesSimulate Simulate { get; }

        /// <summary>
        /// Request parameters for Deactivate a Phone.
        /// </summary>
        public sealed record DeactivateRequest
        {
            /// <summary>
            /// Device ID of the phone that you want to deactivate.
            /// </summary>
            [JsonPropertyName("device_id")]
            public required string DeviceId { get; init; }
        }

        /// <summary>
        /// Deactivates a phone, which is useful, for example, if a user has lost their phone. For more information, see [App User Lost Phone Process](https://docs.seam.co/capability-guides/mobile-access/managing-phones-for-a-user-identity#app-user-lost-phone-process).
        /// </summary>
        public async Task DeactivateAsync(
            DeactivateRequest request,
            CancellationToken cancellationToken = default
        )
        {
            await _transport
                .SendAsync(HttpMethod.Delete, "/phones/deactivate", request, cancellationToken)
                .ConfigureAwait(false);
        }

        /// <summary>
        /// Request parameters for Get a Phone.
        /// </summary>
        public sealed record GetRequest
        {
            /// <summary>
            /// Device ID of the phone that you want to get.
            /// </summary>
            [JsonPropertyName("device_id")]
            public required string DeviceId { get; init; }
        }

        public sealed record GetResponse
        {
            /// <summary>
            /// OK
            /// </summary>
            [JsonPropertyName("phone")]
            public Phone? Phone { get; init; }
        }

        /// <summary>
        /// Returns a specified [phone](https://docs.seam.co/capability-guides/mobile-access/managing-phones-for-a-user-identity).
        /// </summary>
        public async Task<Phone> GetAsync(
            GetRequest request,
            CancellationToken cancellationToken = default
        )
        {
            var response = await _transport
                .SendAsync<GetResponse>(HttpMethod.Get, "/phones/get", request, cancellationToken)
                .ConfigureAwait(false);
            return response.Phone
                ?? throw new HttpRequestException("Seam returned no phone for /phones/get");
        }

        /// <summary>
        /// Request parameters for List Phones.
        /// </summary>
        public sealed record ListRequest
        {
            /// <summary>
            /// ID of the [credential](https://docs.seam.co/low-level-apis/access-systems/managing-credentials) by which you want to filter the list of returned phones.
            /// </summary>
            [JsonPropertyName("acs_credential_id")]
            public string? AcsCredentialId { get; init; }

            /// <summary>
            /// ID of the user identity that represents the owner by which you want to filter the list of returned phones.
            /// </summary>
            [JsonPropertyName("owner_user_identity_id")]
            public string? OwnerUserIdentityId { get; init; }
        }

        public sealed record ListResponse
        {
            /// <summary>
            /// OK
            /// </summary>
            [JsonPropertyName("phones")]
            public List<Phone>? Phones { get; init; }
        }

        /// <summary>
        /// Returns a list of all [phones](https://docs.seam.co/capability-guides/mobile-access/managing-phones-for-a-user-identity). To filter the list of returned phones by a specific owner user identity or credential, include the `owner_user_identity_id` or `acs_credential_id`, respectively, in the request body.
        /// </summary>
        public async Task<List<Phone>> ListAsync(
            ListRequest? request = null,
            CancellationToken cancellationToken = default
        )
        {
            var response = await _transport
                .SendAsync<ListResponse>(HttpMethod.Get, "/phones/list", request, cancellationToken)
                .ConfigureAwait(false);
            return response.Phones
                ?? throw new HttpRequestException("Seam returned no phones for /phones/list");
        }
    }
}
