// <auto-generated>
//   Generated by codegen/smith.ts from @seamapi/types. Do not edit.
// </auto-generated>
#nullable enable
#pragma warning disable CS0618 // The generated code references its own deprecated members.
using System.Runtime.Serialization;
using System.Text.Json;
using System.Text.Json.Serialization;
using Seam.Http;
using Seam.Models;

namespace Seam.Routes
{
    public sealed class Webhooks
    {
        private readonly SeamHttpTransport _transport;
        private readonly ActionAttemptWait _waitForActionAttemptDefault;

        internal Webhooks(
            SeamHttpTransport transport,
            ActionAttemptWait waitForActionAttemptDefault
        )
        {
            _transport = transport;
            _waitForActionAttemptDefault = waitForActionAttemptDefault;
        }

        /// <summary>
        /// Request parameters for Create a Webhook.
        /// </summary>
        public sealed record CreateRequest
        {
            /// <summary>
            /// Types of events that you want the new webhook to receive.
            /// </summary>
            [JsonPropertyName("event_types")]
            public List<string>? EventTypes { get; init; }

            /// <summary>
            /// URL for the new webhook.
            /// </summary>
            [JsonPropertyName("url")]
            public required string Url { get; init; }
        }

        public sealed record CreateResponse
        {
            /// <summary>
            /// OK
            /// </summary>
            [JsonPropertyName("webhook")]
            public Webhook? Webhook { get; init; }
        }

        /// <summary>
        /// Creates a new [webhook](https://docs.seam.co/developer-tools/webhooks).
        /// </summary>
        public async Task<Webhook> CreateAsync(
            CreateRequest request,
            CancellationToken cancellationToken = default
        )
        {
            var response = await _transport
                .SendAsync<CreateResponse>(
                    HttpMethod.Post,
                    "/webhooks/create",
                    request,
                    cancellationToken
                )
                .ConfigureAwait(false);
            return response.Webhook
                ?? throw new HttpRequestException("Seam returned no webhook for /webhooks/create");
        }

        /// <summary>
        /// Request parameters for Delete a Webhook.
        /// </summary>
        public sealed record DeleteRequest
        {
            /// <summary>
            /// ID of the webhook that you want to delete.
            /// </summary>
            [JsonPropertyName("webhook_id")]
            public required string WebhookId { get; init; }
        }

        /// <summary>
        /// Deletes a specified [webhook](https://docs.seam.co/developer-tools/webhooks).
        /// </summary>
        public async Task DeleteAsync(
            DeleteRequest request,
            CancellationToken cancellationToken = default
        )
        {
            await _transport
                .SendAsync(HttpMethod.Delete, "/webhooks/delete", request, cancellationToken)
                .ConfigureAwait(false);
        }

        /// <summary>
        /// Request parameters for Get a Webhook.
        /// </summary>
        public sealed record GetRequest
        {
            /// <summary>
            /// ID of the webhook that you want to get.
            /// </summary>
            [JsonPropertyName("webhook_id")]
            public required string WebhookId { get; init; }
        }

        public sealed record GetResponse
        {
            /// <summary>
            /// OK
            /// </summary>
            [JsonPropertyName("webhook")]
            public Webhook? Webhook { get; init; }
        }

        /// <summary>
        /// Gets a specified [webhook](https://docs.seam.co/developer-tools/webhooks).
        /// </summary>
        public async Task<Webhook> GetAsync(
            GetRequest request,
            CancellationToken cancellationToken = default
        )
        {
            var response = await _transport
                .SendAsync<GetResponse>(HttpMethod.Get, "/webhooks/get", request, cancellationToken)
                .ConfigureAwait(false);
            return response.Webhook
                ?? throw new HttpRequestException("Seam returned no webhook for /webhooks/get");
        }

        /// <summary>
        /// Request parameters for List Webhooks.
        /// </summary>
        public sealed record ListRequest { }

        public sealed record ListResponse
        {
            /// <summary>
            /// OK
            /// </summary>
            [JsonPropertyName("webhooks")]
            public List<Webhook>? Webhooks { get; init; }
        }

        /// <summary>
        /// Returns a list of all [webhooks](https://docs.seam.co/developer-tools/webhooks).
        /// </summary>
        public async Task<List<Webhook>> ListAsync(
            ListRequest? request = null,
            CancellationToken cancellationToken = default
        )
        {
            var response = await _transport
                .SendAsync<ListResponse>(
                    HttpMethod.Get,
                    "/webhooks/list",
                    request,
                    cancellationToken
                )
                .ConfigureAwait(false);
            return response.Webhooks
                ?? throw new HttpRequestException("Seam returned no webhooks for /webhooks/list");
        }

        /// <summary>
        /// Request parameters for Update a Webhook.
        /// </summary>
        public sealed record UpdateRequest
        {
            /// <summary>
            /// Types of events that you want the webhook to receive.
            /// </summary>
            [JsonPropertyName("event_types")]
            public required List<string> EventTypes { get; init; }

            /// <summary>
            /// ID of the webhook that you want to update.
            /// </summary>
            [JsonPropertyName("webhook_id")]
            public required string WebhookId { get; init; }
        }

        /// <summary>
        /// Updates a specified [webhook](https://docs.seam.co/developer-tools/webhooks).
        /// </summary>
        public async Task UpdateAsync(
            UpdateRequest request,
            CancellationToken cancellationToken = default
        )
        {
            await _transport
                .SendAsync(HttpMethod.Put, "/webhooks/update", request, cancellationToken)
                .ConfigureAwait(false);
        }
    }
}
