// <auto-generated>
//   Generated by codegen/smith.ts from @seamapi/types. Do not edit.
// </auto-generated>
#nullable enable
#pragma warning disable CS0618 // The generated code references its own deprecated members.
using System.Runtime.Serialization;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Seam.Models
{
    /// <summary>
    /// Represents a smart lock [access code](https://docs.seam.co/low-level-apis/smart-locks/access-codes).
    ///
    /// An access code is a code used for a keypad or pinpad device. Unlike physical keys, which can easily be lost or duplicated, PIN codes can be customized, tracked, and altered on the fly. Using the Seam Access Code API, you can easily generate access codes on the hundreds of door lock models with which we integrate.
    ///
    /// Seam supports programming two types of access codes: [ongoing](https://docs.seam.co/low-level-apis/smart-locks/access-codes#ongoing-access-codes) and [time-bound](https://docs.seam.co/low-level-apis/smart-locks/access-codes#time-bound-access-codes). To differentiate between the two, refer to the `type` property of the access code. Ongoing codes display as `ongoing`, whereas time-bound codes are labeled `time_bound`. An ongoing access code is active, until it has been removed from the device. To specify an ongoing access code, leave both `starts_at` and `ends_at` empty. A time-bound access code will be programmed at the `starts_at` time and removed at the `ends_at` time.
    ///
    /// In addition, for certain devices, Seam also supports [offline access codes](https://docs.seam.co/low-level-apis/smart-locks/access-codes#offline-access-codes). Offline access (PIN) codes are designed for door locks that might not always maintain an internet connection. For this type of access code, the device manufacturer uses encryption keys (tokens) to create server-based registries of algorithmically-generated offline PIN codes. Because the tokens remain synchronized with the managed devices, the locks do not require an active internet connection—and you do not need to be near the locks—to create an offline access code. Then, owners or managers can share these offline codes with users through a variety of mechanisms, such as messaging applications. That is, lock users do not need to install a smartphone application to receive an offline access code.
    ///
    /// For granting a person access to a space, [Access Grants](https://docs.seam.co/use-cases/granting-access) are the default and recommended approach and work across both standalone smart locks and access systems. Use the lower-level Access Codes API directly only when you specifically need to manage individual PIN codes.
    /// </summary>
    public sealed record AccessCode
    {
        [JsonConverter(typeof(SeamUnionConverter))]
        [SeamUnion("error_code")]
        [SeamUnionVariant("provider_issue", typeof(AccessCodeErrorsProviderIssue))]
        [SeamUnionVariant("failed_to_set_on_device", typeof(AccessCodeErrorsFailedToSetOnDevice))]
        [SeamUnionVariant(
            "failed_to_remove_from_device",
            typeof(AccessCodeErrorsFailedToRemoveFromDevice)
        )]
        [SeamUnionVariant(
            "duplicate_code_on_device",
            typeof(AccessCodeErrorsDuplicateCodeOnDevice)
        )]
        [SeamUnionVariant(
            "no_space_for_access_code_on_device",
            typeof(AccessCodeErrorsNoSpaceForAccessCodeOnDevice)
        )]
        [SeamUnionVariant(
            "conflicting_external_modification",
            typeof(AccessCodeErrorsConflictingExternalModification)
        )]
        [SeamUnionVariant("access_code_inactive", typeof(AccessCodeErrorsAccessCodeInactive))]
        [SeamUnionVariant(
            "code_constraints_violated",
            typeof(AccessCodeErrorsCodeConstraintsViolated)
        )]
        [SeamUnionVariant("failed_to_issue", typeof(AccessCodeErrorsFailedToIssue))]
        [SeamUnionVariant(
            "failed_to_apply_mutations",
            typeof(AccessCodeErrorsFailedToApplyMutations)
        )]
        [SeamUnionVariant("failed_to_expire", typeof(AccessCodeErrorsFailedToExpire))]
        [SeamUnionVariant("account_disconnected", typeof(AccessCodeErrorsAccountDisconnected))]
        [SeamUnionVariant(
            "salto_ks_subscription_limit_exceeded",
            typeof(AccessCodeErrorsSaltoKsSubscriptionLimitExceeded)
        )]
        [SeamUnionVariant(
            "insufficient_permissions",
            typeof(AccessCodeErrorsInsufficientPermissions)
        )]
        [SeamUnionVariant(
            "dormakaba_sites_disconnected",
            typeof(AccessCodeErrorsDormakabaSitesDisconnected)
        )]
        [SeamUnionVariant("device_offline", typeof(AccessCodeErrorsDeviceOffline))]
        [SeamUnionVariant("device_removed", typeof(AccessCodeErrorsDeviceRemoved))]
        [SeamUnionVariant("hub_disconnected", typeof(AccessCodeErrorsHubDisconnected))]
        [SeamUnionVariant("device_disconnected", typeof(AccessCodeErrorsDeviceDisconnected))]
        [SeamUnionVariant(
            "empty_backup_access_code_pool",
            typeof(AccessCodeErrorsEmptyBackupAccessCodePool)
        )]
        [SeamUnionVariant(
            "august_lock_not_authorized",
            typeof(AccessCodeErrorsAugustLockNotAuthorized)
        )]
        [SeamUnionVariant(
            "missing_device_credentials",
            typeof(AccessCodeErrorsMissingDeviceCredentials)
        )]
        [SeamUnionVariant("auxiliary_heat_running", typeof(AccessCodeErrorsAuxiliaryHeatRunning))]
        [SeamUnionVariant("subscription_required", typeof(AccessCodeErrorsSubscriptionRequired))]
        [SeamUnionVariant("bridge_disconnected", typeof(AccessCodeErrorsBridgeDisconnected))]
        [SeamUnionFallback(typeof(AccessCodeErrorsUnrecognized))]
        public abstract record AccessCodeErrors
        {
            /// <summary>The value of the <c>error_code</c> discriminator.</summary>
            public abstract string ErrorCode { get; }

            /// <summary>
            /// Detailed description of the error. Provides insights into the issue and potentially how to rectify it.
            /// </summary>
            [JsonPropertyName("message")]
            public string Message { get; init; } = default!;
        }

        public sealed record AccessCodeErrorsProviderIssue : AccessCodeErrors
        {
            [JsonPropertyName("error_code")]
            public override string ErrorCode { get; } = "provider_issue";

            /// <summary>
            /// Date and time at which Seam created the error.
            /// </summary>
            [JsonPropertyName("created_at")]
            public string? CreatedAt { get; init; }

            /// <summary>
            /// Indicates that this is an access code error.
            /// </summary>
            [JsonPropertyName("is_access_code_error")]
            public bool IsAccessCodeError { get; init; } = default!;
        }

        public sealed record AccessCodeErrorsFailedToSetOnDevice : AccessCodeErrors
        {
            [JsonPropertyName("error_code")]
            public override string ErrorCode { get; } = "failed_to_set_on_device";

            /// <summary>
            /// Date and time at which Seam created the error.
            /// </summary>
            [JsonPropertyName("created_at")]
            public string? CreatedAt { get; init; }

            /// <summary>
            /// Indicates that this is an access code error.
            /// </summary>
            [JsonPropertyName("is_access_code_error")]
            public bool IsAccessCodeError { get; init; } = default!;
        }

        public sealed record AccessCodeErrorsFailedToRemoveFromDevice : AccessCodeErrors
        {
            [JsonPropertyName("error_code")]
            public override string ErrorCode { get; } = "failed_to_remove_from_device";

            /// <summary>
            /// Date and time at which Seam created the error.
            /// </summary>
            [JsonPropertyName("created_at")]
            public string? CreatedAt { get; init; }

            /// <summary>
            /// Indicates that this is an access code error.
            /// </summary>
            [JsonPropertyName("is_access_code_error")]
            public bool IsAccessCodeError { get; init; } = default!;
        }

        public sealed record AccessCodeErrorsDuplicateCodeOnDevice : AccessCodeErrors
        {
            [JsonPropertyName("error_code")]
            public override string ErrorCode { get; } = "duplicate_code_on_device";

            /// <summary>
            /// Date and time at which Seam created the error.
            /// </summary>
            [JsonPropertyName("created_at")]
            public string? CreatedAt { get; init; }

            /// <summary>
            /// Indicates that this is an access code error.
            /// </summary>
            [JsonPropertyName("is_access_code_error")]
            public bool IsAccessCodeError { get; init; } = default!;

            /// <summary>
            /// ID of the managed access code that conflicts with this managed access code, when Seam can identify it.
            /// </summary>
            [JsonPropertyName("managed_access_code_id")]
            public string? ManagedAccessCodeId { get; init; }

            /// <summary>
            /// ID of the unmanaged access code that conflicts with this managed access code, when Seam can identify it.
            /// </summary>
            [JsonPropertyName("unmanaged_access_code_id")]
            public string? UnmanagedAccessCodeId { get; init; }
        }

        public sealed record AccessCodeErrorsNoSpaceForAccessCodeOnDevice : AccessCodeErrors
        {
            [JsonPropertyName("error_code")]
            public override string ErrorCode { get; } = "no_space_for_access_code_on_device";

            /// <summary>
            /// Date and time at which Seam created the error.
            /// </summary>
            [JsonPropertyName("created_at")]
            public string? CreatedAt { get; init; }

            /// <summary>
            /// Indicates that this is an access code error.
            /// </summary>
            [JsonPropertyName("is_access_code_error")]
            public bool IsAccessCodeError { get; init; } = default!;
        }

        public sealed record AccessCodeErrorsConflictingExternalModification : AccessCodeErrors
        {
            /// <summary>
            /// Indicates the type of external modification. `modified` means the code&apos;s PIN or schedule was changed. `removed` means the code was deleted from the device.
            /// </summary>
            [JsonConverter(typeof(SeamStringEnumConverter))]
            public enum ChangeTypeEnum
            {
                [EnumMember(Value = "unrecognized")]
                Unrecognized = 0,

                [EnumMember(Value = "modified")]
                Modified = 1,

                [EnumMember(Value = "removed")]
                Removed = 2,
            }

            [JsonPropertyName("error_code")]
            public override string ErrorCode { get; } = "conflicting_external_modification";

            /// <summary>
            /// Indicates the type of external modification. `modified` means the code&apos;s PIN or schedule was changed. `removed` means the code was deleted from the device.
            /// </summary>
            [JsonPropertyName("change_type")]
            public AccessCodeErrorsConflictingExternalModification.ChangeTypeEnum? ChangeType { get; init; }

            /// <summary>
            /// Date and time at which Seam created the error.
            /// </summary>
            [JsonPropertyName("created_at")]
            public string? CreatedAt { get; init; }

            /// <summary>
            /// Indicates that this is an access code error.
            /// </summary>
            [JsonPropertyName("is_access_code_error")]
            public bool IsAccessCodeError { get; init; } = default!;

            /// <summary>
            /// List of fields that were changed externally, with their previous and new values.
            /// </summary>
            [JsonPropertyName("modified_fields")]
            public List<AccessCodeErrorsConflictingExternalModificationModifiedFields>? ModifiedFields { get; init; }
        }

        public sealed record AccessCodeErrorsConflictingExternalModificationModifiedFields
        {
            /// <summary>
            /// The name of the field that was changed (e.g. `code`, `starts_at`, `ends_at`).
            /// </summary>
            [JsonPropertyName("field")]
            public string Field { get; init; } = default!;

            /// <summary>
            /// The previous value of the field.
            /// </summary>
            [JsonPropertyName("from")]
            public string? From { get; init; }

            /// <summary>
            /// The new value of the field.
            /// </summary>
            [JsonPropertyName("to")]
            public string? To { get; init; }
        }

        public sealed record AccessCodeErrorsAccessCodeInactive : AccessCodeErrors
        {
            [JsonPropertyName("error_code")]
            public override string ErrorCode { get; } = "access_code_inactive";

            /// <summary>
            /// Date and time at which Seam created the error.
            /// </summary>
            [JsonPropertyName("created_at")]
            public string? CreatedAt { get; init; }

            /// <summary>
            /// Indicates that this is an access code error.
            /// </summary>
            [JsonPropertyName("is_access_code_error")]
            public bool IsAccessCodeError { get; init; } = default!;
        }

        public sealed record AccessCodeErrorsCodeConstraintsViolated : AccessCodeErrors
        {
            [JsonPropertyName("error_code")]
            public override string ErrorCode { get; } = "code_constraints_violated";

            /// <summary>
            /// Date and time at which Seam created the error.
            /// </summary>
            [JsonPropertyName("created_at")]
            public string? CreatedAt { get; init; }

            /// <summary>
            /// Indicates that this is an access code error.
            /// </summary>
            [JsonPropertyName("is_access_code_error")]
            public bool IsAccessCodeError { get; init; } = default!;
        }

        public sealed record AccessCodeErrorsFailedToIssue : AccessCodeErrors
        {
            [JsonPropertyName("error_code")]
            public override string ErrorCode { get; } = "failed_to_issue";

            /// <summary>
            /// Date and time at which Seam created the error.
            /// </summary>
            [JsonPropertyName("created_at")]
            public string? CreatedAt { get; init; }

            /// <summary>
            /// Indicates that this is an access code error.
            /// </summary>
            [JsonPropertyName("is_access_code_error")]
            public bool IsAccessCodeError { get; init; } = default!;
        }

        public sealed record AccessCodeErrorsFailedToApplyMutations : AccessCodeErrors
        {
            [JsonPropertyName("error_code")]
            public override string ErrorCode { get; } = "failed_to_apply_mutations";

            /// <summary>
            /// Date and time at which Seam created the error.
            /// </summary>
            [JsonPropertyName("created_at")]
            public string? CreatedAt { get; init; }

            /// <summary>
            /// Indicates that this is an access code error.
            /// </summary>
            [JsonPropertyName("is_access_code_error")]
            public bool IsAccessCodeError { get; init; } = default!;
        }

        public sealed record AccessCodeErrorsFailedToExpire : AccessCodeErrors
        {
            [JsonPropertyName("error_code")]
            public override string ErrorCode { get; } = "failed_to_expire";

            /// <summary>
            /// Date and time at which Seam created the error.
            /// </summary>
            [JsonPropertyName("created_at")]
            public string? CreatedAt { get; init; }

            /// <summary>
            /// Indicates that this is an access code error.
            /// </summary>
            [JsonPropertyName("is_access_code_error")]
            public bool IsAccessCodeError { get; init; } = default!;
        }

        public sealed record AccessCodeErrorsAccountDisconnected : AccessCodeErrors
        {
            [JsonPropertyName("error_code")]
            public override string ErrorCode { get; } = "account_disconnected";

            /// <summary>
            /// Date and time at which Seam created the error.
            /// </summary>
            [JsonPropertyName("created_at")]
            public string CreatedAt { get; init; } = default!;

            /// <summary>
            /// Indicates that the error is a [connected account](https://docs.seam.co/api/connected_accounts) error.
            /// </summary>
            [JsonPropertyName("is_connected_account_error")]
            public bool IsConnectedAccountError { get; init; } = default!;

            /// <summary>
            /// Indicates that the error is not a device error.
            /// </summary>
            [JsonPropertyName("is_device_error")]
            public bool IsDeviceError { get; init; } = default!;
        }

        public sealed record AccessCodeErrorsSaltoKsSubscriptionLimitExceeded : AccessCodeErrors
        {
            [JsonPropertyName("error_code")]
            public override string ErrorCode { get; } = "salto_ks_subscription_limit_exceeded";

            /// <summary>
            /// Date and time at which Seam created the error.
            /// </summary>
            [JsonPropertyName("created_at")]
            public string CreatedAt { get; init; } = default!;

            /// <summary>
            /// Indicates that the error is a [connected account](https://docs.seam.co/api/connected_accounts) error.
            /// </summary>
            [JsonPropertyName("is_connected_account_error")]
            public bool IsConnectedAccountError { get; init; } = default!;

            /// <summary>
            /// Indicates that the error is not a device error.
            /// </summary>
            [JsonPropertyName("is_device_error")]
            public bool IsDeviceError { get; init; } = default!;
        }

        public sealed record AccessCodeErrorsInsufficientPermissions : AccessCodeErrors
        {
            [JsonPropertyName("error_code")]
            public override string ErrorCode { get; } = "insufficient_permissions";

            /// <summary>
            /// Date and time at which Seam created the error.
            /// </summary>
            [JsonPropertyName("created_at")]
            public string CreatedAt { get; init; } = default!;

            /// <summary>
            /// Indicates that the error is a [connected account](https://docs.seam.co/api/connected_accounts) error.
            /// </summary>
            [JsonPropertyName("is_connected_account_error")]
            public bool IsConnectedAccountError { get; init; } = default!;

            /// <summary>
            /// Indicates that the error is not a device error.
            /// </summary>
            [JsonPropertyName("is_device_error")]
            public bool IsDeviceError { get; init; } = default!;
        }

        public sealed record AccessCodeErrorsDormakabaSitesDisconnected : AccessCodeErrors
        {
            [JsonPropertyName("error_code")]
            public override string ErrorCode { get; } = "dormakaba_sites_disconnected";

            /// <summary>
            /// Date and time at which Seam created the error.
            /// </summary>
            [JsonPropertyName("created_at")]
            public string CreatedAt { get; init; } = default!;

            /// <summary>
            /// Indicates that the error is a [connected account](https://docs.seam.co/api/connected_accounts) error.
            /// </summary>
            [JsonPropertyName("is_connected_account_error")]
            public bool IsConnectedAccountError { get; init; } = default!;

            /// <summary>
            /// Indicates that the error is not a device error.
            /// </summary>
            [JsonPropertyName("is_device_error")]
            public bool IsDeviceError { get; init; } = default!;
        }

        public sealed record AccessCodeErrorsDeviceOffline : AccessCodeErrors
        {
            [JsonPropertyName("error_code")]
            public override string ErrorCode { get; } = "device_offline";

            /// <summary>
            /// Date and time at which Seam created the error.
            /// </summary>
            [JsonPropertyName("created_at")]
            public string CreatedAt { get; init; } = default!;

            /// <summary>
            /// Indicates that the error is a device error.
            /// </summary>
            [JsonPropertyName("is_device_error")]
            public bool IsDeviceError { get; init; } = default!;
        }

        public sealed record AccessCodeErrorsDeviceRemoved : AccessCodeErrors
        {
            [JsonPropertyName("error_code")]
            public override string ErrorCode { get; } = "device_removed";

            /// <summary>
            /// Date and time at which Seam created the error.
            /// </summary>
            [JsonPropertyName("created_at")]
            public string CreatedAt { get; init; } = default!;

            /// <summary>
            /// Indicates that the error is a device error.
            /// </summary>
            [JsonPropertyName("is_device_error")]
            public bool IsDeviceError { get; init; } = default!;
        }

        public sealed record AccessCodeErrorsHubDisconnected : AccessCodeErrors
        {
            [JsonPropertyName("error_code")]
            public override string ErrorCode { get; } = "hub_disconnected";

            /// <summary>
            /// Date and time at which Seam created the error.
            /// </summary>
            [JsonPropertyName("created_at")]
            public string CreatedAt { get; init; } = default!;

            /// <summary>
            /// Indicates that the error is a device error.
            /// </summary>
            [JsonPropertyName("is_device_error")]
            public bool IsDeviceError { get; init; } = default!;
        }

        public sealed record AccessCodeErrorsDeviceDisconnected : AccessCodeErrors
        {
            [JsonPropertyName("error_code")]
            public override string ErrorCode { get; } = "device_disconnected";

            /// <summary>
            /// Date and time at which Seam created the error.
            /// </summary>
            [JsonPropertyName("created_at")]
            public string CreatedAt { get; init; } = default!;

            /// <summary>
            /// Indicates that the error is a device error.
            /// </summary>
            [JsonPropertyName("is_device_error")]
            public bool IsDeviceError { get; init; } = default!;
        }

        public sealed record AccessCodeErrorsEmptyBackupAccessCodePool : AccessCodeErrors
        {
            [JsonPropertyName("error_code")]
            public override string ErrorCode { get; } = "empty_backup_access_code_pool";

            /// <summary>
            /// Date and time at which Seam created the error.
            /// </summary>
            [JsonPropertyName("created_at")]
            public string CreatedAt { get; init; } = default!;

            /// <summary>
            /// Indicates that the error is a device error.
            /// </summary>
            [JsonPropertyName("is_device_error")]
            public bool IsDeviceError { get; init; } = default!;
        }

        public sealed record AccessCodeErrorsAugustLockNotAuthorized : AccessCodeErrors
        {
            [JsonPropertyName("error_code")]
            public override string ErrorCode { get; } = "august_lock_not_authorized";

            /// <summary>
            /// Date and time at which Seam created the error.
            /// </summary>
            [JsonPropertyName("created_at")]
            public string CreatedAt { get; init; } = default!;

            /// <summary>
            /// Indicates that the error is a device error.
            /// </summary>
            [JsonPropertyName("is_device_error")]
            public bool IsDeviceError { get; init; } = default!;
        }

        public sealed record AccessCodeErrorsMissingDeviceCredentials : AccessCodeErrors
        {
            [JsonPropertyName("error_code")]
            public override string ErrorCode { get; } = "missing_device_credentials";

            /// <summary>
            /// Date and time at which Seam created the error.
            /// </summary>
            [JsonPropertyName("created_at")]
            public string CreatedAt { get; init; } = default!;

            /// <summary>
            /// Indicates that the error is a device error.
            /// </summary>
            [JsonPropertyName("is_device_error")]
            public bool IsDeviceError { get; init; } = default!;
        }

        public sealed record AccessCodeErrorsAuxiliaryHeatRunning : AccessCodeErrors
        {
            [JsonPropertyName("error_code")]
            public override string ErrorCode { get; } = "auxiliary_heat_running";

            /// <summary>
            /// Date and time at which Seam created the error.
            /// </summary>
            [JsonPropertyName("created_at")]
            public string CreatedAt { get; init; } = default!;

            /// <summary>
            /// Indicates that the error is a device error.
            /// </summary>
            [JsonPropertyName("is_device_error")]
            public bool IsDeviceError { get; init; } = default!;
        }

        public sealed record AccessCodeErrorsSubscriptionRequired : AccessCodeErrors
        {
            [JsonPropertyName("error_code")]
            public override string ErrorCode { get; } = "subscription_required";

            /// <summary>
            /// Date and time at which Seam created the error.
            /// </summary>
            [JsonPropertyName("created_at")]
            public string CreatedAt { get; init; } = default!;

            /// <summary>
            /// Indicates that the error is a device error.
            /// </summary>
            [JsonPropertyName("is_device_error")]
            public bool IsDeviceError { get; init; } = default!;
        }

        public sealed record AccessCodeErrorsBridgeDisconnected : AccessCodeErrors
        {
            [JsonPropertyName("error_code")]
            public override string ErrorCode { get; } = "bridge_disconnected";

            /// <summary>
            /// Date and time at which Seam created the error.
            /// </summary>
            [JsonPropertyName("created_at")]
            public string CreatedAt { get; init; } = default!;

            /// <summary>
            /// Indicates whether the error is related to [Seam Bridge](https://docs.seam.co/capability-guides/seam-bridge).
            /// </summary>
            [JsonPropertyName("is_bridge_error")]
            public bool? IsBridgeError { get; init; }

            /// <summary>
            /// Indicates whether the error is related specifically to the connected account.
            /// </summary>
            [JsonPropertyName("is_connected_account_error")]
            public bool? IsConnectedAccountError { get; init; }
        }

        public sealed record AccessCodeErrorsUnrecognized
            : AccessCodeErrors,
                ISeamUnrecognizedVariant
        {
            [JsonPropertyName("error_code")]
            public override string ErrorCode { get; } = "unrecognized";

            /// <summary>The complete raw JSON of the unrecognized payload.</summary>
            [JsonIgnore]
            public JsonElement RawJson { get; set; }
        }

        [JsonConverter(typeof(SeamUnionConverter))]
        [SeamUnion("mutation_code")]
        [SeamUnionVariant("creating", typeof(AccessCodePendingMutationsCreating))]
        [SeamUnionVariant(
            "deferring_creation",
            typeof(AccessCodePendingMutationsDeferringCreation)
        )]
        [SeamUnionVariant("deleting", typeof(AccessCodePendingMutationsDeleting))]
        [SeamUnionVariant("updating_code", typeof(AccessCodePendingMutationsUpdatingCode))]
        [SeamUnionVariant("updating_name", typeof(AccessCodePendingMutationsUpdatingName))]
        [SeamUnionVariant(
            "updating_time_frame",
            typeof(AccessCodePendingMutationsUpdatingTimeFrame)
        )]
        [SeamUnionFallback(typeof(AccessCodePendingMutationsUnrecognized))]
        public abstract record AccessCodePendingMutations
        {
            /// <summary>The value of the <c>mutation_code</c> discriminator.</summary>
            public abstract string MutationCode { get; }

            /// <summary>
            /// Date and time at which the mutation was created.
            /// </summary>
            [JsonPropertyName("created_at")]
            public string CreatedAt { get; init; } = default!;

            /// <summary>
            /// Detailed description of the mutation.
            /// </summary>
            [JsonPropertyName("message")]
            public string Message { get; init; } = default!;
        }

        public sealed record AccessCodePendingMutationsCreating : AccessCodePendingMutations
        {
            [JsonPropertyName("mutation_code")]
            public override string MutationCode { get; } = "creating";
        }

        public sealed record AccessCodePendingMutationsDeferringCreation
            : AccessCodePendingMutations
        {
            [JsonPropertyName("mutation_code")]
            public override string MutationCode { get; } = "deferring_creation";

            /// <summary>
            /// Date and time at which Seam will attempt to program this access code on the device.
            /// </summary>
            [JsonPropertyName("scheduled_at")]
            public string ScheduledAt { get; init; } = default!;
        }

        public sealed record AccessCodePendingMutationsDeleting : AccessCodePendingMutations
        {
            [JsonPropertyName("mutation_code")]
            public override string MutationCode { get; } = "deleting";
        }

        public sealed record AccessCodePendingMutationsUpdatingCode : AccessCodePendingMutations
        {
            [JsonPropertyName("mutation_code")]
            public override string MutationCode { get; } = "updating_code";

            /// <summary>
            /// Previous code configuration.
            /// </summary>
            [JsonPropertyName("from")]
            public AccessCodePendingMutationsUpdatingCodeFrom From { get; init; } = default!;

            /// <summary>
            /// New code configuration.
            /// </summary>
            [JsonPropertyName("to")]
            public AccessCodePendingMutationsUpdatingCodeTo To { get; init; } = default!;
        }

        public sealed record AccessCodePendingMutationsUpdatingCodeFrom
        {
            /// <summary>
            /// Previous PIN code.
            /// </summary>
            [JsonPropertyName("code")]
            public string? Code { get; init; }
        }

        public sealed record AccessCodePendingMutationsUpdatingCodeTo
        {
            /// <summary>
            /// New PIN code.
            /// </summary>
            [JsonPropertyName("code")]
            public string? Code { get; init; }
        }

        public sealed record AccessCodePendingMutationsUpdatingName : AccessCodePendingMutations
        {
            [JsonPropertyName("mutation_code")]
            public override string MutationCode { get; } = "updating_name";

            /// <summary>
            /// Previous name configuration.
            /// </summary>
            [JsonPropertyName("from")]
            public AccessCodePendingMutationsUpdatingNameFrom From { get; init; } = default!;

            /// <summary>
            /// New name configuration.
            /// </summary>
            [JsonPropertyName("to")]
            public AccessCodePendingMutationsUpdatingNameTo To { get; init; } = default!;
        }

        public sealed record AccessCodePendingMutationsUpdatingNameFrom
        {
            /// <summary>
            /// Previous access code name.
            /// </summary>
            [JsonPropertyName("name")]
            public string? Name { get; init; }
        }

        public sealed record AccessCodePendingMutationsUpdatingNameTo
        {
            /// <summary>
            /// New access code name.
            /// </summary>
            [JsonPropertyName("name")]
            public string? Name { get; init; }
        }

        public sealed record AccessCodePendingMutationsUpdatingTimeFrame
            : AccessCodePendingMutations
        {
            [JsonPropertyName("mutation_code")]
            public override string MutationCode { get; } = "updating_time_frame";

            /// <summary>
            /// Previous time frame configuration.
            /// </summary>
            [JsonPropertyName("from")]
            public AccessCodePendingMutationsUpdatingTimeFrameFrom From { get; init; } = default!;

            /// <summary>
            /// New time frame configuration.
            /// </summary>
            [JsonPropertyName("to")]
            public AccessCodePendingMutationsUpdatingTimeFrameTo To { get; init; } = default!;
        }

        public sealed record AccessCodePendingMutationsUpdatingTimeFrameFrom
        {
            /// <summary>
            /// Previous end time for the access code.
            /// </summary>
            [JsonPropertyName("ends_at")]
            public string? EndsAt { get; init; }

            /// <summary>
            /// Previous start time for the access code.
            /// </summary>
            [JsonPropertyName("starts_at")]
            public string? StartsAt { get; init; }
        }

        public sealed record AccessCodePendingMutationsUpdatingTimeFrameTo
        {
            /// <summary>
            /// New end time for the access code.
            /// </summary>
            [JsonPropertyName("ends_at")]
            public string? EndsAt { get; init; }

            /// <summary>
            /// New start time for the access code.
            /// </summary>
            [JsonPropertyName("starts_at")]
            public string? StartsAt { get; init; }
        }

        public sealed record AccessCodePendingMutationsUnrecognized
            : AccessCodePendingMutations,
                ISeamUnrecognizedVariant
        {
            [JsonPropertyName("mutation_code")]
            public override string MutationCode { get; } = "unrecognized";

            /// <summary>The complete raw JSON of the unrecognized payload.</summary>
            [JsonIgnore]
            public JsonElement RawJson { get; set; }
        }

        /// <summary>
        /// Current status of the access code within the operational lifecycle. Values are `setting`, a transitional phase that indicates that the code is being configured or activated; `set`, which indicates that the code is active and operational; `unset`, which indicates a deactivated or unused state, either before activation or after deliberate deactivation; `removing`, which indicates a transitional period in which the code is being deleted or made inactive; and `unknown`, which indicates an indeterminate state, due to reasons such as system errors or incomplete data, that highlights a potential need for system review or troubleshooting. See also [Lifecycle of Access Codes](https://docs.seam.co/low-level-apis/smart-locks/access-codes/lifecycle-of-access-codes).
        /// </summary>
        [JsonConverter(typeof(SeamStringEnumConverter))]
        public enum StatusEnum
        {
            [EnumMember(Value = "unrecognized")]
            Unrecognized = 0,

            [EnumMember(Value = "setting")]
            Setting = 1,

            [EnumMember(Value = "set")]
            Set = 2,

            [EnumMember(Value = "unset")]
            Unset = 3,

            [EnumMember(Value = "removing")]
            Removing = 4,

            [EnumMember(Value = "unknown")]
            Unknown = 5,
        }

        /// <summary>
        /// Type of the access code. `ongoing` access codes are active continuously until deactivated manually. `time_bound` access codes have a specific duration.
        /// </summary>
        [JsonConverter(typeof(SeamStringEnumConverter))]
        public enum TypeEnum
        {
            [EnumMember(Value = "unrecognized")]
            Unrecognized = 0,

            [EnumMember(Value = "time_bound")]
            TimeBound = 1,

            [EnumMember(Value = "ongoing")]
            Ongoing = 2,
        }

        [JsonConverter(typeof(SeamUnionConverter))]
        [SeamUnion("warning_code")]
        [SeamUnionVariant(
            "code_rotates_periodically",
            typeof(AccessCodeWarningsCodeRotatesPeriodically)
        )]
        [SeamUnionVariant(
            "time_frame_adjusted_for_unknown_time_zone",
            typeof(AccessCodeWarningsTimeFrameAdjustedForUnknownTimeZone)
        )]
        [SeamUnionVariant(
            "external_modification_in_effect",
            typeof(AccessCodeWarningsExternalModificationInEffect)
        )]
        [SeamUnionVariant(
            "delay_in_setting_on_device",
            typeof(AccessCodeWarningsDelayInSettingOnDevice)
        )]
        [SeamUnionVariant(
            "delay_in_removing_from_device",
            typeof(AccessCodeWarningsDelayInRemovingFromDevice)
        )]
        [SeamUnionVariant("delay_in_issuing", typeof(AccessCodeWarningsDelayInIssuing))]
        [SeamUnionVariant(
            "delay_in_applying_mutations",
            typeof(AccessCodeWarningsDelayInApplyingMutations)
        )]
        [SeamUnionVariant(
            "third_party_integration_detected",
            typeof(AccessCodeWarningsThirdPartyIntegrationDetected)
        )]
        [SeamUnionVariant(
            "igloo_algopin_must_be_used_within_24_hours",
            typeof(AccessCodeWarningsIglooAlgopinMustBeUsedWithin_24Hours)
        )]
        [SeamUnionVariant(
            "management_transferred",
            typeof(AccessCodeWarningsManagementTransferred)
        )]
        [SeamUnionVariant(
            "using_backup_access_code",
            typeof(AccessCodeWarningsUsingBackupAccessCode)
        )]
        [SeamUnionVariant("being_deleted", typeof(AccessCodeWarningsBeingDeleted))]
        [SeamUnionVariant(
            "unknown_issue_with_access_code",
            typeof(AccessCodeWarningsUnknownIssueWithAccessCode)
        )]
        [SeamUnionFallback(typeof(AccessCodeWarningsUnrecognized))]
        public abstract record AccessCodeWarnings
        {
            /// <summary>The value of the <c>warning_code</c> discriminator.</summary>
            public abstract string WarningCode { get; }

            /// <summary>
            /// Date and time at which Seam created the warning.
            /// </summary>
            [JsonPropertyName("created_at")]
            public string? CreatedAt { get; init; }

            /// <summary>
            /// Detailed description of the warning. Provides insights into the issue and potentially how to rectify it.
            /// </summary>
            [JsonPropertyName("message")]
            public string Message { get; init; } = default!;
        }

        public sealed record AccessCodeWarningsCodeRotatesPeriodically : AccessCodeWarnings
        {
            [JsonPropertyName("warning_code")]
            public override string WarningCode { get; } = "code_rotates_periodically";
        }

        public sealed record AccessCodeWarningsTimeFrameAdjustedForUnknownTimeZone
            : AccessCodeWarnings
        {
            [JsonPropertyName("warning_code")]
            public override string WarningCode { get; } =
                "time_frame_adjusted_for_unknown_time_zone";
        }

        public sealed record AccessCodeWarningsExternalModificationInEffect : AccessCodeWarnings
        {
            /// <summary>
            /// Indicates the type of external modification. `modified` means the code&apos;s PIN or schedule was changed. `removed` means the code was deleted from the device.
            /// </summary>
            [JsonConverter(typeof(SeamStringEnumConverter))]
            public enum ChangeTypeEnum
            {
                [EnumMember(Value = "unrecognized")]
                Unrecognized = 0,

                [EnumMember(Value = "modified")]
                Modified = 1,

                [EnumMember(Value = "removed")]
                Removed = 2,
            }

            [JsonPropertyName("warning_code")]
            public override string WarningCode { get; } = "external_modification_in_effect";

            /// <summary>
            /// Indicates the type of external modification. `modified` means the code&apos;s PIN or schedule was changed. `removed` means the code was deleted from the device.
            /// </summary>
            [JsonPropertyName("change_type")]
            public AccessCodeWarningsExternalModificationInEffect.ChangeTypeEnum? ChangeType { get; init; }

            /// <summary>
            /// List of fields that were changed externally, with their previous and new values.
            /// </summary>
            [JsonPropertyName("modified_fields")]
            public List<AccessCodeWarningsExternalModificationInEffectModifiedFields>? ModifiedFields { get; init; }
        }

        public sealed record AccessCodeWarningsExternalModificationInEffectModifiedFields
        {
            /// <summary>
            /// The name of the field that was changed (e.g. `code`, `starts_at`, `ends_at`).
            /// </summary>
            [JsonPropertyName("field")]
            public string Field { get; init; } = default!;

            /// <summary>
            /// The previous value of the field.
            /// </summary>
            [JsonPropertyName("from")]
            public string? From { get; init; }

            /// <summary>
            /// The new value of the field.
            /// </summary>
            [JsonPropertyName("to")]
            public string? To { get; init; }
        }

        public sealed record AccessCodeWarningsDelayInSettingOnDevice : AccessCodeWarnings
        {
            [JsonPropertyName("warning_code")]
            public override string WarningCode { get; } = "delay_in_setting_on_device";
        }

        public sealed record AccessCodeWarningsDelayInRemovingFromDevice : AccessCodeWarnings
        {
            [JsonPropertyName("warning_code")]
            public override string WarningCode { get; } = "delay_in_removing_from_device";
        }

        public sealed record AccessCodeWarningsDelayInIssuing : AccessCodeWarnings
        {
            [JsonPropertyName("warning_code")]
            public override string WarningCode { get; } = "delay_in_issuing";
        }

        public sealed record AccessCodeWarningsDelayInApplyingMutations : AccessCodeWarnings
        {
            [JsonPropertyName("warning_code")]
            public override string WarningCode { get; } = "delay_in_applying_mutations";
        }

        public sealed record AccessCodeWarningsThirdPartyIntegrationDetected : AccessCodeWarnings
        {
            [JsonPropertyName("warning_code")]
            public override string WarningCode { get; } = "third_party_integration_detected";
        }

        public sealed record AccessCodeWarningsIglooAlgopinMustBeUsedWithin_24Hours
            : AccessCodeWarnings
        {
            [JsonPropertyName("warning_code")]
            public override string WarningCode { get; } =
                "igloo_algopin_must_be_used_within_24_hours";
        }

        public sealed record AccessCodeWarningsManagementTransferred : AccessCodeWarnings
        {
            [JsonPropertyName("warning_code")]
            public override string WarningCode { get; } = "management_transferred";
        }

        public sealed record AccessCodeWarningsUsingBackupAccessCode : AccessCodeWarnings
        {
            [JsonPropertyName("warning_code")]
            public override string WarningCode { get; } = "using_backup_access_code";
        }

        public sealed record AccessCodeWarningsBeingDeleted : AccessCodeWarnings
        {
            [JsonPropertyName("warning_code")]
            public override string WarningCode { get; } = "being_deleted";
        }

        public sealed record AccessCodeWarningsUnknownIssueWithAccessCode : AccessCodeWarnings
        {
            [JsonPropertyName("warning_code")]
            public override string WarningCode { get; } = "unknown_issue_with_access_code";
        }

        public sealed record AccessCodeWarningsUnrecognized
            : AccessCodeWarnings,
                ISeamUnrecognizedVariant
        {
            [JsonPropertyName("warning_code")]
            public override string WarningCode { get; } = "unrecognized";

            /// <summary>The complete raw JSON of the unrecognized payload.</summary>
            [JsonIgnore]
            public JsonElement RawJson { get; set; }
        }

        /// <summary>
        /// Unique identifier for the access code.
        /// </summary>
        [JsonPropertyName("access_code_id")]
        public string AccessCodeId { get; init; } = default!;

        /// <summary>
        /// Code used for access. Typically, a numeric or alphanumeric string.
        /// </summary>
        [JsonPropertyName("code")]
        public string? Code { get; init; }

        /// <summary>
        /// Unique identifier for a group of access codes that share the same code.
        /// </summary>
        [JsonPropertyName("common_code_key")]
        public string? CommonCodeKey { get; init; }

        /// <summary>
        /// Date and time at which the access code was created.
        /// </summary>
        [JsonPropertyName("created_at")]
        public string CreatedAt { get; init; } = default!;

        /// <summary>
        /// Unique identifier for the device associated with the access code.
        /// </summary>
        [JsonPropertyName("device_id")]
        public string DeviceId { get; init; } = default!;

        /// <summary>
        /// Metadata for a dormakaba Oracode managed access code. Only present for access codes from dormakaba Oracode devices.
        /// </summary>
        [JsonPropertyName("dormakaba_oracode_metadata")]
        public AccessCodeDormakabaOracodeMetadata? DormakabaOracodeMetadata { get; init; }

        /// <summary>
        /// Date and time after which the time-bound access code becomes inactive.
        /// </summary>
        [JsonPropertyName("ends_at")]
        public string? EndsAt { get; init; }

        /// <summary>
        /// Errors associated with the [access code](https://docs.seam.co/low-level-apis/smart-locks/access-codes).
        /// </summary>
        [JsonPropertyName("errors")]
        public List<AccessCodeErrors> Errors { get; init; } = default!;

        /// <summary>
        /// Indicates whether the access code is a backup code.
        /// </summary>
        [JsonPropertyName("is_backup")]
        public bool? IsBackup { get; init; }

        /// <summary>
        /// Indicates whether a backup access code is available for use if the primary access code is lost or compromised.
        /// </summary>
        [JsonPropertyName("is_backup_access_code_available")]
        public bool IsBackupAccessCodeAvailable { get; init; } = default!;

        /// <summary>
        /// Indicates whether changes to the access code from external sources are permitted.
        /// </summary>
        [JsonPropertyName("is_external_modification_allowed")]
        public bool IsExternalModificationAllowed { get; init; } = default!;

        /// <summary>
        /// Indicates whether Seam manages the access code.
        /// </summary>
        [JsonPropertyName("is_managed")]
        public bool IsManaged { get; init; } = default!;

        /// <summary>
        /// Indicates whether the access code is intended for use in offline scenarios. If `true`, this code can be created on a device without a network connection.
        /// </summary>
        [JsonPropertyName("is_offline_access_code")]
        public bool IsOfflineAccessCode { get; init; } = default!;

        /// <summary>
        /// Indicates whether the access code can only be used once. If `true`, the code becomes invalid after the first use.
        /// </summary>
        [JsonPropertyName("is_one_time_use")]
        public bool IsOneTimeUse { get; init; } = default!;

        /// <summary>
        /// Indicates whether the code is set on the device according to a preconfigured schedule.
        /// </summary>
        [JsonPropertyName("is_scheduled_on_device")]
        public bool? IsScheduledOnDevice { get; init; }

        /// <summary>
        /// Indicates whether the access code is waiting for a code assignment.
        /// </summary>
        [JsonPropertyName("is_waiting_for_code_assignment")]
        public bool? IsWaitingForCodeAssignment { get; init; }

        /// <summary>
        /// Name of the access code. Enables administrators and users to identify the access code easily, especially when there are numerous access codes. Note that the name provided on Seam is used to identify the code on Seam and is not necessarily the name that will appear in the lock provider&apos;s app or on the device. This is because lock providers may have constraints on names, such as length, uniqueness, or characters that can be used. In addition, some lock providers may break down names into components such as `first_name` and `last_name`. To provide a consistent experience, Seam identifies the code on Seam by its name but may modify the name that appears on the lock provider&apos;s app or on the device. For example, Seam may add additional characters or truncate the name to meet provider constraints. To help your users identify codes set by Seam, Seam provides the name exactly as it appears on the lock provider&apos;s app or on the device as a separate property called `appearance`. This is an object with a `name` property and, optionally, `first_name` and `last_name` properties (for providers that break down a name into components).
        /// </summary>
        [JsonPropertyName("name")]
        public string? Name { get; init; }

        /// <summary>
        /// Collection of pending mutations for the access code. Indicates changes that Seam is in the process of pushing to the device.
        /// </summary>
        [JsonPropertyName("pending_mutations")]
        public List<AccessCodePendingMutations> PendingMutations { get; init; } = default!;

        /// <summary>
        /// Identifier of the pulled backup access code. Used to associate the pulled backup access code with the original access code.
        /// </summary>
        [JsonPropertyName("pulled_backup_access_code_id")]
        public string? PulledBackupAccessCodeId { get; init; }

        /// <summary>
        /// Date and time at which the time-bound access code becomes active.
        /// </summary>
        [JsonPropertyName("starts_at")]
        public string? StartsAt { get; init; }

        /// <summary>
        /// Current status of the access code within the operational lifecycle. Values are `setting`, a transitional phase that indicates that the code is being configured or activated; `set`, which indicates that the code is active and operational; `unset`, which indicates a deactivated or unused state, either before activation or after deliberate deactivation; `removing`, which indicates a transitional period in which the code is being deleted or made inactive; and `unknown`, which indicates an indeterminate state, due to reasons such as system errors or incomplete data, that highlights a potential need for system review or troubleshooting. See also [Lifecycle of Access Codes](https://docs.seam.co/low-level-apis/smart-locks/access-codes/lifecycle-of-access-codes).
        /// </summary>
        [JsonPropertyName("status")]
        public AccessCode.StatusEnum Status { get; init; } = default!;

        /// <summary>
        /// Type of the access code. `ongoing` access codes are active continuously until deactivated manually. `time_bound` access codes have a specific duration.
        /// </summary>
        [JsonPropertyName("type")]
        public AccessCode.TypeEnum Type { get; init; } = default!;

        /// <summary>
        /// Warnings associated with the [access code](https://docs.seam.co/low-level-apis/smart-locks/access-codes).
        /// </summary>
        [JsonPropertyName("warnings")]
        public List<AccessCodeWarnings> Warnings { get; init; } = default!;

        /// <summary>
        /// Unique identifier for the Seam workspace associated with the access code.
        /// </summary>
        [JsonPropertyName("workspace_id")]
        public string WorkspaceId { get; init; } = default!;
    }

    public sealed record AccessCodeDormakabaOracodeMetadata
    {
        /// <summary>
        /// Indicates whether the stay can be cancelled via the Dormakaba Oracode API.
        /// </summary>
        [JsonPropertyName("is_cancellable")]
        public bool? IsCancellable { get; init; }

        /// <summary>
        /// Indicates whether early check-in is available for this stay.
        /// </summary>
        [JsonPropertyName("is_early_checkin_able")]
        public bool? IsEarlyCheckinAble { get; init; }

        /// <summary>
        /// Indicates whether the stay can be extended via the Dormakaba Oracode API.
        /// </summary>
        [JsonPropertyName("is_extendable")]
        public bool? IsExtendable { get; init; }

        /// <summary>
        /// Indicates whether the access code can be overridden. When false, the maximum number of overrides has been reached.
        /// </summary>
        [JsonPropertyName("is_overridable")]
        public bool? IsOverridable { get; init; }

        /// <summary>
        /// Dormakaba Oracode site name associated with this access code.
        /// </summary>
        [JsonPropertyName("site_name")]
        public string? SiteName { get; init; }

        /// <summary>
        /// Dormakaba Oracode stay ID associated with this access code.
        /// </summary>
        [JsonPropertyName("stay_id")]
        public float? StayId { get; init; }

        /// <summary>
        /// Dormakaba Oracode user level ID associated with this access code.
        /// </summary>
        [JsonPropertyName("user_level_id")]
        public string? UserLevelId { get; init; }

        /// <summary>
        /// Dormakaba Oracode user level name associated with this access code.
        /// </summary>
        [JsonPropertyName("user_level_name")]
        public string? UserLevelName { get; init; }
    }
}
