// <auto-generated>
//   Generated by codegen/smith.ts from @seamapi/types. Do not edit.
// </auto-generated>
#nullable enable
#pragma warning disable CS0618 // The generated code references its own deprecated members.
using System.Runtime.Serialization;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Seam.Models
{
    /// <summary>
    /// Means by which an [access control system user](https://docs.seam.co/low-level-apis/access-systems/user-management) gains access at an [entrance](https://docs.seam.co/low-level-apis/access-systems/retrieving-entrance-details). The `acs_credential` object represents a [credential](https://docs.seam.co/low-level-apis/access-systems/managing-credentials) that provides an ACS user access within an [access control system](https://docs.seam.co/low-level-apis/access-systems).
    ///
    /// An access control system generally uses digital means of access to authorize a user trying to get through a specific entrance. Examples of credentials include plastic key cards, mobile keys, biometric identifiers, and PIN codes. The electronic nature of these credentials, as well as the fact that access is centralized, enables both the rapid provisioning and rescinding of access and the ability to compile access audit logs.
    ///
    /// For each `acs_credential`, you define the access method. You can also specify additional properties, such as a PIN code, depending on the credential type.
    ///
    /// For granting a person access to a space, [Access Grants](https://docs.seam.co/use-cases/granting-access) are the default and recommended approach. Use the lower-level ACS credential API directly only when you specifically need to manage individual credentials.
    /// </summary>
    public sealed record AcsCredential
    {
        /// <summary>
        /// Access method for the [credential](https://docs.seam.co/low-level-apis/access-systems/managing-credentials). Supported values: `code`, `card`, `mobile_key`, `cloud_key`.
        /// </summary>
        [JsonConverter(typeof(SeamStringEnumConverter))]
        public enum AccessMethodEnum
        {
            [EnumMember(Value = "unrecognized")]
            Unrecognized = 0,

            [EnumMember(Value = "code")]
            Code = 1,

            [EnumMember(Value = "card")]
            Card = 2,

            [EnumMember(Value = "mobile_key")]
            MobileKey = 3,

            [EnumMember(Value = "cloud_key")]
            CloudKey = 4,
        }

        /// <summary>
        /// Brand-specific terminology for the [credential](https://docs.seam.co/low-level-apis/access-systems/managing-credentials) type. Supported values: `pti_card`, `brivo_credential`, `hid_credential`, `visionline_card`.
        /// </summary>
        [JsonConverter(typeof(SeamStringEnumConverter))]
        public enum ExternalTypeEnum
        {
            [EnumMember(Value = "unrecognized")]
            Unrecognized = 0,

            [EnumMember(Value = "pti_card")]
            PtiCard = 1,

            [EnumMember(Value = "brivo_credential")]
            BrivoCredential = 2,

            [EnumMember(Value = "hid_credential")]
            HidCredential = 3,

            [EnumMember(Value = "visionline_card")]
            VisionlineCard = 4,

            [EnumMember(Value = "salto_ks_credential")]
            SaltoKsCredential = 5,

            [EnumMember(Value = "assa_abloy_vostio_key")]
            AssaAbloyVostioKey = 6,

            [EnumMember(Value = "salto_space_key")]
            SaltoSpaceKey = 7,

            [EnumMember(Value = "latch_access")]
            LatchAccess = 8,

            [EnumMember(Value = "dormakaba_ambiance_credential")]
            DormakabaAmbianceCredential = 9,

            [EnumMember(Value = "hotek_card")]
            HotekCard = 10,

            [EnumMember(Value = "salto_ks_tag")]
            SaltoKsTag = 11,

            [EnumMember(Value = "avigilon_alta_credential")]
            AvigilonAltaCredential = 12,

            [EnumMember(Value = "kisi_credential")]
            KisiCredential = 13,

            [EnumMember(Value = "akiles_credential")]
            AkilesCredential = 14,
        }

        [JsonConverter(typeof(SeamUnionConverter))]
        [SeamUnion("warning_code")]
        [SeamUnionVariant("waiting_to_be_issued", typeof(AcsCredentialWarningsWaitingToBeIssued))]
        [SeamUnionVariant(
            "schedule_externally_modified",
            typeof(AcsCredentialWarningsScheduleExternallyModified)
        )]
        [SeamUnionVariant("schedule_modified", typeof(AcsCredentialWarningsScheduleModified))]
        [SeamUnionVariant("being_deleted", typeof(AcsCredentialWarningsBeingDeleted))]
        [SeamUnionVariant(
            "unknown_issue_with_acs_credential",
            typeof(AcsCredentialWarningsUnknownIssueWithAcsCredential)
        )]
        [SeamUnionVariant("needs_to_be_reissued", typeof(AcsCredentialWarningsNeedsToBeReissued))]
        [SeamUnionVariant(
            "requested_code_unavailable",
            typeof(AcsCredentialWarningsRequestedCodeUnavailable)
        )]
        [SeamUnionFallback(typeof(AcsCredentialWarningsUnrecognized))]
        public abstract record AcsCredentialWarnings
        {
            /// <summary>The value of the <c>warning_code</c> discriminator.</summary>
            public abstract string WarningCode { get; }

            /// <summary>
            /// Date and time at which Seam created the warning.
            /// </summary>
            [JsonPropertyName("created_at")]
            public string CreatedAt { get; init; } = default!;

            /// <summary>
            /// Detailed description of the warning. Provides insights into the issue and potentially how to rectify it.
            /// </summary>
            [JsonPropertyName("message")]
            public string Message { get; init; } = default!;
        }

        public sealed record AcsCredentialWarningsWaitingToBeIssued : AcsCredentialWarnings
        {
            [JsonPropertyName("warning_code")]
            public override string WarningCode { get; } = "waiting_to_be_issued";
        }

        public sealed record AcsCredentialWarningsScheduleExternallyModified : AcsCredentialWarnings
        {
            [JsonPropertyName("warning_code")]
            public override string WarningCode { get; } = "schedule_externally_modified";
        }

        public sealed record AcsCredentialWarningsScheduleModified : AcsCredentialWarnings
        {
            [JsonPropertyName("warning_code")]
            public override string WarningCode { get; } = "schedule_modified";
        }

        public sealed record AcsCredentialWarningsBeingDeleted : AcsCredentialWarnings
        {
            [JsonPropertyName("warning_code")]
            public override string WarningCode { get; } = "being_deleted";
        }

        public sealed record AcsCredentialWarningsUnknownIssueWithAcsCredential
            : AcsCredentialWarnings
        {
            [JsonPropertyName("warning_code")]
            public override string WarningCode { get; } = "unknown_issue_with_acs_credential";
        }

        public sealed record AcsCredentialWarningsNeedsToBeReissued : AcsCredentialWarnings
        {
            [JsonPropertyName("warning_code")]
            public override string WarningCode { get; } = "needs_to_be_reissued";
        }

        public sealed record AcsCredentialWarningsRequestedCodeUnavailable : AcsCredentialWarnings
        {
            [JsonPropertyName("warning_code")]
            public override string WarningCode { get; } = "requested_code_unavailable";

            /// <summary>
            /// The PIN code that was assigned instead.
            /// </summary>
            [JsonPropertyName("new_code")]
            public string NewCode { get; init; } = default!;

            /// <summary>
            /// The originally requested PIN code that could not be used.
            /// </summary>
            [JsonPropertyName("original_code")]
            public string OriginalCode { get; init; } = default!;
        }

        public sealed record AcsCredentialWarningsUnrecognized
            : AcsCredentialWarnings,
                ISeamUnrecognizedVariant
        {
            [JsonPropertyName("warning_code")]
            public override string WarningCode { get; } = "unrecognized";

            /// <summary>The complete raw JSON of the unrecognized payload.</summary>
            [JsonIgnore]
            public JsonElement RawJson { get; set; }
        }

        /// <summary>
        /// Access method for the [credential](https://docs.seam.co/low-level-apis/access-systems/managing-credentials). Supported values: `code`, `card`, `mobile_key`, `cloud_key`.
        /// </summary>
        [JsonPropertyName("access_method")]
        public AcsCredential.AccessMethodEnum AccessMethod { get; init; } = default!;

        /// <summary>
        /// ID of the [credential](https://docs.seam.co/low-level-apis/access-systems/managing-credentials).
        /// </summary>
        [JsonPropertyName("acs_credential_id")]
        public string AcsCredentialId { get; init; } = default!;

        /// <summary>
        /// ID of the credential pool to which the credential belongs.
        /// </summary>
        [JsonPropertyName("acs_credential_pool_id")]
        public string? AcsCredentialPoolId { get; init; }

        /// <summary>
        /// ID of the [access control system](https://docs.seam.co/low-level-apis/access-systems) that contains the [credential](https://docs.seam.co/low-level-apis/access-systems/managing-credentials).
        /// </summary>
        [JsonPropertyName("acs_system_id")]
        public string AcsSystemId { get; init; } = default!;

        /// <summary>
        /// ID of the [ACS user](https://docs.seam.co/low-level-apis/access-systems/user-management) to whom the [credential](https://docs.seam.co/low-level-apis/access-systems/managing-credentials) belongs.
        /// </summary>
        [JsonPropertyName("acs_user_id")]
        public string? AcsUserId { get; init; }

        /// <summary>
        /// Akiles-specific metadata for the [credential](https://docs.seam.co/low-level-apis/access-systems/managing-credentials).
        /// </summary>
        [JsonPropertyName("akiles_metadata")]
        public AcsCredentialAkilesMetadata? AkilesMetadata { get; init; }

        /// <summary>
        /// Vostio-specific metadata for the [credential](https://docs.seam.co/low-level-apis/access-systems/managing-credentials).
        /// </summary>
        [JsonPropertyName("assa_abloy_vostio_metadata")]
        public AcsCredentialAssaAbloyVostioMetadata? AssaAbloyVostioMetadata { get; init; }

        /// <summary>
        /// Number of the card associated with the [credential](https://docs.seam.co/low-level-apis/access-systems/managing-credentials).
        /// </summary>
        [JsonPropertyName("card_number")]
        public string? CardNumber { get; init; }

        /// <summary>
        /// Access (PIN) code for the [credential](https://docs.seam.co/low-level-apis/access-systems/managing-credentials).
        /// </summary>
        [JsonPropertyName("code")]
        public string? Code { get; init; }

        /// <summary>
        /// ID of the [connected account](https://docs.seam.co/core-concepts/connected-accounts) to which the [credential](https://docs.seam.co/low-level-apis/access-systems/managing-credentials) belongs.
        /// </summary>
        [JsonPropertyName("connected_account_id")]
        public string ConnectedAccountId { get; init; } = default!;

        /// <summary>
        /// Date and time at which the [credential](https://docs.seam.co/low-level-apis/access-systems/managing-credentials) was created.
        /// </summary>
        [JsonPropertyName("created_at")]
        public string CreatedAt { get; init; } = default!;

        /// <summary>
        /// Display name that corresponds to the [credential](https://docs.seam.co/low-level-apis/access-systems/managing-credentials) type.
        /// </summary>
        [JsonPropertyName("display_name")]
        public string DisplayName { get; init; } = default!;

        /// <summary>
        /// Date and time at which the [credential](https://docs.seam.co/low-level-apis/access-systems/managing-credentials) validity ends, in [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html) format. Must be a time in the future and after `starts_at`.
        /// </summary>
        [JsonPropertyName("ends_at")]
        public string? EndsAt { get; init; }

        /// <summary>
        /// Errors associated with the [credential](https://docs.seam.co/low-level-apis/access-systems/managing-credentials).
        /// </summary>
        [JsonPropertyName("errors")]
        public List<AcsCredentialErrors> Errors { get; init; } = default!;

        /// <summary>
        /// Brand-specific terminology for the [credential](https://docs.seam.co/low-level-apis/access-systems/managing-credentials) type. Supported values: `pti_card`, `brivo_credential`, `hid_credential`, `visionline_card`.
        /// </summary>
        [JsonPropertyName("external_type")]
        public AcsCredential.ExternalTypeEnum? ExternalType { get; init; }

        /// <summary>
        /// Display name that corresponds to the brand-specific terminology for the [credential](https://docs.seam.co/low-level-apis/access-systems/managing-credentials) type.
        /// </summary>
        [JsonPropertyName("external_type_display_name")]
        public string? ExternalTypeDisplayName { get; init; }

        /// <summary>
        /// Indicates whether the [credential](https://docs.seam.co/low-level-apis/access-systems/managing-credentials) has been encoded onto a card.
        /// </summary>
        [JsonPropertyName("is_issued")]
        public bool? IsIssued { get; init; }

        /// <summary>
        /// Indicates whether the latest state of the [credential](https://docs.seam.co/low-level-apis/access-systems/managing-credentials) has been synced from Seam to the provider.
        /// </summary>
        [JsonPropertyName("is_latest_desired_state_synced_with_provider")]
        public bool? IsLatestDesiredStateSyncedWithProvider { get; init; }

        /// <summary>
        /// Indicates whether Seam manages the credential.
        /// </summary>
        [JsonPropertyName("is_managed")]
        public bool IsManaged { get; init; } = default!;

        /// <summary>
        /// Indicates whether the [credential](https://docs.seam.co/low-level-apis/access-systems/managing-credentials) is a [multi-phone sync credential](https://docs.seam.co/capability-guides/mobile-access/issuing-mobile-credentials-from-an-access-control-system#what-are-multi-phone-sync-credentials).
        /// </summary>
        [JsonPropertyName("is_multi_phone_sync_credential")]
        public bool? IsMultiPhoneSyncCredential { get; init; }

        /// <summary>
        /// Indicates whether the [credential](https://docs.seam.co/low-level-apis/access-systems/managing-credentials) can only be used once. If `true`, the code becomes invalid after the first use.
        /// </summary>
        [JsonPropertyName("is_one_time_use")]
        public bool? IsOneTimeUse { get; init; }

        /// <summary>
        /// Date and time at which the [credential](https://docs.seam.co/low-level-apis/access-systems/managing-credentials) was encoded onto a card.
        /// </summary>
        [JsonPropertyName("issued_at")]
        public string? IssuedAt { get; init; }

        /// <summary>
        /// Date and time at which the state of the [credential](https://docs.seam.co/low-level-apis/access-systems/managing-credentials) was most recently synced from Seam to the provider.
        /// </summary>
        [JsonPropertyName("latest_desired_state_synced_with_provider_at")]
        public string? LatestDesiredStateSyncedWithProviderAt { get; init; }

        /// <summary>
        /// ID of the parent [credential](https://docs.seam.co/low-level-apis/access-systems/managing-credentials).
        /// </summary>
        [JsonPropertyName("parent_acs_credential_id")]
        public string? ParentAcsCredentialId { get; init; }

        /// <summary>
        /// Date and time at which the [credential](https://docs.seam.co/low-level-apis/access-systems/managing-credentials) validity starts, in [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html) format.
        /// </summary>
        [JsonPropertyName("starts_at")]
        public string? StartsAt { get; init; }

        /// <summary>
        /// ID of the [user identity](https://docs.seam.co/api/user_identities) to whom the [credential](https://docs.seam.co/low-level-apis/access-systems/managing-credentials) belongs.
        /// </summary>
        [JsonPropertyName("user_identity_id")]
        public string? UserIdentityId { get; init; }

        /// <summary>
        /// Visionline-specific metadata for the [credential](https://docs.seam.co/low-level-apis/access-systems/managing-credentials).
        /// </summary>
        [JsonPropertyName("visionline_metadata")]
        public AcsCredentialVisionlineMetadata? VisionlineMetadata { get; init; }

        /// <summary>
        /// Warnings associated with the [credential](https://docs.seam.co/low-level-apis/access-systems/managing-credentials).
        /// </summary>
        [JsonPropertyName("warnings")]
        public List<AcsCredentialWarnings> Warnings { get; init; } = default!;

        /// <summary>
        /// ID of the workspace that contains the [credential](https://docs.seam.co/low-level-apis/access-systems/managing-credentials).
        /// </summary>
        [JsonPropertyName("workspace_id")]
        public string WorkspaceId { get; init; } = default!;
    }

    public sealed record AcsCredentialAkilesMetadata
    {
        /// <summary>
        /// ID of the Akiles member PIN.
        /// </summary>
        [JsonPropertyName("member_pin_id")]
        public string? MemberPinId { get; init; }
    }

    public sealed record AcsCredentialAssaAbloyVostioMetadata
    {
        /// <summary>
        /// Indicates whether the credential should auto-join. For an auto-join credential, Seam automatically issues an override card if there are no other cards and a joiner card if there are existing cards on the doors.
        /// </summary>
        [JsonPropertyName("auto_join")]
        public bool? AutoJoin { get; init; }

        /// <summary>
        /// Names of the doors to which to grant access in the Vostio access system.
        /// </summary>
        [JsonPropertyName("door_names")]
        public List<string>? DoorNames { get; init; }

        /// <summary>
        /// Endpoint ID in the Vostio access system.
        /// </summary>
        [JsonPropertyName("endpoint_id")]
        public string? EndpointId { get; init; }

        /// <summary>
        /// Key ID in the Vostio access system.
        /// </summary>
        [JsonPropertyName("key_id")]
        public string? KeyId { get; init; }

        /// <summary>
        /// Key issuing request ID in the Vostio access system.
        /// </summary>
        [JsonPropertyName("key_issuing_request_id")]
        public string? KeyIssuingRequestId { get; init; }

        /// <summary>
        /// IDs of the guest entrances to override in the Vostio access system.
        /// </summary>
        [JsonPropertyName("override_guest_acs_entrance_ids")]
        public List<string>? OverrideGuestAcsEntranceIds { get; init; }
    }

    public sealed record AcsCredentialErrors
    {
        /// <summary>
        /// Date and time at which Seam created the error.
        /// </summary>
        [JsonPropertyName("created_at")]
        public string CreatedAt { get; init; } = default!;

        [JsonPropertyName("error_code")]
        public string ErrorCode { get; init; } = default!;

        [JsonPropertyName("message")]
        public string Message { get; init; } = default!;
    }

    public sealed record AcsCredentialVisionlineMetadata
    {
        /// <summary>
        /// Card function type in the Visionline access system.
        /// </summary>
        [JsonConverter(typeof(SeamStringEnumConverter))]
        public enum CardFunctionTypeEnum
        {
            [EnumMember(Value = "unrecognized")]
            Unrecognized = 0,

            [EnumMember(Value = "guest")]
            Guest = 1,

            [EnumMember(Value = "staff")]
            Staff = 2,
        }

        /// <summary>
        /// Indicates whether the credential should auto-join. For an auto-join credential, Seam automatically issues an override card if there are no other cards and a joiner card if there are existing cards on the doors.
        /// </summary>
        [JsonPropertyName("auto_join")]
        public bool? AutoJoin { get; init; }

        /// <summary>
        /// Card function type in the Visionline access system.
        /// </summary>
        [JsonPropertyName("card_function_type")]
        public AcsCredentialVisionlineMetadata.CardFunctionTypeEnum? CardFunctionType { get; init; }

        /// <summary>
        /// ID of the card in the Visionline access system.
        /// </summary>
        [JsonPropertyName("card_id")]
        public string? CardId { get; init; }

        /// <summary>
        /// Common entrance IDs in the Visionline access system.
        /// </summary>
        [JsonPropertyName("common_acs_entrance_ids")]
        public List<string>? CommonAcsEntranceIds { get; init; }

        /// <summary>
        /// ID of the credential in the Visionline access system.
        /// </summary>
        [JsonPropertyName("credential_id")]
        public string? CredentialId { get; init; }

        /// <summary>
        /// Guest entrance IDs in the Visionline access system.
        /// </summary>
        [JsonPropertyName("guest_acs_entrance_ids")]
        public List<string>? GuestAcsEntranceIds { get; init; }

        /// <summary>
        /// Indicates whether the credential is valid.
        /// </summary>
        [JsonPropertyName("is_valid")]
        public bool? IsValid { get; init; }

        /// <summary>
        /// IDs of the credentials to which you want to join.
        /// </summary>
        [JsonPropertyName("joiner_acs_credential_ids")]
        public List<string>? JoinerAcsCredentialIds { get; init; }
    }
}
