// <auto-generated>
//   Generated by codegen/smith.ts from @seamapi/types. Do not edit.
// </auto-generated>
#nullable enable
#pragma warning disable CS0618 // The generated code references its own deprecated members.
using System.Runtime.Serialization;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Seam.Models
{
    /// <summary>
    /// Represents a [user](https://docs.seam.co/low-level-apis/access-systems/user-management) in an [access system](https://docs.seam.co/low-level-apis/access-systems).
    ///
    /// An access system user typically refers to an individual who requires access, like an employee or resident. Each user can possess multiple credentials that serve as their keys or identifiers for access. The type of credential can vary widely. For example, in the Salto system, a user can have a PIN code, a mobile app account, and a fob. In other platforms, it is not uncommon for a user to have more than one of the same credential type, such as multiple key cards. Additionally, these credentials can have a schedule or validity period.
    ///
    /// For details about how to configure users in your access system, see the corresponding [system integration guide](https://docs.seam.co/device-and-system-integration-guides#access-control-systems).
    /// </summary>
    public sealed record AcsUser
    {
        [JsonConverter(typeof(SeamUnionConverter))]
        [SeamUnion("error_code")]
        [SeamUnionVariant("deleted_externally", typeof(AcsUserErrorsDeletedExternally))]
        [SeamUnionVariant(
            "salto_ks_subscription_limit_exceeded",
            typeof(AcsUserErrorsSaltoKsSubscriptionLimitExceeded)
        )]
        [SeamUnionVariant(
            "failed_to_create_on_acs_system",
            typeof(AcsUserErrorsFailedToCreateOnAcsSystem)
        )]
        [SeamUnionVariant(
            "failed_to_update_on_acs_system",
            typeof(AcsUserErrorsFailedToUpdateOnAcsSystem)
        )]
        [SeamUnionVariant(
            "failed_to_delete_on_acs_system",
            typeof(AcsUserErrorsFailedToDeleteOnAcsSystem)
        )]
        [SeamUnionVariant(
            "latch_conflict_with_resident_user",
            typeof(AcsUserErrorsLatchConflictWithResidentUser)
        )]
        [SeamUnionFallback(typeof(AcsUserErrorsUnrecognized))]
        public abstract record AcsUserErrors
        {
            /// <summary>The value of the <c>error_code</c> discriminator.</summary>
            public abstract string ErrorCode { get; }

            /// <summary>
            /// Date and time at which Seam created the error.
            /// </summary>
            [JsonPropertyName("created_at")]
            public string CreatedAt { get; init; } = default!;

            /// <summary>
            /// Detailed description of the error. Provides insights into the issue and potentially how to rectify it.
            /// </summary>
            [JsonPropertyName("message")]
            public string Message { get; init; } = default!;
        }

        public sealed record AcsUserErrorsDeletedExternally : AcsUserErrors
        {
            [JsonPropertyName("error_code")]
            public override string ErrorCode { get; } = "deleted_externally";
        }

        public sealed record AcsUserErrorsSaltoKsSubscriptionLimitExceeded : AcsUserErrors
        {
            [JsonPropertyName("error_code")]
            public override string ErrorCode { get; } = "salto_ks_subscription_limit_exceeded";
        }

        public sealed record AcsUserErrorsFailedToCreateOnAcsSystem : AcsUserErrors
        {
            [JsonPropertyName("error_code")]
            public override string ErrorCode { get; } = "failed_to_create_on_acs_system";
        }

        public sealed record AcsUserErrorsFailedToUpdateOnAcsSystem : AcsUserErrors
        {
            [JsonPropertyName("error_code")]
            public override string ErrorCode { get; } = "failed_to_update_on_acs_system";
        }

        public sealed record AcsUserErrorsFailedToDeleteOnAcsSystem : AcsUserErrors
        {
            [JsonPropertyName("error_code")]
            public override string ErrorCode { get; } = "failed_to_delete_on_acs_system";
        }

        public sealed record AcsUserErrorsLatchConflictWithResidentUser : AcsUserErrors
        {
            [JsonPropertyName("error_code")]
            public override string ErrorCode { get; } = "latch_conflict_with_resident_user";
        }

        public sealed record AcsUserErrorsUnrecognized : AcsUserErrors, ISeamUnrecognizedVariant
        {
            [JsonPropertyName("error_code")]
            public override string ErrorCode { get; } = "unrecognized";

            /// <summary>The complete raw JSON of the unrecognized payload.</summary>
            [JsonIgnore]
            public JsonElement RawJson { get; set; }
        }

        /// <summary>
        /// Brand-specific terminology for the [access system user](https://docs.seam.co/low-level-apis/access-systems/user-management) type.
        /// </summary>
        [JsonConverter(typeof(SeamStringEnumConverter))]
        public enum ExternalTypeEnum
        {
            [EnumMember(Value = "unrecognized")]
            Unrecognized = 0,

            [EnumMember(Value = "pti_user")]
            PtiUser = 1,

            [EnumMember(Value = "brivo_user")]
            BrivoUser = 2,

            [EnumMember(Value = "hid_credential_manager_user")]
            HidCredentialManagerUser = 3,

            [EnumMember(Value = "salto_site_user")]
            SaltoSiteUser = 4,

            [EnumMember(Value = "latch_user")]
            LatchUser = 5,

            [EnumMember(Value = "dormakaba_community_user")]
            DormakabaCommunityUser = 6,

            [EnumMember(Value = "salto_space_user")]
            SaltoSpaceUser = 7,

            [EnumMember(Value = "avigilon_alta_user")]
            AvigilonAltaUser = 8,

            [EnumMember(Value = "kisi_user")]
            KisiUser = 9,
        }

        [JsonConverter(typeof(SeamUnionConverter))]
        [SeamUnion("mutation_code")]
        [SeamUnionVariant("creating", typeof(AcsUserPendingMutationsCreating))]
        [SeamUnionVariant("deleting", typeof(AcsUserPendingMutationsDeleting))]
        [SeamUnionVariant("deferring_creation", typeof(AcsUserPendingMutationsDeferringCreation))]
        [SeamUnionVariant(
            "updating_user_information",
            typeof(AcsUserPendingMutationsUpdatingUserInformation)
        )]
        [SeamUnionVariant(
            "updating_access_schedule",
            typeof(AcsUserPendingMutationsUpdatingAccessSchedule)
        )]
        [SeamUnionVariant(
            "updating_suspension_state",
            typeof(AcsUserPendingMutationsUpdatingSuspensionState)
        )]
        [SeamUnionVariant(
            "updating_group_membership",
            typeof(AcsUserPendingMutationsUpdatingGroupMembership)
        )]
        [SeamUnionVariant(
            "deferring_group_membership_update",
            typeof(AcsUserPendingMutationsDeferringGroupMembershipUpdate)
        )]
        [SeamUnionVariant(
            "updating_credential_assignment",
            typeof(AcsUserPendingMutationsUpdatingCredentialAssignment)
        )]
        [SeamUnionFallback(typeof(AcsUserPendingMutationsUnrecognized))]
        public abstract record AcsUserPendingMutations
        {
            /// <summary>The value of the <c>mutation_code</c> discriminator.</summary>
            public abstract string MutationCode { get; }

            /// <summary>
            /// Date and time at which the mutation was created.
            /// </summary>
            [JsonPropertyName("created_at")]
            public string CreatedAt { get; init; } = default!;

            /// <summary>
            /// Detailed description of the mutation.
            /// </summary>
            [JsonPropertyName("message")]
            public string Message { get; init; } = default!;
        }

        public sealed record AcsUserPendingMutationsCreating : AcsUserPendingMutations
        {
            [JsonPropertyName("mutation_code")]
            public override string MutationCode { get; } = "creating";
        }

        public sealed record AcsUserPendingMutationsDeleting : AcsUserPendingMutations
        {
            [JsonPropertyName("mutation_code")]
            public override string MutationCode { get; } = "deleting";
        }

        public sealed record AcsUserPendingMutationsDeferringCreation : AcsUserPendingMutations
        {
            [JsonPropertyName("mutation_code")]
            public override string MutationCode { get; } = "deferring_creation";

            /// <summary>
            /// Optional: When the user creation is scheduled to occur.
            /// </summary>
            [JsonPropertyName("scheduled_at")]
            public string? ScheduledAt { get; init; }
        }

        public sealed record AcsUserPendingMutationsUpdatingUserInformation
            : AcsUserPendingMutations
        {
            [JsonPropertyName("mutation_code")]
            public override string MutationCode { get; } = "updating_user_information";

            /// <summary>
            /// Old access system user information.
            /// </summary>
            [JsonPropertyName("from")]
            public AcsUserPendingMutationsUpdatingUserInformationFrom From { get; init; } =
                default!;

            /// <summary>
            /// New access system user information.
            /// </summary>
            [JsonPropertyName("to")]
            public AcsUserPendingMutationsUpdatingUserInformationTo To { get; init; } = default!;
        }

        public sealed record AcsUserPendingMutationsUpdatingUserInformationFrom
        {
            /// <summary>
            /// Email address of the access system user.
            /// </summary>
            [JsonPropertyName("email_address")]
            public string? EmailAddress { get; init; }

            /// <summary>
            /// Full name of the access system user.
            /// </summary>
            [JsonPropertyName("full_name")]
            public string? FullName { get; init; }

            /// <summary>
            /// Phone number of the access system user.
            /// </summary>
            [JsonPropertyName("phone_number")]
            public string? PhoneNumber { get; init; }
        }

        public sealed record AcsUserPendingMutationsUpdatingUserInformationTo
        {
            /// <summary>
            /// Email address of the access system user.
            /// </summary>
            [JsonPropertyName("email_address")]
            public string? EmailAddress { get; init; }

            /// <summary>
            /// Full name of the access system user.
            /// </summary>
            [JsonPropertyName("full_name")]
            public string? FullName { get; init; }

            /// <summary>
            /// Phone number of the access system user.
            /// </summary>
            [JsonPropertyName("phone_number")]
            public string? PhoneNumber { get; init; }
        }

        public sealed record AcsUserPendingMutationsUpdatingAccessSchedule : AcsUserPendingMutations
        {
            [JsonPropertyName("mutation_code")]
            public override string MutationCode { get; } = "updating_access_schedule";

            /// <summary>
            /// Old access schedule information.
            /// </summary>
            [JsonPropertyName("from")]
            public AcsUserPendingMutationsUpdatingAccessScheduleFrom From { get; init; } = default!;

            /// <summary>
            /// New access schedule information.
            /// </summary>
            [JsonPropertyName("to")]
            public AcsUserPendingMutationsUpdatingAccessScheduleTo To { get; init; } = default!;
        }

        public sealed record AcsUserPendingMutationsUpdatingAccessScheduleFrom
        {
            /// <summary>
            /// Starting time for the access schedule.
            /// </summary>
            [JsonPropertyName("ends_at")]
            public string? EndsAt { get; init; }

            /// <summary>
            /// Starting time for the access schedule.
            /// </summary>
            [JsonPropertyName("starts_at")]
            public string? StartsAt { get; init; }
        }

        public sealed record AcsUserPendingMutationsUpdatingAccessScheduleTo
        {
            /// <summary>
            /// Starting time for the access schedule.
            /// </summary>
            [JsonPropertyName("ends_at")]
            public string? EndsAt { get; init; }

            /// <summary>
            /// Starting time for the access schedule.
            /// </summary>
            [JsonPropertyName("starts_at")]
            public string? StartsAt { get; init; }
        }

        public sealed record AcsUserPendingMutationsUpdatingSuspensionState
            : AcsUserPendingMutations
        {
            [JsonPropertyName("mutation_code")]
            public override string MutationCode { get; } = "updating_suspension_state";

            /// <summary>
            /// Old user suspension state information.
            /// </summary>
            [JsonPropertyName("from")]
            public AcsUserPendingMutationsUpdatingSuspensionStateFrom From { get; init; } =
                default!;

            /// <summary>
            /// New user suspension state information.
            /// </summary>
            [JsonPropertyName("to")]
            public AcsUserPendingMutationsUpdatingSuspensionStateTo To { get; init; } = default!;
        }

        public sealed record AcsUserPendingMutationsUpdatingSuspensionStateFrom
        {
            [JsonPropertyName("is_suspended")]
            public bool IsSuspended { get; init; } = default!;
        }

        public sealed record AcsUserPendingMutationsUpdatingSuspensionStateTo
        {
            [JsonPropertyName("is_suspended")]
            public bool IsSuspended { get; init; } = default!;
        }

        public sealed record AcsUserPendingMutationsUpdatingGroupMembership
            : AcsUserPendingMutations
        {
            [JsonPropertyName("mutation_code")]
            public override string MutationCode { get; } = "updating_group_membership";

            /// <summary>
            /// Old access group membership.
            /// </summary>
            [JsonPropertyName("from")]
            public AcsUserPendingMutationsUpdatingGroupMembershipFrom From { get; init; } =
                default!;

            /// <summary>
            /// New access group membership.
            /// </summary>
            [JsonPropertyName("to")]
            public AcsUserPendingMutationsUpdatingGroupMembershipTo To { get; init; } = default!;
        }

        public sealed record AcsUserPendingMutationsUpdatingGroupMembershipFrom
        {
            /// <summary>
            /// Old access group ID.
            /// </summary>
            [JsonPropertyName("acs_access_group_id")]
            public string? AcsAccessGroupId { get; init; }
        }

        public sealed record AcsUserPendingMutationsUpdatingGroupMembershipTo
        {
            /// <summary>
            /// New access group ID.
            /// </summary>
            [JsonPropertyName("acs_access_group_id")]
            public string? AcsAccessGroupId { get; init; }
        }

        public sealed record AcsUserPendingMutationsDeferringGroupMembershipUpdate
            : AcsUserPendingMutations
        {
            /// <summary>
            /// Whether the user is scheduled to be added to or removed from the access group.
            /// </summary>
            [JsonConverter(typeof(SeamStringEnumConverter))]
            public enum VariantEnum
            {
                [EnumMember(Value = "unrecognized")]
                Unrecognized = 0,

                [EnumMember(Value = "adding")]
                Adding = 1,

                [EnumMember(Value = "removing")]
                Removing = 2,
            }

            [JsonPropertyName("mutation_code")]
            public override string MutationCode { get; } = "deferring_group_membership_update";

            /// <summary>
            /// ID of the access group involved in the scheduled change.
            /// </summary>
            [JsonPropertyName("acs_access_group_id")]
            public string AcsAccessGroupId { get; init; } = default!;

            /// <summary>
            /// Whether the user is scheduled to be added to or removed from the access group.
            /// </summary>
            [JsonPropertyName("variant")]
            public AcsUserPendingMutationsDeferringGroupMembershipUpdate.VariantEnum Variant { get; init; } =
                default!;
        }

        public sealed record AcsUserPendingMutationsUpdatingCredentialAssignment
            : AcsUserPendingMutations
        {
            [JsonPropertyName("mutation_code")]
            public override string MutationCode { get; } = "updating_credential_assignment";

            /// <summary>
            /// Previous credential assignment.
            /// </summary>
            [JsonPropertyName("from")]
            public AcsUserPendingMutationsUpdatingCredentialAssignmentFrom From { get; init; } =
                default!;

            /// <summary>
            /// New credential assignment.
            /// </summary>
            [JsonPropertyName("to")]
            public AcsUserPendingMutationsUpdatingCredentialAssignmentTo To { get; init; } =
                default!;
        }

        public sealed record AcsUserPendingMutationsUpdatingCredentialAssignmentFrom
        {
            /// <summary>
            /// Previous credential ID.
            /// </summary>
            [JsonPropertyName("acs_credential_id")]
            public string? AcsCredentialId { get; init; }
        }

        public sealed record AcsUserPendingMutationsUpdatingCredentialAssignmentTo
        {
            /// <summary>
            /// New credential ID.
            /// </summary>
            [JsonPropertyName("acs_credential_id")]
            public string? AcsCredentialId { get; init; }
        }

        public sealed record AcsUserPendingMutationsUnrecognized
            : AcsUserPendingMutations,
                ISeamUnrecognizedVariant
        {
            [JsonPropertyName("mutation_code")]
            public override string MutationCode { get; } = "unrecognized";

            /// <summary>The complete raw JSON of the unrecognized payload.</summary>
            [JsonIgnore]
            public JsonElement RawJson { get; set; }
        }

        [JsonConverter(typeof(SeamUnionConverter))]
        [SeamUnion("warning_code")]
        [SeamUnionVariant("being_deleted", typeof(AcsUserWarningsBeingDeleted))]
        [SeamUnionVariant(
            "salto_ks_user_not_subscribed",
            typeof(AcsUserWarningsSaltoKsUserNotSubscribed)
        )]
        [SeamUnionVariant("acs_user_inactive", typeof(AcsUserWarningsAcsUserInactive))]
        [SeamUnionVariant(
            "unknown_issue_with_acs_user",
            typeof(AcsUserWarningsUnknownIssueWithAcsUser)
        )]
        [SeamUnionVariant("latch_resident_user", typeof(AcsUserWarningsLatchResidentUser))]
        [SeamUnionFallback(typeof(AcsUserWarningsUnrecognized))]
        public abstract record AcsUserWarnings
        {
            /// <summary>The value of the <c>warning_code</c> discriminator.</summary>
            public abstract string WarningCode { get; }

            /// <summary>
            /// Date and time at which Seam created the warning.
            /// </summary>
            [JsonPropertyName("created_at")]
            public string CreatedAt { get; init; } = default!;

            /// <summary>
            /// Detailed description of the warning. Provides insights into the issue and potentially how to rectify it.
            /// </summary>
            [JsonPropertyName("message")]
            public string Message { get; init; } = default!;
        }

        public sealed record AcsUserWarningsBeingDeleted : AcsUserWarnings
        {
            [JsonPropertyName("warning_code")]
            public override string WarningCode { get; } = "being_deleted";
        }

        public sealed record AcsUserWarningsSaltoKsUserNotSubscribed : AcsUserWarnings
        {
            [JsonPropertyName("warning_code")]
            public override string WarningCode { get; } = "salto_ks_user_not_subscribed";
        }

        public sealed record AcsUserWarningsAcsUserInactive : AcsUserWarnings
        {
            [JsonPropertyName("warning_code")]
            public override string WarningCode { get; } = "acs_user_inactive";
        }

        public sealed record AcsUserWarningsUnknownIssueWithAcsUser : AcsUserWarnings
        {
            [JsonPropertyName("warning_code")]
            public override string WarningCode { get; } = "unknown_issue_with_acs_user";
        }

        public sealed record AcsUserWarningsLatchResidentUser : AcsUserWarnings
        {
            [JsonPropertyName("warning_code")]
            public override string WarningCode { get; } = "latch_resident_user";
        }

        public sealed record AcsUserWarningsUnrecognized : AcsUserWarnings, ISeamUnrecognizedVariant
        {
            [JsonPropertyName("warning_code")]
            public override string WarningCode { get; } = "unrecognized";

            /// <summary>The complete raw JSON of the unrecognized payload.</summary>
            [JsonIgnore]
            public JsonElement RawJson { get; set; }
        }

        /// <summary>
        /// `starts_at` and `ends_at` timestamps for the [access system user&apos;s](https://docs.seam.co/low-level-apis/access-systems/user-management) access.
        /// </summary>
        [JsonPropertyName("access_schedule")]
        public AcsUserAccessSchedule? AccessSchedule { get; init; }

        /// <summary>
        /// ID of the [access system](https://docs.seam.co/low-level-apis/access-systems) that contains the [access system user](https://docs.seam.co/low-level-apis/access-systems/user-management).
        /// </summary>
        [JsonPropertyName("acs_system_id")]
        public string AcsSystemId { get; init; } = default!;

        /// <summary>
        /// ID of the [access system user](https://docs.seam.co/low-level-apis/access-systems/user-management).
        /// </summary>
        [JsonPropertyName("acs_user_id")]
        public string AcsUserId { get; init; } = default!;

        /// <summary>
        /// The ID of the connected account that is associated with the [access system user](https://docs.seam.co/low-level-apis/access-systems/user-management).
        /// </summary>
        [JsonPropertyName("connected_account_id")]
        public string ConnectedAccountId { get; init; } = default!;

        /// <summary>
        /// Date and time at which the [access system user](https://docs.seam.co/low-level-apis/access-systems/user-management) was created.
        /// </summary>
        [JsonPropertyName("created_at")]
        public string CreatedAt { get; init; } = default!;

        /// <summary>
        /// Display name for the [access system user](https://docs.seam.co/low-level-apis/access-systems/user-management).
        /// </summary>
        [JsonPropertyName("display_name")]
        public string DisplayName { get; init; } = default!;

        [Obsolete("use email_address.")]
        [JsonPropertyName("email")]
        public string? Email { get; init; }

        /// <summary>
        /// Email address of the [access system user](https://docs.seam.co/low-level-apis/access-systems/user-management).
        /// </summary>
        [JsonPropertyName("email_address")]
        public string? EmailAddress { get; init; }

        /// <summary>
        /// Errors associated with the [access system user](https://docs.seam.co/low-level-apis/access-systems/user-management).
        /// </summary>
        [JsonPropertyName("errors")]
        public List<AcsUserErrors> Errors { get; init; } = default!;

        /// <summary>
        /// Brand-specific terminology for the [access system user](https://docs.seam.co/low-level-apis/access-systems/user-management) type.
        /// </summary>
        [JsonPropertyName("external_type")]
        public AcsUser.ExternalTypeEnum? ExternalType { get; init; }

        /// <summary>
        /// Display name that corresponds to the brand-specific terminology for the [access system user](https://docs.seam.co/low-level-apis/access-systems/user-management) type.
        /// </summary>
        [JsonPropertyName("external_type_display_name")]
        public string? ExternalTypeDisplayName { get; init; }

        /// <summary>
        /// Full name of the [access system user](https://docs.seam.co/low-level-apis/access-systems/user-management).
        /// </summary>
        [JsonPropertyName("full_name")]
        public string? FullName { get; init; }

        /// <summary>
        /// ID of the HID access control system associated with the user.
        /// </summary>
        [JsonPropertyName("hid_acs_system_id")]
        public string? HidAcsSystemId { get; init; }

        /// <summary>
        /// Indicates whether Seam manages the access system user.
        /// </summary>
        [JsonPropertyName("is_managed")]
        public bool IsManaged { get; init; } = default!;

        /// <summary>
        /// Indicates whether the [access system user](https://docs.seam.co/low-level-apis/access-systems/user-management) is currently [suspended](https://docs.seam.co/low-level-apis/access-systems/user-management/suspending-and-unsuspending-users).
        /// </summary>
        [JsonPropertyName("is_suspended")]
        public bool? IsSuspended { get; init; }

        /// <summary>
        /// Pending mutations associated with the [access system user](https://docs.seam.co/low-level-apis/access-systems/user-management). Seam is in the process of pushing these mutations to the integrated access system.
        /// </summary>
        [JsonPropertyName("pending_mutations")]
        public List<AcsUserPendingMutations>? PendingMutations { get; init; }

        /// <summary>
        /// Phone number of the [access system user](https://docs.seam.co/low-level-apis/access-systems/user-management) in E.164 format (for example, `+15555550100`).
        /// </summary>
        [JsonPropertyName("phone_number")]
        public string? PhoneNumber { get; init; }

        /// <summary>
        /// Salto KS-specific metadata associated with the [access system user](https://docs.seam.co/low-level-apis/access-systems/user-management).
        /// </summary>
        [JsonPropertyName("salto_ks_metadata")]
        public AcsUserSaltoKsMetadata? SaltoKsMetadata { get; init; }

        /// <summary>
        /// Salto Space-specific metadata associated with the [access system user](https://docs.seam.co/low-level-apis/access-systems/user-management).
        /// </summary>
        [JsonPropertyName("salto_space_metadata")]
        public AcsUserSaltoSpaceMetadata? SaltoSpaceMetadata { get; init; }

        /// <summary>
        /// Email address of the user identity associated with the [access system user](https://docs.seam.co/low-level-apis/access-systems/user-management).
        /// </summary>
        [JsonPropertyName("user_identity_email_address")]
        public string? UserIdentityEmailAddress { get; init; }

        /// <summary>
        /// Full name of the user identity associated with the [access system user](https://docs.seam.co/low-level-apis/access-systems/user-management).
        /// </summary>
        [JsonPropertyName("user_identity_full_name")]
        public string? UserIdentityFullName { get; init; }

        /// <summary>
        /// ID of the user identity associated with the [access system user](https://docs.seam.co/low-level-apis/access-systems/user-management).
        /// </summary>
        [JsonPropertyName("user_identity_id")]
        public string? UserIdentityId { get; init; }

        /// <summary>
        /// Phone number of the user identity associated with the [access system user](https://docs.seam.co/low-level-apis/access-systems/user-management) in E.164 format (for example, `+15555550100`).
        /// </summary>
        [JsonPropertyName("user_identity_phone_number")]
        public string? UserIdentityPhoneNumber { get; init; }

        /// <summary>
        /// Warnings associated with the [access system user](https://docs.seam.co/low-level-apis/access-systems/user-management).
        /// </summary>
        [JsonPropertyName("warnings")]
        public List<AcsUserWarnings> Warnings { get; init; } = default!;

        /// <summary>
        /// ID of the workspace that contains the [access system user](https://docs.seam.co/low-level-apis/access-systems/user-management).
        /// </summary>
        [JsonPropertyName("workspace_id")]
        public string WorkspaceId { get; init; } = default!;
    }

    public sealed record AcsUserAccessSchedule
    {
        /// <summary>
        /// Date and time at which the user&apos;s access ends, in [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html) format.
        /// </summary>
        [JsonPropertyName("ends_at")]
        public string? EndsAt { get; init; }

        /// <summary>
        /// Date and time at which the user&apos;s access starts, in [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html) format.
        /// </summary>
        [JsonPropertyName("starts_at")]
        public string StartsAt { get; init; } = default!;
    }

    public sealed record AcsUserSaltoKsMetadata
    {
        /// <summary>
        /// Indicates whether the user holds an active subscription slot on the Salto KS site. Only subscribed users can unlock doors and count against the site&apos;s user-subscription limit. A user may not be subscribed because their access schedule has not started or has ended, the site has reached its subscription limit, or they were manually unsubscribed. This is distinct from `is_suspended`, which reflects whether the user has been explicitly blocked.
        /// </summary>
        [JsonPropertyName("is_subscribed")]
        public bool? IsSubscribed { get; init; }
    }

    public sealed record AcsUserSaltoSpaceMetadata
    {
        /// <summary>
        /// Indicates whether AuditOpenings is enabled for the user in the Salto Space access system.
        /// </summary>
        [JsonPropertyName("audit_openings")]
        public bool? AuditOpenings { get; init; }

        /// <summary>
        /// User ID in the Salto Space access system.
        /// </summary>
        [JsonPropertyName("user_id")]
        public string? UserId { get; init; }
    }
}
