// <auto-generated>
//   Generated by codegen/smith.ts from @seamapi/types. Do not edit.
// </auto-generated>
#nullable enable
#pragma warning disable CS0618 // The generated code references its own deprecated members.
using System.Runtime.Serialization;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Seam.Models
{
    /// <summary>
    /// Represents a [client session](https://docs.seam.co/core-concepts/authentication/client-session-tokens). If you want to restrict your users&apos; access to their own devices, use client sessions.
    ///
    /// You create each client session with a custom `user_identifier_key`. Normally, the `user_identifier_key` is a user ID that your application provides.
    ///
    /// When calling the Seam API from your backend using an API key, you can pass the `user_identifier_key` as a parameter to limit results to the associated client session. For example, `/devices/list?user_identifier_key=123` only returns devices associated with the client session created with the `user_identifier_key` `123`.
    ///
    /// A client session has a token that you can use with the Seam JavaScript SDK to make requests from the client (browser) directly to the Seam API. The token restricts the user&apos;s access to only the devices that they own.
    ///
    /// See also [Get Started with React](https://docs.seam.co/ui-components/overview/getting-started-with-seam-components/get-started-with-react-components-and-client-session-tokens).
    /// </summary>
    public sealed record ClientSession
    {
        /// <summary>
        /// ID of the client session.
        /// </summary>
        [JsonPropertyName("client_session_id")]
        public string ClientSessionId { get; init; } = default!;

        /// <summary>
        /// IDs of the [Connect Webviews](https://docs.seam.co/core-concepts/connect-webviews) associated with the [client session](https://docs.seam.co/core-concepts/authentication/client-session-tokens).
        /// </summary>
        [JsonPropertyName("connect_webview_ids")]
        public List<string> ConnectWebviewIds { get; init; } = default!;

        /// <summary>
        /// IDs of the [connected accounts](https://docs.seam.co/core-concepts/connected-accounts) associated with the [client session](https://docs.seam.co/core-concepts/authentication/client-session-tokens).
        /// </summary>
        [JsonPropertyName("connected_account_ids")]
        public List<string> ConnectedAccountIds { get; init; } = default!;

        /// <summary>
        /// Date and time at which the [client session](https://docs.seam.co/core-concepts/authentication/client-session-tokens) was created.
        /// </summary>
        [JsonPropertyName("created_at")]
        public string CreatedAt { get; init; } = default!;

        /// <summary>
        /// Customer key associated with the [client session](https://docs.seam.co/core-concepts/authentication/client-session-tokens).
        /// </summary>
        [JsonPropertyName("customer_key")]
        public string? CustomerKey { get; init; }

        /// <summary>
        /// Number of devices associated with the [client session](https://docs.seam.co/core-concepts/authentication/client-session-tokens).
        /// </summary>
        [JsonPropertyName("device_count")]
        public float DeviceCount { get; init; } = default!;

        /// <summary>
        /// Date and time at which the [client session](https://docs.seam.co/core-concepts/authentication/client-session-tokens) expires.
        /// </summary>
        [JsonPropertyName("expires_at")]
        public string ExpiresAt { get; init; } = default!;

        /// <summary>
        /// Client session token associated with the [client session](https://docs.seam.co/core-concepts/authentication/client-session-tokens).
        /// </summary>
        [JsonPropertyName("token")]
        public string Token { get; init; } = default!;

        /// <summary>
        /// Your user ID for the user associated with the [client session](https://docs.seam.co/core-concepts/authentication/client-session-tokens).
        /// </summary>
        [JsonPropertyName("user_identifier_key")]
        public string? UserIdentifierKey { get; init; }

        /// <summary>
        /// ID of the [user identity](https://docs.seam.co/capability-guides/mobile-access/managing-mobile-app-user-accounts-with-user-identities#what-is-a-user-identity) associated with the client session.
        /// </summary>
        [JsonPropertyName("user_identity_id")]
        public string? UserIdentityId { get; init; }

        /// <summary>
        /// IDs of the [user identities](https://docs.seam.co/capability-guides/mobile-access/managing-mobile-app-user-accounts-with-user-identities#what-is-a-user-identity) associated with the client session.
        /// </summary>
        [Obsolete("Use `user_identity_id` instead.")]
        [JsonPropertyName("user_identity_ids")]
        public List<string> UserIdentityIds { get; init; } = default!;

        /// <summary>
        /// ID of the workspace associated with the client session.
        /// </summary>
        [JsonPropertyName("workspace_id")]
        public string WorkspaceId { get; init; } = default!;
    }
}
