// <auto-generated>
//   Generated by codegen/smith.ts from @seamapi/types. Do not edit.
// </auto-generated>
#nullable enable
#pragma warning disable CS0618 // The generated code references its own deprecated members.
using System.Runtime.Serialization;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Seam.Models
{
    /// <summary>
    /// Represents a [connected account](https://docs.seam.co/core-concepts/connected-accounts). A connected account is an external third-party account to which your user has authorized Seam to get access, for example, an August account with a list of door locks.
    /// </summary>
    public sealed record ConnectedAccount
    {
        /// <summary>
        /// List of capabilities that were accepted during the account connection process.
        /// </summary>
        [JsonConverter(typeof(SeamStringEnumConverter))]
        public enum AcceptedCapabilitiesEnum
        {
            [EnumMember(Value = "unrecognized")]
            Unrecognized = 0,

            [EnumMember(Value = "lock")]
            Lock = 1,

            [EnumMember(Value = "thermostat")]
            Thermostat = 2,

            [EnumMember(Value = "noise_sensor")]
            NoiseSensor = 3,

            [EnumMember(Value = "access_control")]
            AccessControl = 4,

            [EnumMember(Value = "camera")]
            Camera = 5,
        }

        [JsonConverter(typeof(SeamUnionConverter))]
        [SeamUnion("error_code")]
        [SeamUnionVariant(
            "account_disconnected",
            typeof(ConnectedAccountErrorsAccountDisconnected)
        )]
        [SeamUnionVariant("bridge_disconnected", typeof(ConnectedAccountErrorsBridgeDisconnected))]
        [SeamUnionVariant(
            "salto_ks_subscription_limit_exceeded",
            typeof(ConnectedAccountErrorsSaltoKsSubscriptionLimitExceeded)
        )]
        [SeamUnionVariant(
            "dormakaba_sites_disconnected",
            typeof(ConnectedAccountErrorsDormakabaSitesDisconnected)
        )]
        [SeamUnionFallback(typeof(ConnectedAccountErrorsUnrecognized))]
        public abstract record ConnectedAccountErrors
        {
            /// <summary>The value of the <c>error_code</c> discriminator.</summary>
            public abstract string ErrorCode { get; }

            /// <summary>
            /// Date and time at which Seam created the error.
            /// </summary>
            [JsonPropertyName("created_at")]
            public string CreatedAt { get; init; } = default!;

            /// <summary>
            /// Indicates whether the error is related to [Seam Bridge](https://docs.seam.co/capability-guides/seam-bridge).
            /// </summary>
            [JsonPropertyName("is_bridge_error")]
            public bool? IsBridgeError { get; init; }

            /// <summary>
            /// Indicates whether the error is related specifically to the connected account.
            /// </summary>
            [JsonPropertyName("is_connected_account_error")]
            public bool? IsConnectedAccountError { get; init; }

            /// <summary>
            /// Detailed description of the error. Provides insights into the issue and potentially how to rectify it.
            /// </summary>
            [JsonPropertyName("message")]
            public string Message { get; init; } = default!;
        }

        public sealed record ConnectedAccountErrorsAccountDisconnected : ConnectedAccountErrors
        {
            [JsonPropertyName("error_code")]
            public override string ErrorCode { get; } = "account_disconnected";
        }

        public sealed record ConnectedAccountErrorsBridgeDisconnected : ConnectedAccountErrors
        {
            [JsonPropertyName("error_code")]
            public override string ErrorCode { get; } = "bridge_disconnected";
        }

        public sealed record ConnectedAccountErrorsSaltoKsSubscriptionLimitExceeded
            : ConnectedAccountErrors
        {
            [JsonPropertyName("error_code")]
            public override string ErrorCode { get; } = "salto_ks_subscription_limit_exceeded";

            /// <summary>
            /// Salto KS metadata associated with the connected account that has an error.
            /// </summary>
            [JsonPropertyName("salto_ks_metadata")]
            public ConnectedAccountErrorsSaltoKsSubscriptionLimitExceededSaltoKsMetadata SaltoKsMetadata { get; init; } =
                default!;
        }

        public sealed record ConnectedAccountErrorsSaltoKsSubscriptionLimitExceededSaltoKsMetadata
        {
            /// <summary>
            /// Salto sites associated with the connected account that has an error.
            /// </summary>
            [JsonPropertyName("sites")]
            public List<ConnectedAccountErrorsSaltoKsSubscriptionLimitExceededSaltoKsMetadataSites>? Sites { get; init; }
        }

        public sealed record ConnectedAccountErrorsSaltoKsSubscriptionLimitExceededSaltoKsMetadataSites
        {
            /// <summary>
            /// ID of a Salto site associated with the connected account that has an error.
            /// </summary>
            [JsonPropertyName("site_id")]
            public string? SiteId { get; init; }

            /// <summary>
            /// Name of a Salto site associated with the connected account that has an error.
            /// </summary>
            [JsonPropertyName("site_name")]
            public string? SiteName { get; init; }

            /// <summary>
            /// Subscription limit of site users for a Salto site associated with the connected account that has an error.
            /// </summary>
            [JsonPropertyName("site_user_subscription_limit")]
            public int? SiteUserSubscriptionLimit { get; init; }

            /// <summary>
            /// Count of subscribed site users for a Salto site associated with the connected account that has an error.
            /// </summary>
            [JsonPropertyName("subscribed_site_user_count")]
            public int? SubscribedSiteUserCount { get; init; }
        }

        public sealed record ConnectedAccountErrorsDormakabaSitesDisconnected
            : ConnectedAccountErrors
        {
            [JsonPropertyName("error_code")]
            public override string ErrorCode { get; } = "dormakaba_sites_disconnected";
        }

        public sealed record ConnectedAccountErrorsUnrecognized
            : ConnectedAccountErrors,
                ISeamUnrecognizedVariant
        {
            [JsonPropertyName("error_code")]
            public override string ErrorCode { get; } = "unrecognized";

            /// <summary>The complete raw JSON of the unrecognized payload.</summary>
            [JsonIgnore]
            public JsonElement RawJson { get; set; }
        }

        [JsonConverter(typeof(SeamUnionConverter))]
        [SeamUnion("warning_code")]
        [SeamUnionVariant(
            "scheduled_maintenance_window",
            typeof(ConnectedAccountWarningsScheduledMaintenanceWindow)
        )]
        [SeamUnionVariant(
            "unknown_issue_with_connected_account",
            typeof(ConnectedAccountWarningsUnknownIssueWithConnectedAccount)
        )]
        [SeamUnionVariant(
            "salto_ks_subscription_limit_almost_reached",
            typeof(ConnectedAccountWarningsSaltoKsSubscriptionLimitAlmostReached)
        )]
        [SeamUnionVariant(
            "account_reauthorization_requested",
            typeof(ConnectedAccountWarningsAccountReauthorizationRequested)
        )]
        [SeamUnionVariant("being_deleted", typeof(ConnectedAccountWarningsBeingDeleted))]
        [SeamUnionVariant(
            "provider_service_unavailable",
            typeof(ConnectedAccountWarningsProviderServiceUnavailable)
        )]
        [SeamUnionVariant("setup_required", typeof(ConnectedAccountWarningsSetupRequired))]
        [SeamUnionVariant(
            "dormakaba_sites_unapproved",
            typeof(ConnectedAccountWarningsDormakabaSitesUnapproved)
        )]
        [SeamUnionFallback(typeof(ConnectedAccountWarningsUnrecognized))]
        public abstract record ConnectedAccountWarnings
        {
            /// <summary>The value of the <c>warning_code</c> discriminator.</summary>
            public abstract string WarningCode { get; }

            /// <summary>
            /// Date and time at which Seam created the warning.
            /// </summary>
            [JsonPropertyName("created_at")]
            public string CreatedAt { get; init; } = default!;

            /// <summary>
            /// Detailed description of the warning. Provides insights into the issue and potentially how to rectify it.
            /// </summary>
            [JsonPropertyName("message")]
            public string Message { get; init; } = default!;
        }

        public sealed record ConnectedAccountWarningsScheduledMaintenanceWindow
            : ConnectedAccountWarnings
        {
            [JsonPropertyName("warning_code")]
            public override string WarningCode { get; } = "scheduled_maintenance_window";
        }

        public sealed record ConnectedAccountWarningsUnknownIssueWithConnectedAccount
            : ConnectedAccountWarnings
        {
            [JsonPropertyName("warning_code")]
            public override string WarningCode { get; } = "unknown_issue_with_connected_account";
        }

        public sealed record ConnectedAccountWarningsSaltoKsSubscriptionLimitAlmostReached
            : ConnectedAccountWarnings
        {
            [JsonPropertyName("warning_code")]
            public override string WarningCode { get; } =
                "salto_ks_subscription_limit_almost_reached";

            /// <summary>
            /// Salto KS metadata associated with the connected account that has a warning.
            /// </summary>
            [JsonPropertyName("salto_ks_metadata")]
            public ConnectedAccountWarningsSaltoKsSubscriptionLimitAlmostReachedSaltoKsMetadata SaltoKsMetadata { get; init; } =
                default!;
        }

        public sealed record ConnectedAccountWarningsSaltoKsSubscriptionLimitAlmostReachedSaltoKsMetadata
        {
            /// <summary>
            /// Salto sites associated with the connected account that has a warning.
            /// </summary>
            [JsonPropertyName("sites")]
            public List<ConnectedAccountWarningsSaltoKsSubscriptionLimitAlmostReachedSaltoKsMetadataSites>? Sites { get; init; }
        }

        public sealed record ConnectedAccountWarningsSaltoKsSubscriptionLimitAlmostReachedSaltoKsMetadataSites
        {
            /// <summary>
            /// ID of a Salto site associated with the connected account that has a warning.
            /// </summary>
            [JsonPropertyName("site_id")]
            public string? SiteId { get; init; }

            /// <summary>
            /// Name of a Salto site associated with the connected account that has a warning.
            /// </summary>
            [JsonPropertyName("site_name")]
            public string? SiteName { get; init; }

            /// <summary>
            /// Subscription limit of site users for a Salto site associated with the connected account that has a warning.
            /// </summary>
            [JsonPropertyName("site_user_subscription_limit")]
            public int? SiteUserSubscriptionLimit { get; init; }

            /// <summary>
            /// Count of subscribed site users for a Salto site associated with the connected account that has a warning.
            /// </summary>
            [JsonPropertyName("subscribed_site_user_count")]
            public int? SubscribedSiteUserCount { get; init; }
        }

        public sealed record ConnectedAccountWarningsAccountReauthorizationRequested
            : ConnectedAccountWarnings
        {
            [JsonPropertyName("warning_code")]
            public override string WarningCode { get; } = "account_reauthorization_requested";
        }

        public sealed record ConnectedAccountWarningsBeingDeleted : ConnectedAccountWarnings
        {
            [JsonPropertyName("warning_code")]
            public override string WarningCode { get; } = "being_deleted";
        }

        public sealed record ConnectedAccountWarningsProviderServiceUnavailable
            : ConnectedAccountWarnings
        {
            [JsonPropertyName("warning_code")]
            public override string WarningCode { get; } = "provider_service_unavailable";
        }

        public sealed record ConnectedAccountWarningsSetupRequired : ConnectedAccountWarnings
        {
            [JsonPropertyName("warning_code")]
            public override string WarningCode { get; } = "setup_required";
        }

        public sealed record ConnectedAccountWarningsDormakabaSitesUnapproved
            : ConnectedAccountWarnings
        {
            [JsonPropertyName("warning_code")]
            public override string WarningCode { get; } = "dormakaba_sites_unapproved";
        }

        public sealed record ConnectedAccountWarningsUnrecognized
            : ConnectedAccountWarnings,
                ISeamUnrecognizedVariant
        {
            [JsonPropertyName("warning_code")]
            public override string WarningCode { get; } = "unrecognized";

            /// <summary>The complete raw JSON of the unrecognized payload.</summary>
            [JsonIgnore]
            public JsonElement RawJson { get; set; }
        }

        /// <summary>
        /// List of capabilities that were accepted during the account connection process.
        /// </summary>
        [JsonPropertyName("accepted_capabilities")]
        public List<ConnectedAccount.AcceptedCapabilitiesEnum> AcceptedCapabilities { get; init; } =
            default!;

        /// <summary>
        /// Type of connected account.
        /// </summary>
        [JsonPropertyName("account_type")]
        public string? AccountType { get; init; }

        /// <summary>
        /// Display name for the connected account type.
        /// </summary>
        [JsonPropertyName("account_type_display_name")]
        public string AccountTypeDisplayName { get; init; } = default!;

        /// <summary>
        /// Indicates whether Seam should [import all new devices](https://docs.seam.co/core-concepts/connect-webviews/customizing-connect-webviews#automatically_manage_new_devices) for the connected account to make these devices available for management by the Seam API.
        /// </summary>
        [JsonPropertyName("automatically_manage_new_devices")]
        public bool AutomaticallyManageNewDevices { get; init; } = default!;

        /// <summary>
        /// ID of the connected account.
        /// </summary>
        [JsonPropertyName("connected_account_id")]
        public string ConnectedAccountId { get; init; } = default!;

        /// <summary>
        /// Date and time at which the connected account was created.
        /// </summary>
        [JsonPropertyName("created_at")]
        public string? CreatedAt { get; init; }

        /// <summary>
        /// Set of key:value pairs. Adding custom metadata to a resource, such as a [Connect Webview](https://docs.seam.co/core-concepts/connect-webviews/attaching-custom-data-to-the-connect-webview), [connected account](https://docs.seam.co/core-concepts/connected-accounts/adding-custom-metadata-to-a-connected-account), or [device](https://docs.seam.co/core-concepts/devices/adding-custom-metadata-to-a-device), enables you to store custom information, like customer details or internal IDs from your application. Keys set to `null` or to an empty string are omitted.
        /// </summary>
        [JsonPropertyName("custom_metadata")]
        public object CustomMetadata { get; init; } = default!;

        /// <summary>
        /// Your unique key for the customer associated with this connected account.
        /// </summary>
        [JsonPropertyName("customer_key")]
        public string? CustomerKey { get; init; }

        /// <summary>
        /// Default reservation check-in time for this connected account, as `HH:mm` (24-hour). Sourced from the connector configuration — set during the connect_webview for providers like Lodgify whose API does not expose check-in times.
        /// </summary>
        [JsonPropertyName("default_checkin_time")]
        public string? DefaultCheckinTime { get; init; }

        /// <summary>
        /// Default reservation check-out time for this connected account, as `HH:mm` (24-hour). Sourced from the connector configuration.
        /// </summary>
        [JsonPropertyName("default_checkout_time")]
        public string? DefaultCheckoutTime { get; init; }

        /// <summary>
        /// Display name for the connected account.
        /// </summary>
        [JsonPropertyName("display_name")]
        public string DisplayName { get; init; } = default!;

        /// <summary>
        /// Errors associated with the connected account.
        /// </summary>
        [JsonPropertyName("errors")]
        public List<ConnectedAccountErrors> Errors { get; init; } = default!;

        /// <summary>
        /// For iCal connected accounts, the platform that produced the feed (for example, `airbnb`, `vrbo`, or `booking`), or `unknown` when it could not be determined. Intended for rendering the source platform&apos;s logo.
        /// </summary>
        [JsonPropertyName("ical_feed_origin")]
        public string? IcalFeedOrigin { get; init; }

        /// <summary>
        /// For iCal connected accounts, the feed URL for the connection. Sourced from the connector configuration.
        /// </summary>
        [JsonPropertyName("ical_url")]
        public string? IcalUrl { get; init; }

        /// <summary>
        /// Logo URL for the connected account provider.
        /// </summary>
        [JsonPropertyName("image_url")]
        public string? ImageUrl { get; init; }

        /// <summary>
        /// IANA time zone (e.g. America/Los_Angeles) for this connected account. Sourced from the connector configuration.
        /// </summary>
        [JsonPropertyName("time_zone")]
        public string? TimeZone { get; init; }

        /// <summary>
        /// User identifier associated with the connected account.
        /// </summary>
        [Obsolete("Use `display_name` instead.")]
        [JsonPropertyName("user_identifier")]
        public ConnectedAccountUserIdentifier? UserIdentifier { get; init; }

        /// <summary>
        /// Warnings associated with the connected account.
        /// </summary>
        [JsonPropertyName("warnings")]
        public List<ConnectedAccountWarnings> Warnings { get; init; } = default!;
    }

    public sealed record ConnectedAccountUserIdentifier
    {
        /// <summary>
        /// API URL for the user identifier associated with the connected account.
        /// </summary>
        [JsonPropertyName("api_url")]
        public string? ApiUrl { get; init; }

        /// <summary>
        /// Email address of the user identifier associated with the connected account.
        /// </summary>
        [JsonPropertyName("email")]
        public string? Email { get; init; }

        /// <summary>
        /// Indicates whether the user identifier associated with the connected account is exclusive.
        /// </summary>
        [JsonPropertyName("exclusive")]
        public bool? Exclusive { get; init; }

        /// <summary>
        /// Phone number of the user identifier associated with the connected account.
        /// </summary>
        [JsonPropertyName("phone")]
        public string? Phone { get; init; }

        /// <summary>
        /// Username of the user identifier associated with the connected account.
        /// </summary>
        [JsonPropertyName("username")]
        public string? Username { get; init; }
    }
}
