// <auto-generated>
//   Generated by codegen/smith.ts from @seamapi/types. Do not edit.
// </auto-generated>
#nullable enable
#pragma warning disable CS0618 // The generated code references its own deprecated members.
using System.Runtime.Serialization;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Seam.Models
{
    public sealed record DeviceProvider
    {
        /// <summary>
        /// Name of the device provider.
        /// </summary>
        [JsonConverter(typeof(SeamStringEnumConverter))]
        public enum DeviceProviderNameEnum
        {
            [EnumMember(Value = "unrecognized")]
            Unrecognized = 0,

            [EnumMember(Value = "hotek")]
            Hotek = 1,

            [EnumMember(Value = "dormakaba_community")]
            DormakabaCommunity = 2,

            [EnumMember(Value = "legic_connect")]
            LegicConnect = 3,

            [EnumMember(Value = "akuvox")]
            Akuvox = 4,

            [EnumMember(Value = "august")]
            August = 5,

            [EnumMember(Value = "avigilon_alta")]
            AvigilonAlta = 6,

            [EnumMember(Value = "brivo")]
            Brivo = 7,

            [EnumMember(Value = "butterflymx")]
            Butterflymx = 8,

            [EnumMember(Value = "schlage")]
            Schlage = 9,

            [EnumMember(Value = "smartthings")]
            Smartthings = 10,

            [EnumMember(Value = "yale")]
            Yale = 11,

            [EnumMember(Value = "genie")]
            Genie = 12,

            [EnumMember(Value = "doorking")]
            Doorking = 13,

            [EnumMember(Value = "salto")]
            Salto = 14,

            [EnumMember(Value = "salto_ks")]
            SaltoKs = 15,

            [EnumMember(Value = "salto_ks_accept")]
            SaltoKsAccept = 16,

            [EnumMember(Value = "lockly")]
            Lockly = 17,

            [EnumMember(Value = "ttlock")]
            Ttlock = 18,

            [EnumMember(Value = "linear")]
            Linear = 19,

            [EnumMember(Value = "noiseaware")]
            Noiseaware = 20,

            [EnumMember(Value = "nuki")]
            Nuki = 21,

            [EnumMember(Value = "igloo")]
            Igloo = 22,

            [EnumMember(Value = "kwikset")]
            Kwikset = 23,

            [EnumMember(Value = "minut")]
            Minut = 24,

            [EnumMember(Value = "my_2n")]
            My_2n = 25,

            [EnumMember(Value = "controlbyweb")]
            Controlbyweb = 26,

            [EnumMember(Value = "nest")]
            Nest = 27,

            [EnumMember(Value = "igloohome")]
            Igloohome = 28,

            [EnumMember(Value = "ecobee")]
            Ecobee = 29,

            [EnumMember(Value = "four_suites")]
            FourSuites = 30,

            [EnumMember(Value = "dormakaba_oracode")]
            DormakabaOracode = 31,

            [EnumMember(Value = "pti")]
            Pti = 32,

            [EnumMember(Value = "wyze")]
            Wyze = 33,

            [EnumMember(Value = "seam_passport")]
            SeamPassport = 34,

            [EnumMember(Value = "visionline")]
            Visionline = 35,

            [EnumMember(Value = "assa_abloy_credential_service")]
            AssaAbloyCredentialService = 36,

            [EnumMember(Value = "tedee")]
            Tedee = 37,

            [EnumMember(Value = "honeywell_resideo")]
            HoneywellResideo = 38,

            [EnumMember(Value = "first_alert")]
            FirstAlert = 39,

            [EnumMember(Value = "latch")]
            Latch = 40,

            [EnumMember(Value = "akiles")]
            Akiles = 41,

            [EnumMember(Value = "assa_abloy_vostio")]
            AssaAbloyVostio = 42,

            [EnumMember(Value = "assa_abloy_vostio_credential_service")]
            AssaAbloyVostioCredentialService = 43,

            [EnumMember(Value = "tado")]
            Tado = 44,

            [EnumMember(Value = "salto_space")]
            SaltoSpace = 45,

            [EnumMember(Value = "sensi")]
            Sensi = 46,

            [EnumMember(Value = "keynest")]
            Keynest = 47,

            [EnumMember(Value = "korelock")]
            Korelock = 48,

            [EnumMember(Value = "keyincode")]
            Keyincode = 49,

            [EnumMember(Value = "dormakaba_ambiance")]
            DormakabaAmbiance = 50,

            [EnumMember(Value = "ultraloq")]
            Ultraloq = 51,

            [EnumMember(Value = "yacan")]
            Yacan = 52,

            [EnumMember(Value = "dusaw")]
            Dusaw = 53,

            [EnumMember(Value = "sifely")]
            Sifely = 54,

            [EnumMember(Value = "thirty_three_lock")]
            ThirtyThreeLock = 55,

            [EnumMember(Value = "ring")]
            Ring = 56,

            [EnumMember(Value = "ical")]
            Ical = 57,

            [EnumMember(Value = "lodgify")]
            Lodgify = 58,

            [EnumMember(Value = "hostaway")]
            Hostaway = 59,

            [EnumMember(Value = "guesty")]
            Guesty = 60,

            [EnumMember(Value = "acuity_scheduling")]
            AcuityScheduling = 61,

            [EnumMember(Value = "omnitec")]
            Omnitec = 62,

            [EnumMember(Value = "kisi")]
            Kisi = 63,

            [EnumMember(Value = "aqara")]
            Aqara = 64,
        }

        /// <summary>
        /// List of provider categories to which the device provider belongs, such as `stable`, `consumer_smartlocks`, `thermostats`, and so on.
        /// </summary>
        [JsonConverter(typeof(SeamStringEnumConverter))]
        public enum ProviderCategoriesEnum
        {
            [EnumMember(Value = "unrecognized")]
            Unrecognized = 0,

            [EnumMember(Value = "stable")]
            Stable = 1,

            [EnumMember(Value = "consumer_smartlocks")]
            ConsumerSmartlocks = 2,

            [EnumMember(Value = "beta")]
            Beta = 3,

            [EnumMember(Value = "thermostats")]
            Thermostats = 4,

            [EnumMember(Value = "noise_sensors")]
            NoiseSensors = 5,

            [EnumMember(Value = "access_control_systems")]
            AccessControlSystems = 6,

            [EnumMember(Value = "cameras")]
            Cameras = 7,

            [EnumMember(Value = "connectors")]
            Connectors = 8,
        }

        /// <summary>
        /// Indicates whether the lock supports configuring automatic locking.
        /// </summary>
        [JsonPropertyName("can_configure_auto_lock")]
        public bool? CanConfigureAutoLock { get; init; }

        /// <summary>
        /// Indicates whether the thermostat supports cooling.
        /// </summary>
        [JsonPropertyName("can_hvac_cool")]
        public bool? CanHvacCool { get; init; }

        /// <summary>
        /// Indicates whether the thermostat supports heating.
        /// </summary>
        [JsonPropertyName("can_hvac_heat")]
        public bool? CanHvacHeat { get; init; }

        /// <summary>
        /// Indicates whether the thermostat supports simultaneous heating and cooling.
        /// </summary>
        [JsonPropertyName("can_hvac_heat_cool")]
        public bool? CanHvacHeatCool { get; init; }

        /// <summary>
        /// Indicates whether the device supports programming offline access codes.
        /// </summary>
        [JsonPropertyName("can_program_offline_access_codes")]
        public bool? CanProgramOfflineAccessCodes { get; init; }

        /// <summary>
        /// Indicates whether the device supports programming online access codes.
        /// </summary>
        [JsonPropertyName("can_program_online_access_codes")]
        public bool? CanProgramOnlineAccessCodes { get; init; }

        /// <summary>
        /// Indicates whether the thermostat supports different climate programs for each day of the week.
        /// </summary>
        [JsonPropertyName("can_program_thermostat_programs_as_different_each_day")]
        public bool? CanProgramThermostatProgramsAsDifferentEachDay { get; init; }

        /// <summary>
        /// Indicates whether the thermostat supports a single climate program applied to every day.
        /// </summary>
        [JsonPropertyName("can_program_thermostat_programs_as_same_each_day")]
        public bool? CanProgramThermostatProgramsAsSameEachDay { get; init; }

        /// <summary>
        /// Indicates whether the thermostat supports weekday/weekend climate programs.
        /// </summary>
        [JsonPropertyName("can_program_thermostat_programs_as_weekday_weekend")]
        public bool? CanProgramThermostatProgramsAsWeekdayWeekend { get; init; }

        /// <summary>
        /// Indicates whether the device supports remote locking.
        /// </summary>
        [JsonPropertyName("can_remotely_lock")]
        public bool? CanRemotelyLock { get; init; }

        /// <summary>
        /// Indicates whether the device supports remote unlocking.
        /// </summary>
        [JsonPropertyName("can_remotely_unlock")]
        public bool? CanRemotelyUnlock { get; init; }

        /// <summary>
        /// Indicates whether the thermostat supports running climate programs.
        /// </summary>
        [JsonPropertyName("can_run_thermostat_programs")]
        public bool? CanRunThermostatPrograms { get; init; }

        /// <summary>
        /// Indicates whether the device supports simulating connection in a sandbox.
        /// </summary>
        [JsonPropertyName("can_simulate_connection")]
        public bool? CanSimulateConnection { get; init; }

        /// <summary>
        /// Indicates whether the device supports simulating disconnection in a sandbox.
        /// </summary>
        [JsonPropertyName("can_simulate_disconnection")]
        public bool? CanSimulateDisconnection { get; init; }

        /// <summary>
        /// Indicates whether the hub supports simulating connection in a sandbox.
        /// </summary>
        [JsonPropertyName("can_simulate_hub_connection")]
        public bool? CanSimulateHubConnection { get; init; }

        /// <summary>
        /// Indicates whether the hub supports simulating disconnection in a sandbox.
        /// </summary>
        [JsonPropertyName("can_simulate_hub_disconnection")]
        public bool? CanSimulateHubDisconnection { get; init; }

        /// <summary>
        /// Indicates whether the device supports simulating a paid subscription in a sandbox.
        /// </summary>
        [JsonPropertyName("can_simulate_paid_subscription")]
        public bool? CanSimulatePaidSubscription { get; init; }

        /// <summary>
        /// Indicates whether the device supports simulating removal in a sandbox.
        /// </summary>
        [JsonPropertyName("can_simulate_removal")]
        public bool? CanSimulateRemoval { get; init; }

        /// <summary>
        /// Indicates whether the thermostat can be turned off.
        /// </summary>
        [JsonPropertyName("can_turn_off_hvac")]
        public bool? CanTurnOffHvac { get; init; }

        /// <summary>
        /// Indicates whether the lock supports unlocking with an access code.
        /// </summary>
        [JsonPropertyName("can_unlock_with_code")]
        public bool? CanUnlockWithCode { get; init; }

        /// <summary>
        /// Name of the device provider.
        /// </summary>
        [JsonPropertyName("device_provider_name")]
        public DeviceProvider.DeviceProviderNameEnum DeviceProviderName { get; init; } = default!;

        /// <summary>
        /// Display name for the device provider.
        /// </summary>
        [JsonPropertyName("display_name")]
        public string DisplayName { get; init; } = default!;

        /// <summary>
        /// Image URL for the device provider.
        /// </summary>
        [JsonPropertyName("image_url")]
        public string ImageUrl { get; init; } = default!;

        /// <summary>
        /// List of provider categories to which the device provider belongs, such as `stable`, `consumer_smartlocks`, `thermostats`, and so on.
        /// </summary>
        [JsonPropertyName("provider_categories")]
        public List<DeviceProvider.ProviderCategoriesEnum> ProviderCategories { get; init; } =
            default!;
    }
}
