// <auto-generated>
//   Generated by codegen/smith.ts from @seamapi/types. Do not edit.
// </auto-generated>
#nullable enable
#pragma warning disable CS0618 // The generated code references its own deprecated members.
using System.Runtime.Serialization;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Seam.Models
{
    /// <summary>
    /// Represents a Seam Instant Key. For issuing Bluetooth mobile keys, Instant Keys are the fastest way to share access. With a single API call, you can create a mobile key and send it through text or email or embed it in your own app.
    ///
    /// There’s no app to install, nor account to create. Your user just taps a link and gets a lightweight, native-feeling experience using iOS App Clip or Instant Apps on Android. Further, Instant Keys work offline, so even in areas with poor cellular or Wi-Fi, like elevator banks or concrete-walled hallways, the Instant Keys still work.
    /// </summary>
    public sealed record InstantKey
    {
        /// <summary>
        /// ID of the client session associated with the Instant Key.
        /// </summary>
        [JsonPropertyName("client_session_id")]
        public string ClientSessionId { get; init; } = default!;

        /// <summary>
        /// Date and time at which the Instant Key was created.
        /// </summary>
        [JsonPropertyName("created_at")]
        public string CreatedAt { get; init; } = default!;

        /// <summary>
        /// Customization applied to the Instant Key UI.
        /// </summary>
        [JsonPropertyName("customization")]
        public InstantKeyCustomization? Customization { get; init; }

        /// <summary>
        /// ID of the customization profile associated with the Instant Key.
        /// </summary>
        [JsonPropertyName("customization_profile_id")]
        public string? CustomizationProfileId { get; init; }

        /// <summary>
        /// Date and time at which the Instant Key expires.
        /// </summary>
        [JsonPropertyName("expires_at")]
        public string ExpiresAt { get; init; } = default!;

        /// <summary>
        /// ID of the Instant Key.
        /// </summary>
        [JsonPropertyName("instant_key_id")]
        public string InstantKeyId { get; init; } = default!;

        /// <summary>
        /// Shareable URL for the Instant Key. Use the URL to deliver the Instant Key to your user through a link in a text message or email or by embedding it in your web app.
        /// </summary>
        [JsonPropertyName("instant_key_url")]
        public string InstantKeyUrl { get; init; } = default!;

        /// <summary>
        /// ID of the user identity associated with the Instant Key.
        /// </summary>
        [JsonPropertyName("user_identity_id")]
        public string UserIdentityId { get; init; } = default!;

        /// <summary>
        /// ID of the workspace that contains the Instant Key.
        /// </summary>
        [JsonPropertyName("workspace_id")]
        public string WorkspaceId { get; init; } = default!;
    }

    public sealed record InstantKeyCustomization
    {
        /// <summary>
        /// URL of the logo displayed on the Instant Key.
        /// </summary>
        [JsonPropertyName("logo_url")]
        public string? LogoUrl { get; init; }

        /// <summary>
        /// Primary color used in the Instant Key UI.
        /// </summary>
        [JsonPropertyName("primary_color")]
        public string? PrimaryColor { get; init; }

        /// <summary>
        /// Secondary color used in the Instant Key UI.
        /// </summary>
        [JsonPropertyName("secondary_color")]
        public string? SecondaryColor { get; init; }
    }
}
