// <auto-generated>
//   Generated by codegen/smith.ts from @seamapi/types. Do not edit.
// </auto-generated>
#nullable enable
#pragma warning disable CS0618 // The generated code references its own deprecated members.
using System.Runtime.Serialization;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Seam.Models
{
    /// <summary>
    /// Represents a [noise threshold](https://docs.seam.co/capability-guides/noise-sensors/configure-noise-threshold-settings) for a [noise sensor](https://docs.seam.co/capability-guides/noise-sensors). Thresholds represent the limits of noise tolerated at a property, which can be customized for each hour of the day. Each device has its own default thresholds, but you can use the Seam API to modify them.
    /// </summary>
    public sealed record NoiseThreshold
    {
        /// <summary>
        /// Unique identifier for the device that contains the noise threshold.
        /// </summary>
        [JsonPropertyName("device_id")]
        public string DeviceId { get; init; } = default!;

        /// <summary>
        /// Time at which the noise threshold should become inactive daily.
        /// </summary>
        [JsonPropertyName("ends_daily_at")]
        public string EndsDailyAt { get; init; } = default!;

        /// <summary>
        /// Name of the noise threshold.
        /// </summary>
        [JsonPropertyName("name")]
        public string Name { get; init; } = default!;

        /// <summary>
        /// Noise level in decibels for the noise threshold.
        /// </summary>
        [JsonPropertyName("noise_threshold_decibels")]
        public float NoiseThresholdDecibels { get; init; } = default!;

        /// <summary>
        /// Unique identifier for the noise threshold.
        /// </summary>
        [JsonPropertyName("noise_threshold_id")]
        public string NoiseThresholdId { get; init; } = default!;

        /// <summary>
        /// Noise level in Noiseaware Noise Risk Score (NRS) for the noise threshold. This parameter is only relevant for [Noiseaware sensors](https://docs.seam.co/device-and-system-integration-guides/noiseaware-sensors).
        /// </summary>
        [JsonPropertyName("noise_threshold_nrs")]
        public float? NoiseThresholdNrs { get; init; }

        /// <summary>
        /// Time at which the noise threshold should become active daily.
        /// </summary>
        [JsonPropertyName("starts_daily_at")]
        public string StartsDailyAt { get; init; } = default!;
    }
}
