// <auto-generated>
//   Generated by codegen/smith.ts from @seamapi/types. Do not edit.
// </auto-generated>
#nullable enable
#pragma warning disable CS0618 // The generated code references its own deprecated members.
using System.Runtime.Serialization;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Seam.Models
{
    /// <summary>
    /// Represents an unmanaged user identity. Unmanaged user identities do not have keys.
    /// </summary>
    public sealed record UnmanagedUserIdentity
    {
        [JsonConverter(typeof(SeamUnionConverter))]
        [SeamUnion("error_code")]
        [SeamUnionVariant(
            "issue_with_acs_user",
            typeof(UnmanagedUserIdentityErrorsIssueWithAcsUser)
        )]
        [SeamUnionFallback(typeof(UnmanagedUserIdentityErrorsUnrecognized))]
        public abstract record UnmanagedUserIdentityErrors
        {
            /// <summary>The value of the <c>error_code</c> discriminator.</summary>
            public abstract string ErrorCode { get; }

            /// <summary>
            /// ID of the access system that the user identity is associated with.
            /// </summary>
            [JsonPropertyName("acs_system_id")]
            public string AcsSystemId { get; init; } = default!;

            /// <summary>
            /// ID of the access system user that has an issue.
            /// </summary>
            [JsonPropertyName("acs_user_id")]
            public string AcsUserId { get; init; } = default!;

            /// <summary>
            /// Date and time at which Seam created the error.
            /// </summary>
            [JsonPropertyName("created_at")]
            public string CreatedAt { get; init; } = default!;

            /// <summary>
            /// Detailed description of the error. Provides insights into the issue and potentially how to rectify it.
            /// </summary>
            [JsonPropertyName("message")]
            public string Message { get; init; } = default!;
        }

        public sealed record UnmanagedUserIdentityErrorsIssueWithAcsUser
            : UnmanagedUserIdentityErrors
        {
            [JsonPropertyName("error_code")]
            public override string ErrorCode { get; } = "issue_with_acs_user";
        }

        public sealed record UnmanagedUserIdentityErrorsUnrecognized
            : UnmanagedUserIdentityErrors,
                ISeamUnrecognizedVariant
        {
            [JsonPropertyName("error_code")]
            public override string ErrorCode { get; } = "unrecognized";

            /// <summary>The complete raw JSON of the unrecognized payload.</summary>
            [JsonIgnore]
            public JsonElement RawJson { get; set; }
        }

        [JsonConverter(typeof(SeamUnionConverter))]
        [SeamUnion("warning_code")]
        [SeamUnionVariant("being_deleted", typeof(UnmanagedUserIdentityWarningsBeingDeleted))]
        [SeamUnionVariant(
            "acs_user_profile_does_not_match_user_identity",
            typeof(UnmanagedUserIdentityWarningsAcsUserProfileDoesNotMatchUserIdentity)
        )]
        [SeamUnionFallback(typeof(UnmanagedUserIdentityWarningsUnrecognized))]
        public abstract record UnmanagedUserIdentityWarnings
        {
            /// <summary>The value of the <c>warning_code</c> discriminator.</summary>
            public abstract string WarningCode { get; }

            /// <summary>
            /// Date and time at which Seam created the warning.
            /// </summary>
            [JsonPropertyName("created_at")]
            public string CreatedAt { get; init; } = default!;

            /// <summary>
            /// Detailed description of the warning. Provides insights into the issue and potentially how to rectify it.
            /// </summary>
            [JsonPropertyName("message")]
            public string Message { get; init; } = default!;
        }

        public sealed record UnmanagedUserIdentityWarningsBeingDeleted
            : UnmanagedUserIdentityWarnings
        {
            [JsonPropertyName("warning_code")]
            public override string WarningCode { get; } = "being_deleted";
        }

        public sealed record UnmanagedUserIdentityWarningsAcsUserProfileDoesNotMatchUserIdentity
            : UnmanagedUserIdentityWarnings
        {
            [JsonPropertyName("warning_code")]
            public override string WarningCode { get; } =
                "acs_user_profile_does_not_match_user_identity";
        }

        public sealed record UnmanagedUserIdentityWarningsUnrecognized
            : UnmanagedUserIdentityWarnings,
                ISeamUnrecognizedVariant
        {
            [JsonPropertyName("warning_code")]
            public override string WarningCode { get; } = "unrecognized";

            /// <summary>The complete raw JSON of the unrecognized payload.</summary>
            [JsonIgnore]
            public JsonElement RawJson { get; set; }
        }

        /// <summary>
        /// Array of access system user IDs associated with the user identity.
        /// </summary>
        [JsonPropertyName("acs_user_ids")]
        public List<string> AcsUserIds { get; init; } = default!;

        /// <summary>
        /// Date and time at which the user identity was created.
        /// </summary>
        [JsonPropertyName("created_at")]
        public string CreatedAt { get; init; } = default!;

        /// <summary>
        /// Display name for the user identity.
        /// </summary>
        [JsonPropertyName("display_name")]
        public string DisplayName { get; init; } = default!;

        /// <summary>
        /// Unique email address for the user identity.
        /// </summary>
        [JsonPropertyName("email_address")]
        public string? EmailAddress { get; init; }

        /// <summary>
        /// Array of errors associated with the user identity. Each error object within the array contains fields like &quot;error_code&quot; and &quot;message.&quot; &quot;error_code&quot; is a string that uniquely identifies the type of error, enabling quick recognition and categorization of the issue. &quot;message&quot; provides a more detailed description of the error, offering insights into the issue and potentially how to rectify it.
        /// </summary>
        [JsonPropertyName("errors")]
        public List<UnmanagedUserIdentityErrors> Errors { get; init; } = default!;

        /// <summary>
        /// Full name of the user associated with the user identity.
        /// </summary>
        [JsonPropertyName("full_name")]
        public string? FullName { get; init; }

        /// <summary>
        /// IDs that other user identities used to have before they were merged into this user identity. Looking up any of them returns this user identity.
        /// </summary>
        [JsonPropertyName("merged_user_identity_ids")]
        public List<string> MergedUserIdentityIds { get; init; } = default!;

        /// <summary>
        /// Keys that other user identities used to have before they were merged into this user identity. Looking up any of them returns this user identity.
        /// </summary>
        [JsonPropertyName("merged_user_identity_keys")]
        public List<string> MergedUserIdentityKeys { get; init; } = default!;

        /// <summary>
        /// Unique phone number for the user identity in [E.164 format](https://www.itu.int/rec/T-REC-E.164/en) (for example, +15555550100).
        /// </summary>
        [JsonPropertyName("phone_number")]
        public string? PhoneNumber { get; init; }

        /// <summary>
        /// ID of the user identity.
        /// </summary>
        [JsonPropertyName("user_identity_id")]
        public string UserIdentityId { get; init; } = default!;

        /// <summary>
        /// Array of warnings associated with the user identity. Each warning object within the array contains two fields: &quot;warning_code&quot; and &quot;message.&quot; &quot;warning_code&quot; is a string that uniquely identifies the type of warning, enabling quick recognition and categorization of the issue. &quot;message&quot; provides a more detailed description of the warning, offering insights into the issue and potentially how to rectify it.
        /// </summary>
        [JsonPropertyName("warnings")]
        public List<UnmanagedUserIdentityWarnings> Warnings { get; init; } = default!;

        /// <summary>
        /// ID of the workspace that contains the user identity.
        /// </summary>
        [JsonPropertyName("workspace_id")]
        public string WorkspaceId { get; init; } = default!;
    }
}
