// <auto-generated>
//   Generated by codegen/smith.ts from @seamapi/types. Do not edit.
// </auto-generated>
#nullable enable
#pragma warning disable CS0618 // The generated code references its own deprecated members.
using System.Runtime.Serialization;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Seam.Models
{
    /// <summary>
    /// Represents an [unmanaged smart lock access code](https://docs.seam.co/low-level-apis/smart-locks/access-codes/migrating-existing-access-codes).
    ///
    /// An access code is a code used for a keypad or pinpad device. Unlike physical keys, which can easily be lost or duplicated, PIN codes can be customized, tracked, and altered on the fly.
    ///
    /// When you create an access code on a device in Seam, it is created as a managed access code. Access codes that exist on a device that were not created through Seam are considered unmanaged codes. We strictly limit the operations that can be performed on unmanaged codes.
    ///
    /// Prior to using Seam to manage your devices, you may have used another lock management system to manage the access codes on your devices. Where possible, we help you keep any existing access codes on devices and transition those codes to ones managed by your Seam workspace.
    ///
    /// Not all providers support unmanaged access codes. The following providers do not support unmanaged access codes:
    ///
    /// - [Kwikset](https://docs.seam.co/device-and-system-integration-guides/kwikset-locks)
    /// </summary>
    public sealed record UnmanagedAccessCode
    {
        [JsonConverter(typeof(SeamUnionConverter))]
        [SeamUnion("error_code")]
        [SeamUnionVariant("provider_issue", typeof(UnmanagedAccessCodeErrorsProviderIssue))]
        [SeamUnionVariant(
            "failed_to_set_on_device",
            typeof(UnmanagedAccessCodeErrorsFailedToSetOnDevice)
        )]
        [SeamUnionVariant(
            "failed_to_remove_from_device",
            typeof(UnmanagedAccessCodeErrorsFailedToRemoveFromDevice)
        )]
        [SeamUnionVariant(
            "duplicate_code_on_device",
            typeof(UnmanagedAccessCodeErrorsDuplicateCodeOnDevice)
        )]
        [SeamUnionVariant(
            "no_space_for_access_code_on_device",
            typeof(UnmanagedAccessCodeErrorsNoSpaceForAccessCodeOnDevice)
        )]
        [SeamUnionVariant(
            "conflicting_external_modification",
            typeof(UnmanagedAccessCodeErrorsConflictingExternalModification)
        )]
        [SeamUnionVariant(
            "access_code_inactive",
            typeof(UnmanagedAccessCodeErrorsAccessCodeInactive)
        )]
        [SeamUnionVariant(
            "code_constraints_violated",
            typeof(UnmanagedAccessCodeErrorsCodeConstraintsViolated)
        )]
        [SeamUnionVariant(
            "account_disconnected",
            typeof(UnmanagedAccessCodeErrorsAccountDisconnected)
        )]
        [SeamUnionVariant(
            "salto_ks_subscription_limit_exceeded",
            typeof(UnmanagedAccessCodeErrorsSaltoKsSubscriptionLimitExceeded)
        )]
        [SeamUnionVariant(
            "insufficient_permissions",
            typeof(UnmanagedAccessCodeErrorsInsufficientPermissions)
        )]
        [SeamUnionVariant(
            "dormakaba_sites_disconnected",
            typeof(UnmanagedAccessCodeErrorsDormakabaSitesDisconnected)
        )]
        [SeamUnionVariant("device_offline", typeof(UnmanagedAccessCodeErrorsDeviceOffline))]
        [SeamUnionVariant("device_removed", typeof(UnmanagedAccessCodeErrorsDeviceRemoved))]
        [SeamUnionVariant("hub_disconnected", typeof(UnmanagedAccessCodeErrorsHubDisconnected))]
        [SeamUnionVariant(
            "device_disconnected",
            typeof(UnmanagedAccessCodeErrorsDeviceDisconnected)
        )]
        [SeamUnionVariant(
            "empty_backup_access_code_pool",
            typeof(UnmanagedAccessCodeErrorsEmptyBackupAccessCodePool)
        )]
        [SeamUnionVariant(
            "august_lock_not_authorized",
            typeof(UnmanagedAccessCodeErrorsAugustLockNotAuthorized)
        )]
        [SeamUnionVariant(
            "missing_device_credentials",
            typeof(UnmanagedAccessCodeErrorsMissingDeviceCredentials)
        )]
        [SeamUnionVariant(
            "auxiliary_heat_running",
            typeof(UnmanagedAccessCodeErrorsAuxiliaryHeatRunning)
        )]
        [SeamUnionVariant(
            "subscription_required",
            typeof(UnmanagedAccessCodeErrorsSubscriptionRequired)
        )]
        [SeamUnionVariant(
            "bridge_disconnected",
            typeof(UnmanagedAccessCodeErrorsBridgeDisconnected)
        )]
        [SeamUnionFallback(typeof(UnmanagedAccessCodeErrorsUnrecognized))]
        public abstract record UnmanagedAccessCodeErrors
        {
            /// <summary>The value of the <c>error_code</c> discriminator.</summary>
            public abstract string ErrorCode { get; }

            /// <summary>
            /// Detailed description of the error. Provides insights into the issue and potentially how to rectify it.
            /// </summary>
            [JsonPropertyName("message")]
            public string Message { get; init; } = default!;
        }

        public sealed record UnmanagedAccessCodeErrorsProviderIssue : UnmanagedAccessCodeErrors
        {
            [JsonPropertyName("error_code")]
            public override string ErrorCode { get; } = "provider_issue";

            /// <summary>
            /// Date and time at which Seam created the error.
            /// </summary>
            [JsonPropertyName("created_at")]
            public string? CreatedAt { get; init; }

            /// <summary>
            /// Indicates that this is an access code error.
            /// </summary>
            [JsonPropertyName("is_access_code_error")]
            public bool IsAccessCodeError { get; init; } = default!;
        }

        public sealed record UnmanagedAccessCodeErrorsFailedToSetOnDevice
            : UnmanagedAccessCodeErrors
        {
            [JsonPropertyName("error_code")]
            public override string ErrorCode { get; } = "failed_to_set_on_device";

            /// <summary>
            /// Date and time at which Seam created the error.
            /// </summary>
            [JsonPropertyName("created_at")]
            public string? CreatedAt { get; init; }

            /// <summary>
            /// Indicates that this is an access code error.
            /// </summary>
            [JsonPropertyName("is_access_code_error")]
            public bool IsAccessCodeError { get; init; } = default!;
        }

        public sealed record UnmanagedAccessCodeErrorsFailedToRemoveFromDevice
            : UnmanagedAccessCodeErrors
        {
            [JsonPropertyName("error_code")]
            public override string ErrorCode { get; } = "failed_to_remove_from_device";

            /// <summary>
            /// Date and time at which Seam created the error.
            /// </summary>
            [JsonPropertyName("created_at")]
            public string? CreatedAt { get; init; }

            /// <summary>
            /// Indicates that this is an access code error.
            /// </summary>
            [JsonPropertyName("is_access_code_error")]
            public bool IsAccessCodeError { get; init; } = default!;
        }

        public sealed record UnmanagedAccessCodeErrorsDuplicateCodeOnDevice
            : UnmanagedAccessCodeErrors
        {
            [JsonPropertyName("error_code")]
            public override string ErrorCode { get; } = "duplicate_code_on_device";

            /// <summary>
            /// Date and time at which Seam created the error.
            /// </summary>
            [JsonPropertyName("created_at")]
            public string? CreatedAt { get; init; }

            /// <summary>
            /// Indicates that this is an access code error.
            /// </summary>
            [JsonPropertyName("is_access_code_error")]
            public bool IsAccessCodeError { get; init; } = default!;

            /// <summary>
            /// ID of the managed access code that conflicts with this managed access code, when Seam can identify it.
            /// </summary>
            [JsonPropertyName("managed_access_code_id")]
            public string? ManagedAccessCodeId { get; init; }

            /// <summary>
            /// ID of the unmanaged access code that conflicts with this managed access code, when Seam can identify it.
            /// </summary>
            [JsonPropertyName("unmanaged_access_code_id")]
            public string? UnmanagedAccessCodeId { get; init; }
        }

        public sealed record UnmanagedAccessCodeErrorsNoSpaceForAccessCodeOnDevice
            : UnmanagedAccessCodeErrors
        {
            [JsonPropertyName("error_code")]
            public override string ErrorCode { get; } = "no_space_for_access_code_on_device";

            /// <summary>
            /// Date and time at which Seam created the error.
            /// </summary>
            [JsonPropertyName("created_at")]
            public string? CreatedAt { get; init; }

            /// <summary>
            /// Indicates that this is an access code error.
            /// </summary>
            [JsonPropertyName("is_access_code_error")]
            public bool IsAccessCodeError { get; init; } = default!;
        }

        public sealed record UnmanagedAccessCodeErrorsConflictingExternalModification
            : UnmanagedAccessCodeErrors
        {
            /// <summary>
            /// Indicates the type of external modification. `modified` means the code&apos;s PIN or schedule was changed. `removed` means the code was deleted from the device.
            /// </summary>
            [JsonConverter(typeof(SeamStringEnumConverter))]
            public enum ChangeTypeEnum
            {
                [EnumMember(Value = "unrecognized")]
                Unrecognized = 0,

                [EnumMember(Value = "modified")]
                Modified = 1,

                [EnumMember(Value = "removed")]
                Removed = 2,
            }

            [JsonPropertyName("error_code")]
            public override string ErrorCode { get; } = "conflicting_external_modification";

            /// <summary>
            /// Indicates the type of external modification. `modified` means the code&apos;s PIN or schedule was changed. `removed` means the code was deleted from the device.
            /// </summary>
            [JsonPropertyName("change_type")]
            public UnmanagedAccessCodeErrorsConflictingExternalModification.ChangeTypeEnum? ChangeType { get; init; }

            /// <summary>
            /// Date and time at which Seam created the error.
            /// </summary>
            [JsonPropertyName("created_at")]
            public string? CreatedAt { get; init; }

            /// <summary>
            /// Indicates that this is an access code error.
            /// </summary>
            [JsonPropertyName("is_access_code_error")]
            public bool IsAccessCodeError { get; init; } = default!;

            /// <summary>
            /// List of fields that were changed externally, with their previous and new values.
            /// </summary>
            [JsonPropertyName("modified_fields")]
            public List<UnmanagedAccessCodeErrorsConflictingExternalModificationModifiedFields>? ModifiedFields { get; init; }
        }

        public sealed record UnmanagedAccessCodeErrorsConflictingExternalModificationModifiedFields
        {
            /// <summary>
            /// The name of the field that was changed (e.g. `code`, `starts_at`, `ends_at`).
            /// </summary>
            [JsonPropertyName("field")]
            public string Field { get; init; } = default!;

            /// <summary>
            /// The previous value of the field.
            /// </summary>
            [JsonPropertyName("from")]
            public string? From { get; init; }

            /// <summary>
            /// The new value of the field.
            /// </summary>
            [JsonPropertyName("to")]
            public string? To { get; init; }
        }

        public sealed record UnmanagedAccessCodeErrorsAccessCodeInactive : UnmanagedAccessCodeErrors
        {
            [JsonPropertyName("error_code")]
            public override string ErrorCode { get; } = "access_code_inactive";

            /// <summary>
            /// Date and time at which Seam created the error.
            /// </summary>
            [JsonPropertyName("created_at")]
            public string? CreatedAt { get; init; }

            /// <summary>
            /// Indicates that this is an access code error.
            /// </summary>
            [JsonPropertyName("is_access_code_error")]
            public bool IsAccessCodeError { get; init; } = default!;
        }

        public sealed record UnmanagedAccessCodeErrorsCodeConstraintsViolated
            : UnmanagedAccessCodeErrors
        {
            [JsonPropertyName("error_code")]
            public override string ErrorCode { get; } = "code_constraints_violated";

            /// <summary>
            /// Date and time at which Seam created the error.
            /// </summary>
            [JsonPropertyName("created_at")]
            public string? CreatedAt { get; init; }

            /// <summary>
            /// Indicates that this is an access code error.
            /// </summary>
            [JsonPropertyName("is_access_code_error")]
            public bool IsAccessCodeError { get; init; } = default!;
        }

        public sealed record UnmanagedAccessCodeErrorsAccountDisconnected
            : UnmanagedAccessCodeErrors
        {
            [JsonPropertyName("error_code")]
            public override string ErrorCode { get; } = "account_disconnected";

            /// <summary>
            /// Date and time at which Seam created the error.
            /// </summary>
            [JsonPropertyName("created_at")]
            public string CreatedAt { get; init; } = default!;

            /// <summary>
            /// Indicates that the error is a [connected account](https://docs.seam.co/api/connected_accounts) error.
            /// </summary>
            [JsonPropertyName("is_connected_account_error")]
            public bool IsConnectedAccountError { get; init; } = default!;

            /// <summary>
            /// Indicates that the error is not a device error.
            /// </summary>
            [JsonPropertyName("is_device_error")]
            public bool IsDeviceError { get; init; } = default!;
        }

        public sealed record UnmanagedAccessCodeErrorsSaltoKsSubscriptionLimitExceeded
            : UnmanagedAccessCodeErrors
        {
            [JsonPropertyName("error_code")]
            public override string ErrorCode { get; } = "salto_ks_subscription_limit_exceeded";

            /// <summary>
            /// Date and time at which Seam created the error.
            /// </summary>
            [JsonPropertyName("created_at")]
            public string CreatedAt { get; init; } = default!;

            /// <summary>
            /// Indicates that the error is a [connected account](https://docs.seam.co/api/connected_accounts) error.
            /// </summary>
            [JsonPropertyName("is_connected_account_error")]
            public bool IsConnectedAccountError { get; init; } = default!;

            /// <summary>
            /// Indicates that the error is not a device error.
            /// </summary>
            [JsonPropertyName("is_device_error")]
            public bool IsDeviceError { get; init; } = default!;
        }

        public sealed record UnmanagedAccessCodeErrorsInsufficientPermissions
            : UnmanagedAccessCodeErrors
        {
            [JsonPropertyName("error_code")]
            public override string ErrorCode { get; } = "insufficient_permissions";

            /// <summary>
            /// Date and time at which Seam created the error.
            /// </summary>
            [JsonPropertyName("created_at")]
            public string CreatedAt { get; init; } = default!;

            /// <summary>
            /// Indicates that the error is a [connected account](https://docs.seam.co/api/connected_accounts) error.
            /// </summary>
            [JsonPropertyName("is_connected_account_error")]
            public bool IsConnectedAccountError { get; init; } = default!;

            /// <summary>
            /// Indicates that the error is not a device error.
            /// </summary>
            [JsonPropertyName("is_device_error")]
            public bool IsDeviceError { get; init; } = default!;
        }

        public sealed record UnmanagedAccessCodeErrorsDormakabaSitesDisconnected
            : UnmanagedAccessCodeErrors
        {
            [JsonPropertyName("error_code")]
            public override string ErrorCode { get; } = "dormakaba_sites_disconnected";

            /// <summary>
            /// Date and time at which Seam created the error.
            /// </summary>
            [JsonPropertyName("created_at")]
            public string CreatedAt { get; init; } = default!;

            /// <summary>
            /// Indicates that the error is a [connected account](https://docs.seam.co/api/connected_accounts) error.
            /// </summary>
            [JsonPropertyName("is_connected_account_error")]
            public bool IsConnectedAccountError { get; init; } = default!;

            /// <summary>
            /// Indicates that the error is not a device error.
            /// </summary>
            [JsonPropertyName("is_device_error")]
            public bool IsDeviceError { get; init; } = default!;
        }

        public sealed record UnmanagedAccessCodeErrorsDeviceOffline : UnmanagedAccessCodeErrors
        {
            [JsonPropertyName("error_code")]
            public override string ErrorCode { get; } = "device_offline";

            /// <summary>
            /// Date and time at which Seam created the error.
            /// </summary>
            [JsonPropertyName("created_at")]
            public string CreatedAt { get; init; } = default!;

            /// <summary>
            /// Indicates that the error is a device error.
            /// </summary>
            [JsonPropertyName("is_device_error")]
            public bool IsDeviceError { get; init; } = default!;
        }

        public sealed record UnmanagedAccessCodeErrorsDeviceRemoved : UnmanagedAccessCodeErrors
        {
            [JsonPropertyName("error_code")]
            public override string ErrorCode { get; } = "device_removed";

            /// <summary>
            /// Date and time at which Seam created the error.
            /// </summary>
            [JsonPropertyName("created_at")]
            public string CreatedAt { get; init; } = default!;

            /// <summary>
            /// Indicates that the error is a device error.
            /// </summary>
            [JsonPropertyName("is_device_error")]
            public bool IsDeviceError { get; init; } = default!;
        }

        public sealed record UnmanagedAccessCodeErrorsHubDisconnected : UnmanagedAccessCodeErrors
        {
            [JsonPropertyName("error_code")]
            public override string ErrorCode { get; } = "hub_disconnected";

            /// <summary>
            /// Date and time at which Seam created the error.
            /// </summary>
            [JsonPropertyName("created_at")]
            public string CreatedAt { get; init; } = default!;

            /// <summary>
            /// Indicates that the error is a device error.
            /// </summary>
            [JsonPropertyName("is_device_error")]
            public bool IsDeviceError { get; init; } = default!;
        }

        public sealed record UnmanagedAccessCodeErrorsDeviceDisconnected : UnmanagedAccessCodeErrors
        {
            [JsonPropertyName("error_code")]
            public override string ErrorCode { get; } = "device_disconnected";

            /// <summary>
            /// Date and time at which Seam created the error.
            /// </summary>
            [JsonPropertyName("created_at")]
            public string CreatedAt { get; init; } = default!;

            /// <summary>
            /// Indicates that the error is a device error.
            /// </summary>
            [JsonPropertyName("is_device_error")]
            public bool IsDeviceError { get; init; } = default!;
        }

        public sealed record UnmanagedAccessCodeErrorsEmptyBackupAccessCodePool
            : UnmanagedAccessCodeErrors
        {
            [JsonPropertyName("error_code")]
            public override string ErrorCode { get; } = "empty_backup_access_code_pool";

            /// <summary>
            /// Date and time at which Seam created the error.
            /// </summary>
            [JsonPropertyName("created_at")]
            public string CreatedAt { get; init; } = default!;

            /// <summary>
            /// Indicates that the error is a device error.
            /// </summary>
            [JsonPropertyName("is_device_error")]
            public bool IsDeviceError { get; init; } = default!;
        }

        public sealed record UnmanagedAccessCodeErrorsAugustLockNotAuthorized
            : UnmanagedAccessCodeErrors
        {
            [JsonPropertyName("error_code")]
            public override string ErrorCode { get; } = "august_lock_not_authorized";

            /// <summary>
            /// Date and time at which Seam created the error.
            /// </summary>
            [JsonPropertyName("created_at")]
            public string CreatedAt { get; init; } = default!;

            /// <summary>
            /// Indicates that the error is a device error.
            /// </summary>
            [JsonPropertyName("is_device_error")]
            public bool IsDeviceError { get; init; } = default!;
        }

        public sealed record UnmanagedAccessCodeErrorsMissingDeviceCredentials
            : UnmanagedAccessCodeErrors
        {
            [JsonPropertyName("error_code")]
            public override string ErrorCode { get; } = "missing_device_credentials";

            /// <summary>
            /// Date and time at which Seam created the error.
            /// </summary>
            [JsonPropertyName("created_at")]
            public string CreatedAt { get; init; } = default!;

            /// <summary>
            /// Indicates that the error is a device error.
            /// </summary>
            [JsonPropertyName("is_device_error")]
            public bool IsDeviceError { get; init; } = default!;
        }

        public sealed record UnmanagedAccessCodeErrorsAuxiliaryHeatRunning
            : UnmanagedAccessCodeErrors
        {
            [JsonPropertyName("error_code")]
            public override string ErrorCode { get; } = "auxiliary_heat_running";

            /// <summary>
            /// Date and time at which Seam created the error.
            /// </summary>
            [JsonPropertyName("created_at")]
            public string CreatedAt { get; init; } = default!;

            /// <summary>
            /// Indicates that the error is a device error.
            /// </summary>
            [JsonPropertyName("is_device_error")]
            public bool IsDeviceError { get; init; } = default!;
        }

        public sealed record UnmanagedAccessCodeErrorsSubscriptionRequired
            : UnmanagedAccessCodeErrors
        {
            [JsonPropertyName("error_code")]
            public override string ErrorCode { get; } = "subscription_required";

            /// <summary>
            /// Date and time at which Seam created the error.
            /// </summary>
            [JsonPropertyName("created_at")]
            public string CreatedAt { get; init; } = default!;

            /// <summary>
            /// Indicates that the error is a device error.
            /// </summary>
            [JsonPropertyName("is_device_error")]
            public bool IsDeviceError { get; init; } = default!;
        }

        public sealed record UnmanagedAccessCodeErrorsBridgeDisconnected : UnmanagedAccessCodeErrors
        {
            [JsonPropertyName("error_code")]
            public override string ErrorCode { get; } = "bridge_disconnected";

            /// <summary>
            /// Date and time at which Seam created the error.
            /// </summary>
            [JsonPropertyName("created_at")]
            public string CreatedAt { get; init; } = default!;

            /// <summary>
            /// Indicates whether the error is related to [Seam Bridge](https://docs.seam.co/capability-guides/seam-bridge).
            /// </summary>
            [JsonPropertyName("is_bridge_error")]
            public bool? IsBridgeError { get; init; }

            /// <summary>
            /// Indicates whether the error is related specifically to the connected account.
            /// </summary>
            [JsonPropertyName("is_connected_account_error")]
            public bool? IsConnectedAccountError { get; init; }
        }

        public sealed record UnmanagedAccessCodeErrorsUnrecognized
            : UnmanagedAccessCodeErrors,
                ISeamUnrecognizedVariant
        {
            [JsonPropertyName("error_code")]
            public override string ErrorCode { get; } = "unrecognized";

            /// <summary>The complete raw JSON of the unrecognized payload.</summary>
            [JsonIgnore]
            public JsonElement RawJson { get; set; }
        }

        /// <summary>
        /// Current status of the access code within the operational lifecycle. `set` indicates that the code is active and operational. `unset` indicates that the code exists on the provider but is not usable on the device.
        /// </summary>
        [JsonConverter(typeof(SeamStringEnumConverter))]
        public enum StatusEnum
        {
            [EnumMember(Value = "unrecognized")]
            Unrecognized = 0,

            [EnumMember(Value = "set")]
            Set = 1,

            [EnumMember(Value = "unset")]
            Unset = 2,
        }

        /// <summary>
        /// Type of the access code. `ongoing` access codes are active continuously until deactivated manually. `time_bound` access codes have a specific duration.
        /// </summary>
        [JsonConverter(typeof(SeamStringEnumConverter))]
        public enum TypeEnum
        {
            [EnumMember(Value = "unrecognized")]
            Unrecognized = 0,

            [EnumMember(Value = "time_bound")]
            TimeBound = 1,

            [EnumMember(Value = "ongoing")]
            Ongoing = 2,
        }

        [JsonConverter(typeof(SeamUnionConverter))]
        [SeamUnion("warning_code")]
        [SeamUnionVariant(
            "code_rotates_periodically",
            typeof(UnmanagedAccessCodeWarningsCodeRotatesPeriodically)
        )]
        [SeamUnionVariant(
            "time_frame_adjusted_for_unknown_time_zone",
            typeof(UnmanagedAccessCodeWarningsTimeFrameAdjustedForUnknownTimeZone)
        )]
        [SeamUnionVariant(
            "external_modification_in_effect",
            typeof(UnmanagedAccessCodeWarningsExternalModificationInEffect)
        )]
        [SeamUnionVariant(
            "delay_in_setting_on_device",
            typeof(UnmanagedAccessCodeWarningsDelayInSettingOnDevice)
        )]
        [SeamUnionVariant(
            "delay_in_removing_from_device",
            typeof(UnmanagedAccessCodeWarningsDelayInRemovingFromDevice)
        )]
        [SeamUnionVariant(
            "third_party_integration_detected",
            typeof(UnmanagedAccessCodeWarningsThirdPartyIntegrationDetected)
        )]
        [SeamUnionVariant(
            "igloo_algopin_must_be_used_within_24_hours",
            typeof(UnmanagedAccessCodeWarningsIglooAlgopinMustBeUsedWithin_24Hours)
        )]
        [SeamUnionVariant(
            "management_transferred",
            typeof(UnmanagedAccessCodeWarningsManagementTransferred)
        )]
        [SeamUnionVariant(
            "using_backup_access_code",
            typeof(UnmanagedAccessCodeWarningsUsingBackupAccessCode)
        )]
        [SeamUnionVariant("being_deleted", typeof(UnmanagedAccessCodeWarningsBeingDeleted))]
        [SeamUnionVariant(
            "unknown_issue_with_access_code",
            typeof(UnmanagedAccessCodeWarningsUnknownIssueWithAccessCode)
        )]
        [SeamUnionFallback(typeof(UnmanagedAccessCodeWarningsUnrecognized))]
        public abstract record UnmanagedAccessCodeWarnings
        {
            /// <summary>The value of the <c>warning_code</c> discriminator.</summary>
            public abstract string WarningCode { get; }

            /// <summary>
            /// Date and time at which Seam created the warning.
            /// </summary>
            [JsonPropertyName("created_at")]
            public string? CreatedAt { get; init; }

            /// <summary>
            /// Detailed description of the warning. Provides insights into the issue and potentially how to rectify it.
            /// </summary>
            [JsonPropertyName("message")]
            public string Message { get; init; } = default!;
        }

        public sealed record UnmanagedAccessCodeWarningsCodeRotatesPeriodically
            : UnmanagedAccessCodeWarnings
        {
            [JsonPropertyName("warning_code")]
            public override string WarningCode { get; } = "code_rotates_periodically";
        }

        public sealed record UnmanagedAccessCodeWarningsTimeFrameAdjustedForUnknownTimeZone
            : UnmanagedAccessCodeWarnings
        {
            [JsonPropertyName("warning_code")]
            public override string WarningCode { get; } =
                "time_frame_adjusted_for_unknown_time_zone";
        }

        public sealed record UnmanagedAccessCodeWarningsExternalModificationInEffect
            : UnmanagedAccessCodeWarnings
        {
            /// <summary>
            /// Indicates the type of external modification. `modified` means the code&apos;s PIN or schedule was changed. `removed` means the code was deleted from the device.
            /// </summary>
            [JsonConverter(typeof(SeamStringEnumConverter))]
            public enum ChangeTypeEnum
            {
                [EnumMember(Value = "unrecognized")]
                Unrecognized = 0,

                [EnumMember(Value = "modified")]
                Modified = 1,

                [EnumMember(Value = "removed")]
                Removed = 2,
            }

            [JsonPropertyName("warning_code")]
            public override string WarningCode { get; } = "external_modification_in_effect";

            /// <summary>
            /// Indicates the type of external modification. `modified` means the code&apos;s PIN or schedule was changed. `removed` means the code was deleted from the device.
            /// </summary>
            [JsonPropertyName("change_type")]
            public UnmanagedAccessCodeWarningsExternalModificationInEffect.ChangeTypeEnum? ChangeType { get; init; }

            /// <summary>
            /// List of fields that were changed externally, with their previous and new values.
            /// </summary>
            [JsonPropertyName("modified_fields")]
            public List<UnmanagedAccessCodeWarningsExternalModificationInEffectModifiedFields>? ModifiedFields { get; init; }
        }

        public sealed record UnmanagedAccessCodeWarningsExternalModificationInEffectModifiedFields
        {
            /// <summary>
            /// The name of the field that was changed (e.g. `code`, `starts_at`, `ends_at`).
            /// </summary>
            [JsonPropertyName("field")]
            public string Field { get; init; } = default!;

            /// <summary>
            /// The previous value of the field.
            /// </summary>
            [JsonPropertyName("from")]
            public string? From { get; init; }

            /// <summary>
            /// The new value of the field.
            /// </summary>
            [JsonPropertyName("to")]
            public string? To { get; init; }
        }

        public sealed record UnmanagedAccessCodeWarningsDelayInSettingOnDevice
            : UnmanagedAccessCodeWarnings
        {
            [JsonPropertyName("warning_code")]
            public override string WarningCode { get; } = "delay_in_setting_on_device";
        }

        public sealed record UnmanagedAccessCodeWarningsDelayInRemovingFromDevice
            : UnmanagedAccessCodeWarnings
        {
            [JsonPropertyName("warning_code")]
            public override string WarningCode { get; } = "delay_in_removing_from_device";
        }

        public sealed record UnmanagedAccessCodeWarningsThirdPartyIntegrationDetected
            : UnmanagedAccessCodeWarnings
        {
            [JsonPropertyName("warning_code")]
            public override string WarningCode { get; } = "third_party_integration_detected";
        }

        public sealed record UnmanagedAccessCodeWarningsIglooAlgopinMustBeUsedWithin_24Hours
            : UnmanagedAccessCodeWarnings
        {
            [JsonPropertyName("warning_code")]
            public override string WarningCode { get; } =
                "igloo_algopin_must_be_used_within_24_hours";
        }

        public sealed record UnmanagedAccessCodeWarningsManagementTransferred
            : UnmanagedAccessCodeWarnings
        {
            [JsonPropertyName("warning_code")]
            public override string WarningCode { get; } = "management_transferred";
        }

        public sealed record UnmanagedAccessCodeWarningsUsingBackupAccessCode
            : UnmanagedAccessCodeWarnings
        {
            [JsonPropertyName("warning_code")]
            public override string WarningCode { get; } = "using_backup_access_code";
        }

        public sealed record UnmanagedAccessCodeWarningsBeingDeleted : UnmanagedAccessCodeWarnings
        {
            [JsonPropertyName("warning_code")]
            public override string WarningCode { get; } = "being_deleted";
        }

        public sealed record UnmanagedAccessCodeWarningsUnknownIssueWithAccessCode
            : UnmanagedAccessCodeWarnings
        {
            [JsonPropertyName("warning_code")]
            public override string WarningCode { get; } = "unknown_issue_with_access_code";
        }

        public sealed record UnmanagedAccessCodeWarningsUnrecognized
            : UnmanagedAccessCodeWarnings,
                ISeamUnrecognizedVariant
        {
            [JsonPropertyName("warning_code")]
            public override string WarningCode { get; } = "unrecognized";

            /// <summary>The complete raw JSON of the unrecognized payload.</summary>
            [JsonIgnore]
            public JsonElement RawJson { get; set; }
        }

        /// <summary>
        /// Unique identifier for the access code.
        /// </summary>
        [JsonPropertyName("access_code_id")]
        public string AccessCodeId { get; init; } = default!;

        /// <summary>
        /// Indicates that Seam cannot convert this unmanaged access code to a managed access code. Some providers do not support management of unmanaged access codes through API integrations.
        /// </summary>
        [JsonPropertyName("cannot_be_managed")]
        public bool? CannotBeManaged { get; init; }

        /// <summary>
        /// Indicates that Seam cannot delete this unmanaged access code through the provider. If this access code needs to be deleted, it will only be possible from the manufacturer app.
        /// </summary>
        [JsonPropertyName("cannot_delete_unmanaged_access_code")]
        public bool? CannotDeleteUnmanagedAccessCode { get; init; }

        /// <summary>
        /// Code used for access. Typically, a numeric or alphanumeric string.
        /// </summary>
        [JsonPropertyName("code")]
        public string? Code { get; init; }

        /// <summary>
        /// Date and time at which the access code was created.
        /// </summary>
        [JsonPropertyName("created_at")]
        public string CreatedAt { get; init; } = default!;

        /// <summary>
        /// Unique identifier for the device associated with the access code.
        /// </summary>
        [JsonPropertyName("device_id")]
        public string DeviceId { get; init; } = default!;

        /// <summary>
        /// Metadata for a dormakaba Oracode unmanaged access code. Only present for unmanaged access codes from dormakaba Oracode devices.
        /// </summary>
        [JsonPropertyName("dormakaba_oracode_metadata")]
        public UnmanagedAccessCodeDormakabaOracodeMetadata? DormakabaOracodeMetadata { get; init; }

        /// <summary>
        /// Date and time after which the time-bound access code becomes inactive.
        /// </summary>
        [JsonPropertyName("ends_at")]
        public string? EndsAt { get; init; }

        /// <summary>
        /// Errors associated with the [access code](https://docs.seam.co/low-level-apis/smart-locks/access-codes).
        /// </summary>
        [JsonPropertyName("errors")]
        public List<UnmanagedAccessCodeErrors> Errors { get; init; } = default!;

        /// <summary>
        /// Indicates that Seam does not manage the access code.
        /// </summary>
        [JsonPropertyName("is_managed")]
        public bool IsManaged { get; init; } = default!;

        /// <summary>
        /// Name of the access code. Enables administrators and users to identify the access code easily, especially when there are numerous access codes. Note that the name provided on Seam is used to identify the code on Seam and is not necessarily the name that will appear in the lock provider&apos;s app or on the device. This is because lock providers may have constraints on names, such as length, uniqueness, or characters that can be used. In addition, some lock providers may break down names into components such as `first_name` and `last_name`. To provide a consistent experience, Seam identifies the code on Seam by its name but may modify the name that appears on the lock provider&apos;s app or on the device. For example, Seam may add additional characters or truncate the name to meet provider constraints. To help your users identify codes set by Seam, Seam provides the name exactly as it appears on the lock provider&apos;s app or on the device as a separate property called `appearance`. This is an object with a `name` property and, optionally, `first_name` and `last_name` properties (for providers that break down a name into components).
        /// </summary>
        [JsonPropertyName("name")]
        public string? Name { get; init; }

        /// <summary>
        /// Date and time at which the time-bound access code becomes active.
        /// </summary>
        [JsonPropertyName("starts_at")]
        public string? StartsAt { get; init; }

        /// <summary>
        /// Current status of the access code within the operational lifecycle. `set` indicates that the code is active and operational. `unset` indicates that the code exists on the provider but is not usable on the device.
        /// </summary>
        [JsonPropertyName("status")]
        public UnmanagedAccessCode.StatusEnum Status { get; init; } = default!;

        /// <summary>
        /// Type of the access code. `ongoing` access codes are active continuously until deactivated manually. `time_bound` access codes have a specific duration.
        /// </summary>
        [JsonPropertyName("type")]
        public UnmanagedAccessCode.TypeEnum Type { get; init; } = default!;

        /// <summary>
        /// Warnings associated with the [access code](https://docs.seam.co/low-level-apis/smart-locks/access-codes).
        /// </summary>
        [JsonPropertyName("warnings")]
        public List<UnmanagedAccessCodeWarnings> Warnings { get; init; } = default!;

        /// <summary>
        /// Unique identifier for the Seam workspace associated with the access code.
        /// </summary>
        [JsonPropertyName("workspace_id")]
        public string WorkspaceId { get; init; } = default!;
    }

    public sealed record UnmanagedAccessCodeDormakabaOracodeMetadata
    {
        /// <summary>
        /// Indicates whether the stay can be cancelled via the Dormakaba Oracode API.
        /// </summary>
        [JsonPropertyName("is_cancellable")]
        public bool? IsCancellable { get; init; }

        /// <summary>
        /// Indicates whether early check-in is available for this stay.
        /// </summary>
        [JsonPropertyName("is_early_checkin_able")]
        public bool? IsEarlyCheckinAble { get; init; }

        /// <summary>
        /// Indicates whether the stay can be extended via the Dormakaba Oracode API.
        /// </summary>
        [JsonPropertyName("is_extendable")]
        public bool? IsExtendable { get; init; }

        /// <summary>
        /// Indicates whether the access code can be overridden. When false, the maximum number of overrides has been reached.
        /// </summary>
        [JsonPropertyName("is_overridable")]
        public bool? IsOverridable { get; init; }

        /// <summary>
        /// Dormakaba Oracode site name associated with this access code.
        /// </summary>
        [JsonPropertyName("site_name")]
        public string? SiteName { get; init; }

        /// <summary>
        /// Dormakaba Oracode stay ID associated with this access code.
        /// </summary>
        [JsonPropertyName("stay_id")]
        public float? StayId { get; init; }

        /// <summary>
        /// Dormakaba Oracode user level ID associated with this access code.
        /// </summary>
        [JsonPropertyName("user_level_id")]
        public string? UserLevelId { get; init; }

        /// <summary>
        /// Dormakaba Oracode user level name associated with this access code.
        /// </summary>
        [JsonPropertyName("user_level_name")]
        public string? UserLevelName { get; init; }
    }
}
