// <auto-generated>
//   Generated by codegen/smith.ts from @seamapi/types. Do not edit.
// </auto-generated>
#nullable enable
#pragma warning disable CS0618 // The generated code references its own deprecated members.
using System.Runtime.Serialization;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Seam.Models
{
    /// <summary>
    /// Represents an unmanaged access method. Unmanaged access methods do not have client sessions, instant keys, customization profiles, or keys.
    /// </summary>
    public sealed record UnmanagedAccessMethod
    {
        [JsonConverter(typeof(SeamUnionConverter))]
        [SeamUnion("error_code")]
        [SeamUnionVariant("failed_to_issue", typeof(UnmanagedAccessMethodErrorsFailedToIssue))]
        [SeamUnionFallback(typeof(UnmanagedAccessMethodErrorsUnrecognized))]
        public abstract record UnmanagedAccessMethodErrors
        {
            /// <summary>The value of the <c>error_code</c> discriminator.</summary>
            public abstract string ErrorCode { get; }

            /// <summary>
            /// Date and time at which Seam created the error.
            /// </summary>
            [JsonPropertyName("created_at")]
            public string CreatedAt { get; init; } = default!;

            /// <summary>
            /// Detailed description of the error. Provides insights into the issue and potentially how to rectify it.
            /// </summary>
            [JsonPropertyName("message")]
            public string Message { get; init; } = default!;
        }

        public sealed record UnmanagedAccessMethodErrorsFailedToIssue : UnmanagedAccessMethodErrors
        {
            [JsonPropertyName("error_code")]
            public override string ErrorCode { get; } = "failed_to_issue";
        }

        public sealed record UnmanagedAccessMethodErrorsUnrecognized
            : UnmanagedAccessMethodErrors,
                ISeamUnrecognizedVariant
        {
            [JsonPropertyName("error_code")]
            public override string ErrorCode { get; } = "unrecognized";

            /// <summary>The complete raw JSON of the unrecognized payload.</summary>
            [JsonIgnore]
            public JsonElement RawJson { get; set; }
        }

        /// <summary>
        /// Access method mode. Supported values: `code`, `card`, `mobile_key`, `cloud_key`.
        /// </summary>
        [JsonConverter(typeof(SeamStringEnumConverter))]
        public enum ModeEnum
        {
            [EnumMember(Value = "unrecognized")]
            Unrecognized = 0,

            [EnumMember(Value = "code")]
            Code = 1,

            [EnumMember(Value = "card")]
            Card = 2,

            [EnumMember(Value = "mobile_key")]
            MobileKey = 3,

            [EnumMember(Value = "cloud_key")]
            CloudKey = 4,
        }

        [JsonConverter(typeof(SeamUnionConverter))]
        [SeamUnion("mutation_code")]
        [SeamUnionVariant(
            "provisioning_access",
            typeof(UnmanagedAccessMethodPendingMutationsProvisioningAccess)
        )]
        [SeamUnionVariant(
            "revoking_access",
            typeof(UnmanagedAccessMethodPendingMutationsRevokingAccess)
        )]
        [SeamUnionVariant(
            "updating_access_times",
            typeof(UnmanagedAccessMethodPendingMutationsUpdatingAccessTimes)
        )]
        [SeamUnionFallback(typeof(UnmanagedAccessMethodPendingMutationsUnrecognized))]
        public abstract record UnmanagedAccessMethodPendingMutations
        {
            /// <summary>The value of the <c>mutation_code</c> discriminator.</summary>
            public abstract string MutationCode { get; }

            /// <summary>
            /// Date and time at which the mutation was created.
            /// </summary>
            [JsonPropertyName("created_at")]
            public string CreatedAt { get; init; } = default!;

            /// <summary>
            /// Detailed description of the mutation.
            /// </summary>
            [JsonPropertyName("message")]
            public string Message { get; init; } = default!;
        }

        public sealed record UnmanagedAccessMethodPendingMutationsProvisioningAccess
            : UnmanagedAccessMethodPendingMutations
        {
            [JsonPropertyName("mutation_code")]
            public override string MutationCode { get; } = "provisioning_access";

            /// <summary>
            /// Previous device configuration.
            /// </summary>
            [JsonPropertyName("from")]
            public UnmanagedAccessMethodPendingMutationsProvisioningAccessFrom From { get; init; } =
                default!;

            /// <summary>
            /// New device configuration.
            /// </summary>
            [JsonPropertyName("to")]
            public UnmanagedAccessMethodPendingMutationsProvisioningAccessTo To { get; init; } =
                default!;
        }

        public sealed record UnmanagedAccessMethodPendingMutationsProvisioningAccessFrom
        {
            /// <summary>
            /// Previous device IDs where access was provisioned.
            /// </summary>
            [JsonPropertyName("device_ids")]
            public List<string> DeviceIds { get; init; } = default!;
        }

        public sealed record UnmanagedAccessMethodPendingMutationsProvisioningAccessTo
        {
            /// <summary>
            /// New device IDs where access is being provisioned.
            /// </summary>
            [JsonPropertyName("device_ids")]
            public List<string> DeviceIds { get; init; } = default!;
        }

        public sealed record UnmanagedAccessMethodPendingMutationsRevokingAccess
            : UnmanagedAccessMethodPendingMutations
        {
            [JsonPropertyName("mutation_code")]
            public override string MutationCode { get; } = "revoking_access";

            /// <summary>
            /// Previous device configuration.
            /// </summary>
            [JsonPropertyName("from")]
            public UnmanagedAccessMethodPendingMutationsRevokingAccessFrom From { get; init; } =
                default!;

            /// <summary>
            /// New device configuration.
            /// </summary>
            [JsonPropertyName("to")]
            public UnmanagedAccessMethodPendingMutationsRevokingAccessTo To { get; init; } =
                default!;
        }

        public sealed record UnmanagedAccessMethodPendingMutationsRevokingAccessFrom
        {
            /// <summary>
            /// Previous device IDs where access existed.
            /// </summary>
            [JsonPropertyName("device_ids")]
            public List<string> DeviceIds { get; init; } = default!;
        }

        public sealed record UnmanagedAccessMethodPendingMutationsRevokingAccessTo
        {
            /// <summary>
            /// New device IDs where access should remain.
            /// </summary>
            [JsonPropertyName("device_ids")]
            public List<string> DeviceIds { get; init; } = default!;
        }

        public sealed record UnmanagedAccessMethodPendingMutationsUpdatingAccessTimes
            : UnmanagedAccessMethodPendingMutations
        {
            [JsonPropertyName("mutation_code")]
            public override string MutationCode { get; } = "updating_access_times";

            /// <summary>
            /// Previous access time configuration.
            /// </summary>
            [JsonPropertyName("from")]
            public UnmanagedAccessMethodPendingMutationsUpdatingAccessTimesFrom From { get; init; } =
                default!;

            /// <summary>
            /// New access time configuration.
            /// </summary>
            [JsonPropertyName("to")]
            public UnmanagedAccessMethodPendingMutationsUpdatingAccessTimesTo To { get; init; } =
                default!;
        }

        public sealed record UnmanagedAccessMethodPendingMutationsUpdatingAccessTimesFrom
        {
            /// <summary>
            /// Previous end time for access.
            /// </summary>
            [JsonPropertyName("ends_at")]
            public string? EndsAt { get; init; }

            /// <summary>
            /// Previous start time for access.
            /// </summary>
            [JsonPropertyName("starts_at")]
            public string? StartsAt { get; init; }
        }

        public sealed record UnmanagedAccessMethodPendingMutationsUpdatingAccessTimesTo
        {
            /// <summary>
            /// New end time for access.
            /// </summary>
            [JsonPropertyName("ends_at")]
            public string? EndsAt { get; init; }

            /// <summary>
            /// New start time for access.
            /// </summary>
            [JsonPropertyName("starts_at")]
            public string? StartsAt { get; init; }
        }

        public sealed record UnmanagedAccessMethodPendingMutationsUnrecognized
            : UnmanagedAccessMethodPendingMutations,
                ISeamUnrecognizedVariant
        {
            [JsonPropertyName("mutation_code")]
            public override string MutationCode { get; } = "unrecognized";

            /// <summary>The complete raw JSON of the unrecognized payload.</summary>
            [JsonIgnore]
            public JsonElement RawJson { get; set; }
        }

        [JsonConverter(typeof(SeamUnionConverter))]
        [SeamUnion("warning_code")]
        [SeamUnionVariant("being_deleted", typeof(UnmanagedAccessMethodWarningsBeingDeleted))]
        [SeamUnionVariant(
            "updating_access_times",
            typeof(UnmanagedAccessMethodWarningsUpdatingAccessTimes)
        )]
        [SeamUnionVariant(
            "pulled_backup_access_code",
            typeof(UnmanagedAccessMethodWarningsPulledBackupAccessCode)
        )]
        [SeamUnionVariant("delay_in_issuing", typeof(UnmanagedAccessMethodWarningsDelayInIssuing))]
        [SeamUnionFallback(typeof(UnmanagedAccessMethodWarningsUnrecognized))]
        public abstract record UnmanagedAccessMethodWarnings
        {
            /// <summary>The value of the <c>warning_code</c> discriminator.</summary>
            public abstract string WarningCode { get; }

            /// <summary>
            /// Date and time at which Seam created the warning.
            /// </summary>
            [JsonPropertyName("created_at")]
            public string CreatedAt { get; init; } = default!;

            /// <summary>
            /// Detailed description of the warning. Provides insights into the issue and potentially how to rectify it.
            /// </summary>
            [JsonPropertyName("message")]
            public string Message { get; init; } = default!;
        }

        public sealed record UnmanagedAccessMethodWarningsBeingDeleted
            : UnmanagedAccessMethodWarnings
        {
            [JsonPropertyName("warning_code")]
            public override string WarningCode { get; } = "being_deleted";
        }

        public sealed record UnmanagedAccessMethodWarningsUpdatingAccessTimes
            : UnmanagedAccessMethodWarnings
        {
            [JsonPropertyName("warning_code")]
            public override string WarningCode { get; } = "updating_access_times";
        }

        public sealed record UnmanagedAccessMethodWarningsPulledBackupAccessCode
            : UnmanagedAccessMethodWarnings
        {
            [JsonPropertyName("warning_code")]
            public override string WarningCode { get; } = "pulled_backup_access_code";

            /// <summary>
            /// ID of the original access method from which this backup access method was split, if applicable.
            /// </summary>
            [JsonPropertyName("original_access_method_id")]
            public string? OriginalAccessMethodId { get; init; }
        }

        public sealed record UnmanagedAccessMethodWarningsDelayInIssuing
            : UnmanagedAccessMethodWarnings
        {
            [JsonPropertyName("warning_code")]
            public override string WarningCode { get; } = "delay_in_issuing";
        }

        public sealed record UnmanagedAccessMethodWarningsUnrecognized
            : UnmanagedAccessMethodWarnings,
                ISeamUnrecognizedVariant
        {
            [JsonPropertyName("warning_code")]
            public override string WarningCode { get; } = "unrecognized";

            /// <summary>The complete raw JSON of the unrecognized payload.</summary>
            [JsonIgnore]
            public JsonElement RawJson { get; set; }
        }

        /// <summary>
        /// ID of the access method.
        /// </summary>
        [JsonPropertyName("access_method_id")]
        public string AccessMethodId { get; init; } = default!;

        /// <summary>
        /// The actual PIN code for code access methods.
        /// </summary>
        [JsonPropertyName("code")]
        public string? Code { get; init; }

        /// <summary>
        /// Date and time at which the access method was created.
        /// </summary>
        [JsonPropertyName("created_at")]
        public string CreatedAt { get; init; } = default!;

        /// <summary>
        /// Display name of the access method.
        /// </summary>
        [JsonPropertyName("display_name")]
        public string DisplayName { get; init; } = default!;

        /// <summary>
        /// Human-readable sentence describing where the access method sits in its relationship with the device or access system, for example `Awaiting encoding`. For display only. The wording is not stable and is not an enumeration — it may change at any time, so never compare against or branch on it. To make decisions, read `is_issued`, `errors`, and `pending_mutations`.
        /// </summary>
        [JsonPropertyName("display_status")]
        public string DisplayStatus { get; init; } = default!;

        /// <summary>
        /// Errors associated with the [access method](https://docs.seam.co/use-cases/granting-access/creating-an-access-grant).
        /// </summary>
        [JsonPropertyName("errors")]
        public List<UnmanagedAccessMethodErrors> Errors { get; init; } = default!;

        /// <summary>
        /// Indicates whether an existing card credential must be assigned to this access method before it can be issued. Only applies to card-mode access methods on systems that support credential assignment.
        /// </summary>
        [JsonPropertyName("is_assignment_required")]
        public bool? IsAssignmentRequired { get; init; }

        /// <summary>
        /// Indicates whether encoding with an card encoder is required to issue or reissue the plastic card associated with the access method.
        /// </summary>
        [JsonPropertyName("is_encoding_required")]
        public bool? IsEncodingRequired { get; init; }

        /// <summary>
        /// Indicates whether the access method has been issued.
        /// </summary>
        [JsonPropertyName("is_issued")]
        public bool IsIssued { get; init; } = default!;

        /// <summary>
        /// Indicates whether the access method is ready for card assignment. This is true when the access method is in card mode, has not yet been issued, and the system supports credential assignment.
        /// </summary>
        [JsonPropertyName("is_ready_for_assignment")]
        public bool? IsReadyForAssignment { get; init; }

        /// <summary>
        /// Indicates whether the access method is ready to be encoded. This is true when the credential has been created and the card has not yet been issued.
        /// </summary>
        [JsonPropertyName("is_ready_for_encoding")]
        public bool? IsReadyForEncoding { get; init; }

        /// <summary>
        /// Date and time at which the access method was issued.
        /// </summary>
        [JsonPropertyName("issued_at")]
        public string? IssuedAt { get; init; }

        /// <summary>
        /// Access method mode. Supported values: `code`, `card`, `mobile_key`, `cloud_key`.
        /// </summary>
        [JsonPropertyName("mode")]
        public UnmanagedAccessMethod.ModeEnum Mode { get; init; } = default!;

        /// <summary>
        /// Pending mutations for the [access method](https://docs.seam.co/use-cases/granting-access/creating-an-access-grant). Indicates operations that are in progress.
        /// </summary>
        [JsonPropertyName("pending_mutations")]
        public List<UnmanagedAccessMethodPendingMutations> PendingMutations { get; init; } =
            default!;

        /// <summary>
        /// Warnings associated with the [access method](https://docs.seam.co/use-cases/granting-access/creating-an-access-grant).
        /// </summary>
        [JsonPropertyName("warnings")]
        public List<UnmanagedAccessMethodWarnings> Warnings { get; init; } = default!;

        /// <summary>
        /// ID of the Seam workspace associated with the access method.
        /// </summary>
        [JsonPropertyName("workspace_id")]
        public string WorkspaceId { get; init; } = default!;
    }
}
