// <auto-generated>
//   Generated by codegen/smith.ts from @seamapi/types. Do not edit.
// </auto-generated>
#nullable enable
#pragma warning disable CS0618 // The generated code references its own deprecated members.
using System.Runtime.Serialization;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Seam.Models
{
    /// <summary>
    /// Represents a [webhook](https://docs.seam.co/developer-tools/webhooks) that enables you to receive notifications of events. When you create a webhook, specify the endpoint URL at which you want to receive events and the set of event types that you want to receive.
    /// </summary>
    public sealed record Webhook
    {
        /// <summary>
        /// Types of events that the [webhook](https://docs.seam.co/developer-tools/webhooks) should receive.
        /// </summary>
        [JsonPropertyName("event_types")]
        public List<string>? EventTypes { get; init; }

        /// <summary>
        /// Secret associated with the [webhook](https://docs.seam.co/developer-tools/webhooks).
        /// </summary>
        [JsonPropertyName("secret")]
        public string? Secret { get; init; }

        /// <summary>
        /// URL for the [webhook](https://docs.seam.co/developer-tools/webhooks).
        /// </summary>
        [JsonPropertyName("url")]
        public string Url { get; init; } = default!;

        /// <summary>
        /// ID of the webhook.
        /// </summary>
        [JsonPropertyName("webhook_id")]
        public string WebhookId { get; init; } = default!;
    }
}
