---
name: _build

on:
  workflow_call:
    inputs:
      dotnet_version:
        description: The .NET SDK versions to install.
        type: string
        required: false
        default: |
          6.0.x
          8.0.x
    outputs:
      artifact_name:
        description: The artifact name.
        value: build-${{ github.sha }}

jobs:
  build:
    name: Package
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup
        uses: ./.github/actions/setup
        with:
          dotnet_version: ${{ inputs.dotnet_version }}
      - name: Setup Node.js
        uses: ./.github/actions/setup-node
      - name: Build
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: build-${{ github.sha }}
          if-no-files-found: error
          path: pkg/
